### ISSUE TITLE
2019 budget roadshow: EPIC

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1031]
Contact: 
Due: 

Short term goal: 
The budgeting office would like to create a roadshow / lightning talks to create interest in how the budget works. The talks and exhibit will rotate along a number of spaces.

MONUM deliverables:
- MONUM will act as a project manager
- MONUM will provide the Digital Team with requested documentation and information.

Digital team deliverables:
- An advertising campaign that drives residents to the webpage/ lighting talks/ exhibits.
Parent of #1032

- 4-5 Portable posters that explain the budget
Parent of #1033

Longterm goal:
It is the goal of the Digital Team to create sustainable avenues for showing off budget information. Some examples that we have slated are below. 

- Redesign tax bills to be more legible
- Re-purpose the back of tax bills to indicate how taxes are used for budget
- Re-thinking the use of receipts/tickets and another official "leave behind products" to display how taxes are used for a budget.

**Comment by sebastianebarb** [comment]
@carolinestj I talked to @jfalvey about this last night. Please hold on all work. Budget is not sure if they are doing the roadshow!

**Comment by carolinestj** [comment]
https://drive.google.com/drive/folders/1OZlvPz9F5V-isE-17IPqHAZkFHq7tGSH
