### ISSUE TITLE
2019 Budget Banners

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1033]
Contact: Justin Sterritt justin.sterritt@boston.gov
Due: ~ 02/08/19 (need a solid due date)

**Comment by carolinestj** [comment]
4 Banners 3' x 8'

**Comment by carolinestj** [comment]
https://docs.google.com/presentation/d/1vITMY9-g2qv9AXsGYFpKPfGyLIsl6vGP28tyCf60i3o/edit#slide=id.g2ccbb63ee7_1_0
[Operating Budget- Spending.pptx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46c7849f318397a081eeff61b159f7913d0b67403901ad2f798be46af3006b1300051bff054a5556f9feda2ba1b369778f5409b8d1385d75c63f40f9bc844cb613a632c91edbe2e3d7158abd7f37ed998e48341f001d8bfa5d3da49e4fc051f259ac.pptx)
