### ISSUE TITLE
Create Access Boston icons

### ISSUE THREAD

**Issue by rachelbraun** [CityOfBoston/design-team-workflow#1054]
We need end-user-friendly icons for the following applications on Access Boston (by Fri, Feb 15):

- [x] 1. BAIS FN (Enterprise Financial Management tool)
- [x] 2. BAIS HCM (Enterprise Human Resources tool)
- [x] 3. BostonMaps (Search existing maps or create your own)
- [x] 4. Civis (Data Analysis tool)
- [x] 5. Employee Connect (Search for jobs only advertised to current City of Boston employees)
- [x] 6. ESS (Employee Self-Service portal)
- [x] 7. Hub (City of Boston’s intranet site featuring policies, information on health and wellness benefits, career training, as well as news and events)
- [x] 8. Hyperion (Enterprise Budget Management tool)
- [x] 9. IIQ (Enterprise Identity Management tool)
- [x] 10. My Learning Plan (Sign up for Technology Training)
- [x] 11. BPS TalentEd (Search for jobs only advertised to current Boston Public School employees)

Reach out to me with questions. I will collect and pass on for approval/integration.

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=1j4RV6uBZ3mkHGotxEoGcRTGxt5byqpjQ&authuser=sebastian.ebarb@boston.gov

**Comment by rachelbraun** [comment]
These look great. Appreciate the thought on this. Passing onto IAM.
