### ISSUE TITLE
Access Boston Portal launch: Video

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1097]
Contact: gretchen.grozier@boston.gov
Due: (4/1)

We had our IAM Executive Committee meeting yesterday and they expressed interest in having a video for the Access Boston Portal launch of the Mayor and various members of the Cabinet (mentioned specifically were Police Commissioner, Fire Commissioner, BPS Superintendent and David) registering for an account - choosing a longer & stronger password and setting up MFA.  The idea being employees would see that their leadership is on board with this exciting new product - we need to send a broadcast to all employees announcing the launch (4/1) and it could be included there.

 Kristina would film at a Cabinet meeting in March. I assume we can just film folks at a keyboard, using a phone/tablet and then interweave that with shots of the actual screens of the ABP.

**Comment by KristinaVicario** [comment]
Reached out to Gretchen to inquire about the date of the next cabinet meeting.

**Comment by KristinaVicario** [comment]
Met with Gretchen and waiting on script/ideas to be sent over. Next step to check on Mayor's schedule at AV Club meeting 3/8.

**Comment by KristinaVicario** [comment]
Filming 3/27 in David's office
