### ISSUE TITLE
Women's history month B-roll

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1099]
Contact: brenna.callahan@boston.gov

Here's the calendar of women's history month events https://www.boston.gov/departments/womens-advancement/womens-history-month the only official MOWA events are this Friday and the self-defense event on 3/23 

We do not need to get b-roll from every event!

**Comment by KristinaVicario** [comment]
Attending the International Women's day event today at 3:30 to shoot some stock footage/b-roll to be used in future videos.

**Comment by KristinaVicario** [comment]
Sent over a day-turn video on Friday. Uploaded photos to International Women's Day photo and sent over to Women's advancement
