### ISSUE TITLE
Welcome Video for Big City Emergency Managers

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1112]
Per Nancy Anderson (Point of Contact) :nancy.anderson@boston.gov

Video to be presented to the Big City Emergency Managers group coming in at the end of the month. Not looking to create something new, more on the order of curating a selection of videos already in library which could be strung together and played consecutively (YouTube perhaps?).

Looking to highlight the City's rich diversity, cultural history, progressive development etc. Basically anything that shows off our city (maybe even sports accomplishments! LA will be there and it would be fun to subtly rub it in a little)

**Comment by sebastianebarb** [comment]
https://www.youtube.com/watch?v=Dk43uw8PrE8
https://www.youtube.com/watch?v=FnHvIS192VU
https://www.youtube.com/watch?v=bQ76FCwKJ7g&t=39s
https://www.youtube.com/watch?v=xbovGBd1hDo
https://www.youtube.com/watch?v=D3mAj2Q--XY&t=2s
https://www.youtube.com/watch?v=hSQLn0aZK38
https://www.youtube.com/watch?v=_S2LCKoctjI
https://www.youtube.com/watch?v=UfhFfNMWopg&t=8s
https://www.youtube.com/watch?v=c6D-yOr4zQs
https://www.youtube.com/watch?v=P_YMUqoVjAE&t=47s

**Comment by KristinaVicario** [comment]
Sent Youtube Playlist link to Nancy, awaiting reply. 

https://www.youtube.com/playlist?list=PL5YpM4O2fgyqOXidQH_oeaswOqgjrABP9
