### ISSUE TITLE
thelooplab.org Partnership review

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1142]
Task: The founder of  The Loop Lab reched out to Reilly and wanted to know if there is opertunity to partner on projects. Do we see a use for thease skills?

Loop Lab mission statement
We are dedicated to empowering low-income underserved youth in careers in audio/video through job training.

**Comment by KristinaVicario** [comment]
Looks like a really cool program. 
Thoughts:
Would be interested in the type of equipment they have.
Would love to see some samples of their work on their site. 
Would they send people out in the field with us, or are they talking about in-studio videography only?
What have other collaborations looked like for them? How did they work with other companies in the past?
