### ISSUE TITLE
New photos of website on mobile

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#1147]
Would be great to get new photos of boston.gov as it's shown on mobile. 

Example found here: https://www.boston.gov/departments/digital-team/digital-team-roadmap#highlights

**Comment by sebastianebarb** [comment]
@here Bash Week Item

**Comment by GuruAmar9** [comment]
Added to Google Photos folder: https://goo.gl/photos/q7sTogmeNhBSi5GR7
