### ISSUE TITLE
SPARK Boston social graphic 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#1195]
Contact: Amy Mahler

SPARK applications are opening soon! I'd love to get a small set of social media materials promoting the launch of applications (similar to MYC if possible). I'd also love to them pushed out on the external digital billboards in the city too :) 
-Our application link is http://bit.ly/sparkapp19
-Applications Open Monday, May 6th and close Monday, June 16
Attaches is last year's flyer.
Happy to share you on a photo folder of SPARK photos!
Here's the currently being drafted press release for further info & inspo: 
https://docs.google.com/document/d/1xpZl0OZX3LsdDe1JNTwAGeG9DIPoEvvMx7FqiA_wzdA/edit

**Comment by carolinestj** [comment]
Old graphic: ![2018-2019 Apps Open Flyer-white (1).png](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/16616183-3765-4c76-aba6-50cac5447b74)

**Comment by sebastianebarb** [comment]
![APPLICATIONS FOR 2019-2020 SPARK BOSTON COUNCIL](https://user-images.githubusercontent.com/20642299/56915373-55d8a700-6a84-11e9-91cf-c35b4bbe40d8.png)
