### ISSUE TITLE
Access Boston icons Round 3

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1197]
Contact: Gretchen Grozier
Due: open

Task:
We are starting preliminary work with some more applications to integrate them with the Access Boston Portal - so I figured I'd put in requests for their new icons early..

[ ] - Kronos/Telestaff [time management for BFD]
[ ] - Sceris [doc management,]
[ ] - Asset Essentials' It will be used for Building Maintenance Requests (at City Hall)...
[ ] - Lagan/CityWorker [should be in by mid-June]
[ ] - AgilePoint [new forms tool]
[ ] - Riskmaster [new Worker's Comp tool]

**Comment by sebastianebarb** [comment]
attached are the draft flyers and the descriptions:
Draft of Sign to be Posted in DTX – Note: This needs the following language added: No Amplification without Permit
As far as dimensions, something similar to a no parking sign would probably be a good size.
Editable version (Word) of Brochure/Pamphlet – they added a link to the City website for further information on noise.

**Comment by sebastianebarb** [comment]
Lagan/CityWorker  [should be in by mid-June]

AgilePoint [new forms tool that Bryan C is implementing, Julyish?]

Riskmaster [new Worker's Comp tool - September timeframe]

**Comment by carolinestj** [comment]
![ABP Apps.JPG](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/c5d9401b-f807-46f0-9839-acff00202a0a)

**Comment by carolinestj** [comment]
Folder where all the icons are https://drive.google.com/drive/folders/1j4RV6uBZ3mkHGotxEoGcRTGxt5byqpjQ
