### ISSUE TITLE
Roxbury Dig - 4 videos total

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1201]
Joe Bagley's dig in Roxbury with artifacts and outside an old church. Collecting b-roll and interviews for a Boston Uncovered.

**Comment by GuruAmar9** [comment]
All four videos from the shoot are uploaded in Google Drive, sent to Joe Bagley and waiting for his approval before posting tomorrow (7/18)

Videos:
- Intro/Overview of Roxbury Dig
- Finding Dead Bodies (Or Not)
- Artifacts Found
- How to Dig a Hole For Science
