### ISSUE TITLE
U-PreK

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/design-team-workflow#1236]
Digital/print graphics for end of summer ad campaign (similar to 311) requested from LO. Still awaiting sign-up link, but visuals can be drafted anytime. NYC inspiration attached! [15724.jpeg](https://images.zenhubusercontent.com/5a25607b8a75884b9089c73c/ff221971-f8bf-4f74-87ef-613b1b8880ba)

**Comment by KristinaVicario** [comment]
@sebastianebarb Sebastian are GuruAmar and I supposed to be on this ticket? I know I did a U-PreK video last year.

**Comment by sebastianebarb** [comment]
@KristinaVicario no this is for print only at this point
