### ISSUE TITLE
Video series: A Changing City

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/design-team-workflow#1239]
Minimum of 5 larger storytelling pieces on how the City is changing this year in the realms of: 

* Transportation (to combat traffic congestion and safety)
* Climate Change
* Housing (affordable housing, tenants rights) 
* Public Safety 
* Economic mobility/opportunity

**Comment by sebastianebarb** [comment]
parent of #311

**Comment by KristinaVicario** [comment]
Thinking we don't need an epic ticket for this since this will just be an ongoing series for the rest of time right? So technically, we will never be "done" just ongoing?
