### ISSUE TITLE
A Changing City: Affordable Housing

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/design-team-workflow#1240]
One of five areas where a larger storytelling piece is needed this year. 
-- What is the City doing to address affordable housing? 
-- What are DND's 2030 goals and what are they doing incrementally to get there, now? 
-- What will it take for Boston to be known as a leading City for these efforts? 

Partners: 
Alex Sturke - DND Comms Director  

Existing b-roll likely can help here, but two initial action items:
1) Meeting with Partners to storyboard
2) Identify key footage to get, events to look out for
3) Identify timeline for launch

**Comment by KristinaVicario** [comment]
Waiting on Press to pass on their feedback. So far, center text is preferred.

**Comment by KristinaVicario** [comment]
Would need a complete overhaul and major updates, but was previously done and ready to go.
