### ISSUE TITLE
ISD video: Inspector and Repairs 

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1251]
Lisa Timberlake wanted a video of an inspector walking viewers through the building and telling people what sorts of things renters and home buyers should be on the lookout for. We were thinking about having the setting be a very old and historic building and tie this into a Boston Uncovered.

**Comment by KristinaVicario** [comment]
We collected the footage for this.

**Comment by GuruAmar9** [comment]
Waiting for edits from Department. Google Drive link: https://drive.google.com/open?id=1E6VIBKaSsM1hFABVFpXvRVmVxpnizt48
