### ISSUE TITLE
Copyright Free Song Online Membership Options

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1271]
Laying out options for music licensing website options. All about $20/month or less. 

Envato/Audiojungle    ($16.50/month, $198 total annual)
 - unlimited downloads
 - simple commercial license
 - one use only (re-license for each project as needed)
 - no broadcast use
 - access to graphic templates, stock photos & video, plug-ins, sound effects

Soundstripe    
- Standard ($11.25/mo, $135 billed annually; $15/mo, billed monthly, $180 total annual)
  - unlimited music
  - curated playlists on demand
  - license covers *any* use, commercial or broadcast

 - Premium ($21/mo, billed annually, $252 total annual) 
   - unlimited music & curated playlists on demand
   - sound effects
   - songs with stems (individual instrument and sound tracks)
   - license covers *any* use, commercial or broadcast

**Comment by sebastianebarb** [comment]
@jfalvey Where are we with this?

**Comment by KristinaVicario** [comment]
Not an option at this point.
