### ISSUE TITLE
Boston Uncovered - Chinatown Dig

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1285]
Boston Uncovered - Joe Bagley dig in Chinatown

Some footage captured, nothing really found yet though, might need a second visit next week once they dig down further (they're 4 feet down now, and only in the 1990s, which is unusual). They're probably going to have to dig out the entire back half of the lot, to go past 4 feet.

Also we put a GoPro on Joe, and it looks great:

![Chinatown Dig - Joe-1.jpg](https://images.zenhubusercontent.com/5d2399be1799422cc7d89f78/5f068f2c-5a2b-458f-ae13-08064c63aabd)

**Comment by GuruAmar9** [comment]
Just send out and published a fun teaser for this dig, that Joe approved (yay emojis)

Another potential four additional videos:
- intro/overview of dig [already edited together, 1:57 length]
- the science of trash (artifacts found so far) [already edited together, 1:15 length]
- this is a dream dig location for Joe
- the future of archaeology (it's complicated)

**Comment by sebastianebarb** [comment]
@KristinaVicario @GuruAmar9 can we close this ticket?

**Comment by GuruAmar9** [comment]
I was originally hoping for a follow-up after they realized they had to close the dig... but I don't think that's happening because it seems like they closed it up a long time ago.
So, long story short, yes I think this can be closed!
