### ISSUE TITLE
Organize Marathon Footage 

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1290]
Organize Footage into buckets that make sense so that when it's time to edit, the process will be much easier.

Connect w/ Nora and Steve for help organizing and labeling previously shot items.

**Comment by sebastianebarb** [comment]
@KristinaVicario @GuruAmar9 can we close this ticket?

**Comment by sebastianebarb** [comment]
@KristinaVicario @GuruAmar9 can we close this ticket?
