### ISSUE TITLE
Recycling Video - Students Composting

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1292]
Susan Cascino is contact

Pilot program in three schools with students learning how and why to compost.

**Comment by GuruAmar9** [comment]
Sat down with Susan Cascino and Laura Alves, the zero waste coordinator, in January. She is working with Katherine Walsh from BPS to pilot composting in 3 schools in the spring.

Also talking with Chris Coakley about a recycling video with BPS students as part of a big recycling campaign that Public Works is putting together.
