### ISSUE TITLE
Melnea Project Video 

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1296]
Replacing trees much to the disapproval of the community. The trees are currently dead and need to be replaced, but the shade canopy it provides will be removed and not replaced for 10-20 years. Need to shed good light on the project and why it is important to replace the trees in the longrun. 

Talk to a community advocate and someone respected in the community. 

Talk to the lead botonist (Mossman?) on the project. 

We met with Sam Chambers to discuss and he connected us to the respected people.

**Comment by GuruAmar9** [comment]
Haven't had confirmation from everybody involved (especially Sam), but most likely going to close this, since it seems like a video isn't needed
