### ISSUE TITLE
Boston Uncovered-Archives Edition

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1298]
Went out and shot 7/23, editing into a couple short Boston Uncovered videos.

**Comment by GuruAmar9** [comment]
We covered a lot while we were there. Videos will be:

- Looking through an election scrapbook from 1890 (includes: hand counted votes, example ballot, a very amusing notice banning smoking and drinking while voting, etc.)
- instructions for voting women, women voting records (includes interesting record of woman journalist from 1890), record of men voting against suffrage and breakdown of that vote by neighborhood
- Boston transit maps from 1930 (it looks very different)
- 1960 Boston comic book for tourists (freedom trail, etc)
- emergency preparedness in WW2 vs now (gas masks and instructions on how to identify chemical gas, in case of an attack)

Lots of good stuff!
