### ISSUE TITLE
In Your Shoes: Immigrant Advancement

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1299]
Subject is Dheandra Jack. She attended Citizenship Day 2018, sworn in April 2019, lives in Hyde Park, from Trinidad. Contact info: dheandra.n.jack@gmail.com, (617) 291-7321

Starting to coordinate everything with her now.

**Comment by KristinaVicario** [comment]
@GuruAmar9 will ping Carol about this

**Comment by Neslihan-Sahinkaya** [comment]
Talked to Carol, she will brainstorm with her team and send possible candidates for this project.

**Comment by Neslihan-Sahinkaya** [comment]
Interviewed Cassie R. an immigration lawyer who gives free consultations through MOIA. (1/12/22
This video will be highlighting her, and the work that she does. The goal that we have for this video is, to bring awareness to this service that MOIA offers, and to get more volunteer lawyers involved.
