### ISSUE TITLE
Access Boston: Group Management

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#1306]
Help create design for group management in Access Boston.

Requirements here: https://docs.google.com/document/d/1tZg4YMucj5OJ-TWzJ-OYkorq8nzTpHkyYl6HKKd3wvo/edit

**Comment by sebastianebarb** [comment]
[1306_Access Boston- Group Management.pdf](https://github.com/CityOfBoston/creative-team-workflow/files/3477564/1306_Access.Boston-.Group.Management.pdf)
@reillyzlab take a look

**Comment by reillyzlab** [comment]
Feedback:

1. Begin with different entry screen so they can select between two icons -- 1 of person management, 1 of group management
2. Build in a way to go back to beginning
3. Add a 'header/subheader' for the functionality - i.e. this is managing groups
4. On 'current groups', replace 'add back' with an empty check box
5. Allow a way to view all group members by clicking on the group name
6. Allow a way to click on the person name and view all of the groups that they are in

Please create a full flow for the add/edit person and another for add/edit group

**Comment by reillyzlab** [comment]
@phillipbentonkelly to put in examples of group name lengths

**Comment by phillipbentonkelly** [comment]
Sample Group Names:
- BTDT_SignShop_WorkordersfromDisability_Installation
- BTDT_PavementMarking_WorkordersfromEngineering
- INFO02_SelfServiceGenericeFormforOtherServiceReque
- PWDx_StreetLight_Pending_Contractor(Internal)

**Comment by sebastianebarb** [comment]
[1306_Access Boston- Group Management.pdf](https://github.com/CityOfBoston/creative-team-workflow/files/3517273/1306_Access.Boston-.Group.Management.pdf)
![Screen Shot 2019-08-19 at 3 01 20 PM](https://user-images.githubusercontent.com/20642299/63291803-4af38d80-c292-11e9-8060-86198733957e.png)
