### ISSUE TITLE
2020 Census Poster re-design

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1336]

**Comment by sebastianebarb** [comment]
The Elections Department thought it would be a great idea to have census posters (2 by 2 ft) up at 255 locations for election day come September and November. The drop-dead deadline they have given me is September 17.

I have attached a basic template I thought we could work with and rebrand as the city's.

I think the "Coming Soon!" portion should be changed to read "Coming Next Spring" and then have the Federal logo attached.

As for the remaining content:

WHO? Everyone! Regardless of immigration status, housing security, age, race, gender, or
ability, you count equally in our democracy.

WHAT? Be counted and be visible by filling out your Census form.

WHERE? Each neighborhood of Boston and everywhere in the U.S.

WHEN? This once in a decade opportunity to define your community will take place March-July of 2020 

HOW? Online, phone, or mail

WHY?  Participating in the Census ensures your community receives federal funding for services like healthcare, affordable housing, public education, childcare, and public transportation. The Census also impacts political representation.

We could end the poster by having the following text -
"Boston depends on everyone to participate and be counted so that the Census accurately reflects the diverse populations that call our city home."

Then have the bottom right corner read -
For more information visit
boston.gov/2020-census or contact:
Sebastian.Zapata@boston.gov, 617-635-4478

Bottom left would be the City's B icon or seal.

Let me know what you think!

**Comment by sebastianebarb** [comment]
[Census-Coming-Soon-poster-legal.pdf](https://github.com/CityOfBoston/creative-team-workflow/files/3574563/Census-Coming-Soon-poster-legal.pdf)

**Comment by carolinestj** [comment]
WHY?  For every person who is not counted in the Census, Massachusetts loses out on approximately $2,400 in federal funding for services like healthcare, affordable housing, public education, childcare, and transportation. The Census also impacts political representation.

WHO? Everyone! Regardless of immigration status, housing security, age, race, gender, or
ability, you count equally in our democracy.

WHEN? March-July of 2020. 

HOW? Online, phone, or mail. 

We need to also fit in the US Census logo somewhere on the poster as well. Here are the branding guidelines the census created that might help with selecting an appropriate size and color scheme for the poster. https://www2.census.gov/programs-surveys/decennial/2020/resources/promotional-print-materials/2020-census-brand-guidelines.pdf
