### ISSUE TITLE
 Boston Marathon Memorial Video & Teaser

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1338]
A two-minute piece for social 
A 5-minute piece as a short-form doc for boston.gov/YouTube.
Create a blog-post to house video

**Comment by GuruAmar9** [comment]
Now thinking about getting multilingual captions for this, especially for Lingzi's family from China. Probably Spanish as well. Just requested an estimate from Manar on the cost, waiting to see what she says.

**Comment by GuruAmar9** [comment]
Donny has heard back from almost all the families, just waiting on the Richards now, but very good feedback from everybody else so far! 

Planning out the release info/text now as well.
