### ISSUE TITLE
Employment and Resource Fair

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#1345]
Contact: Kevin Sibley 

Event: Employment and Resource Fair
Sponsored by: The Mayor's Office of Returning Citizens, The Suffolk County Sheriff's Department, The Office of the District Attorney Rachael Rollins and Mass Hire Boston 

Date: Thursday, October 24, 2019
Time: 10:00am to 2:00pm
Location The Salvation Army Ray and Joan Kroc Corps Community Center
650 Dudley Street 
Boston, MA 02125

For more information, please call 617-635-5333 or 617-704-6601

https://www.canva.com/design/DADlMh1pCx8/share/preview?token=SMkjH3TZ7pwk22tyZGmAdA&role=EDITOR&utm_content=DADlMh1pCx8&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

https://www.canva.com/design/DADlMcQQjcg/share/preview?token=9A1ff_qbW3lns5Wj1_GDOw&role=EDITOR&utm_content=DADlMcQQjcg&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by carolinestj** [comment]
want the design to be more community relatable like this flyer ![project immigrant.jpg](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/2e30c010-3676-4665-aaa0-b22fe1700a30)

**Comment by sebastianebarb** [comment]
[Returning Citizens job fair flyer  (1).pdf](https://github.com/CityOfBoston/creative-team-workflow/files/3658496/Returning.Citizens.job.fair.flyer.1.pdf)
- no diversity
- Returning Citizens to get photos

**Comment by sebastianebarb** [comment]
[Returning Citizens job fair flyer .pdf](https://github.com/CityOfBoston/creative-team-workflow/files/3658499/Returning.Citizens.job.fair.flyer.pdf)
- Returning Citizens could not get photos
