### ISSUE TITLE
fix it flyer 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#1366]
Contact: Victoria Phillips 

For the Fix-it Clinics, attached is the current flyer. The flyer file just needs to be editable for the location, date, and time as well as the list of things which can be fixed.

The most essential permanent information for all posters is the disclaimer about no oversized items, engines, or firearms and space for a contact person (which is tbd).

[https://app.zenhub.com/files/66664846/d53f1486-d22c-4489-a53b-471bb88edcf1/download](https://app.zenhub.com/files/66664846/d53f1486-d22c-4489-a53b-471bb88edcf1/download)

**Comment by sebastianebarb** [comment]
@carolinestj can we check in on this?

**Comment by sebastianebarb** [comment]
https://www.canva.com/design/DADn0mVV9ZA/share/preview?token=tS9N5U-J0-ABOL2W6cs8sw&role=EDITOR&utm_content=DADn0mVV9ZA&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by sebastianebarb** [comment]
This looks much better than the original, I am thinking if we can add a few icons of objects just to give some greater visual appeal, that would be great.
