### ISSUE TITLE
Access Boston Logo: Tableau

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#1371]
Icon request for Access Boston:

Application icon for: Tableau 

Purpose: Tableau is an app that does data reporting - it's providing the dashboards the Mayor/311 use.  

Timeline/relevant deadlines (i.e. when should this be live on production - date and time): 

Name/verbiage that should go with the icon (may match application name, or might not):

Who should see the icon/security group name:

**Comment by gretchen-grozier** [comment]
Timeline/relevant deadlines (i.e. when should this be live on production - date and time): October 3

Name/verbiage that should go with the icon (may match application name, or might not): Tableau

Who should see the icon/security group name:  SG_AB_TABLEAU

**Comment by sebastianebarb** [comment]
![Tableau-290](https://user-images.githubusercontent.com/20642299/66319568-52770080-e8eb-11e9-8a60-9f95e7709c4f.png)
@gretchen-grozier

**Comment by gretchen-grozier** [comment]
@sebastianebarb I sent over to the Data team to check it out.  Our process says we let the app owners have the final say....thanks!

**Comment by gretchen-grozier** [comment]
Okay, I put all 4 icons that Sebastian has done in a google drive folder for Data team to look at.  I'm recommending they use this one for Analyze Boston actually. Then they have options to choose from for Tableau too.
