### ISSUE TITLE
Death Certificate Wireframe Design

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/design-team-workflow#140]
[DeathCertificateWireframe.pdf](https://github.com/CityOfBoston/design-team-workflow/files/694150/DeathCertificateWireframe.pdf)

**Comment by joshuagee** [comment]
@carolinestj Can you make the changes from our meeting by Monday/Tuesday?

**Comment by joshuagee** [comment]
@carolinestj @sebastianebarb The next step I am looking for is for mockups that "work" in https://www.invisionapp.com/ (sent you both invites). Not sure where my job begins and yours ends here, but this is a lightweight mockup program that syncs with creative suite. @reillyzlab mentioned it. 

My goal is to take an mobile version downstairs on my phone to run some tests with people waiting on line to buy certificates.

**Comment by joshuagee** [comment]
@carolinestj Can you also load a mobile screen of an empty cart into Invision? 

Also, can you drop the updated proofs into this chain? I'd like to share them with Patty.

**Comment by carolinestj** [comment]
@joshuagee 
[death6.pdf](https://github.com/CityOfBoston/design-team-workflow/files/855518/death6.pdf)
