### ISSUE TITLE
Photos - traffic congestion 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#1404]
We got a new request to take some photos of traffic jams/congestion 

some good locations:
- congress/state street at 9 a.m. or 5 p.m.
- Atlantic ave in front of south station specifically 9 a.m. or 5 p.m. but anytime is pretty bad 
- Mass ave between Harvard bridge and mass ave T stop

**Comment by GuruAmar9** [comment]
Also, a couple video clips of traffic would be great for when we get around to the traffic and transportation part of the Changing City series we're trying to do on the big policy initiatives from the Mayor. If possible!

**Comment by sebastianebarb** [comment]
@GuruAmar9 did we ever get these photos? If not let's do this ASAP!

**Comment by Neslihan-Sahinkaya** [comment]
https://drive.google.com/drive/folders/1s-5kcWWkhSlhx4p35HJ6-uL3VMiCVXSd?usp=sharing

Didn't take videos but can get that one done when I get back from my trip!
