### ISSUE TITLE
In Your Shoes - Mass Cass Recovery Centers

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1415]
In Your Shoes video that potentially features someone who has benefitted from coordinated recovery resources, potentially through the STEP pilot program which closes gaps in access to care. While this person will have received services prior to the launch of Mass/Cass 2.0, it demonstrates how important coordination/continuum of care is, and allows us to point to Mass/Cass 2.0 as a continuation./expansion of that kind of approach.

**Comment by KristinaVicario** [comment]
Followed up on this via email.

**Comment by GuruAmar9** [comment]
Filmed Mario Chaparro, program manager for Boston Public Health Commitment Engagement Center, on 2/20. Waiting to edit now.
