### ISSUE TITLE
Request for new icon: Boston.gov (content editors)

### ISSUE THREAD

**Issue by gretchen-grozier** [CityOfBoston/design-team-workflow#1423]
We are going to populate an icon onto the ABP for users who have the ability to edit Boston.gov (~160 end users).   We'll need to do this somewhat quickly - but I'm hoping you have a lot of icons that will work here.   I will be asking James for user list week of 12/2

This icon is instead of sending them to a link (also the UX is same as all the other apps).

**Comment by sebastianebarb** [comment]
![1_Boston dot gov editor](https://user-images.githubusercontent.com/20642299/69992192-2789e100-1517-11ea-925a-1ad2c0818673.png)

**Comment by gretchen-grozier** [comment]
Sent to James and Jeanethe to review.  James okay'ed it so we will move forward!
