### ISSUE TITLE
Request for new icon: Genetec

### ISSUE THREAD

**Issue by gretchen-grozier** [CityOfBoston/design-team-workflow#1424]
We have started working to integrate the Genetec (video cameras) into central IAM systems.  We want to put it behind MFA and better manage the user base/access.  

Timeline is probably March (no rush) - they are doing an upgrade.

**Comment by sebastianebarb** [comment]
![1_Security camera](https://user-images.githubusercontent.com/20642299/69992167-180a9800-1517-11ea-9ccd-3447f6123c7c.png)

**Comment by gretchen-grozier** [comment]
Sent icon to Linda and Dan for review.  Once the tool gets close to going live, I'll circle back if I don't hear from them.
