### ISSUE TITLE
City as a Classroom Ep #3 - TechBoston at Harvard

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1426]
TechBoston teacher, Casey Andrews, reached out to the Radcliffe Institute to explore the Angela Davis: Freed by the People exhibition as part of a new course where 11th and 12th grade students are co-designing their class curriculum and are focusing on activism and structural change. The museum reached out to us after seeing the storytelling post on Twitter, asking if we wanted to join for the Dec 3rd visit.  Potentially interviewing up to 5 students and a couple of the organizers.

**Comment by KristinaVicario** [comment]
GuruAmar collected footage for this.

**Comment by GuruAmar9** [comment]
Export and caption files here: https://drive.google.com/drive/folders/1RFc9yobOTPkvMjPcLmxUDCifWJqZn0Lw?usp=sharing
