### ISSUE TITLE
Boston Uncovered - North End Dig

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1430]
Digging in a small backyard in the North End before the owner builds out the house into it. Some serious 17th and 18th century deposits, more to be confirmed.

Initial visit on 12/4: So many good little stories already. Joe says they've found more artifacts on the first day digging there than on every other dig this year combined.

Follow-up required during the week of 12/9-1/13

**Comment by KristinaVicario** [comment]
GuruAmar has collected some footage so far.

**Comment by GuruAmar9** [comment]
Intro Video - https://www.youtube.com/watch?v=SSP3OyQuRyM
Artifacts Video - https://www.youtube.com/watch?v=x0uZg_DfsG8&t=1s

more TBD

**Comment by GuruAmar9** [comment]
Completed two more little videos, on more specific tidbits from that dig. One on the "necessary" (the privy), and backyards in general then, and the other is on a couple artifacts from the house that are already in museums. Sent to Joe for approval. Could space these out for Thursday posts over a few weeks. Captions are still needed: 

https://drive.google.com/drive/folders/1Lj9KDsBPTdFseSyYpVe07a-r2JMdUBIQ?usp=sharing

**Comment by KristinaVicario** [comment]
We need to get Joe's approval but these would be good to release in the late fall/early winter time

**Comment by KristinaVicario** [comment]
I think these videos are dead in the water without Guramar's account so I'm just going to close this.
