### ISSUE TITLE
Thank you & Happy New Year cards from Digital Team

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/design-team-workflow#1436]
Two separate card files that I'll print off at Staples. Size-wise could be a postcard (nice to display) so long as its a size that comes with a standard envelope. If that's not easy, a regular foldover card works. 

1. Thank you from the City of Boston Digital Team 
* Can be simple, but some icons/graphics that represent our work or a B I'm open to ideas. 

2. Happy New Year from the City of Boston Digital Team
* More celebratory in design/icons maybe one of Caroline's patterns with icons of fireworks, computers, etc :). 

Will send to vendors, partners (like GA), staff in other Depts. 

Thanks!

**Comment by sebastianebarb** [comment]
[Ty&HNYcard#1436.pdf](https://github.com/CityOfBoston/creative-team-workflow/files/3996018/Ty.HNYcard.1436.pdf)
