### ISSUE TITLE
Comp request: Department page list view

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/design-team-workflow#148]
As a website viewer, it is difficult to find a specific department on boston.gov/departments because the departments are all in "card" format. 

What would a "list view" of those departments look like? (alphabetical order only - no filters or sorting needed)

What would the toggle between "card view" and "list view" look like? (iconography, buttons, placement on the page, etc.)

Low-fidelity comp requested for initial discussion purposes and user testing. 

Requested due date: Monday January 30. Let me know (in-person or here) whether that works or if you need more info.

**Comment by reillyzlab** [comment]
@sebastianebarb re-opening b/c it would be great to also see a version that's even more list like - i.e. one a top another rather than broken into two columns

**Comment by sebastianebarb** [comment]
![departments list v2](https://user-images.githubusercontent.com/20642299/31091936-b55dca30-a77a-11e7-98d0-5a405a94d472.png)
@reillyzlab let me know if you were thinking of something different.
