### ISSUE TITLE
Find solution to better label and organize stock photos

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1487]
Trying find a way to better organize and tag photos from all of us in the digital team, for better access and sharing, and for future users. 

Is it Flickr...? Is it by photographer name in Google? Do we make separate folders within Google...? To be determined!

Google Photos folder: https://goo.gl/photos/q7sTogmeNhBSi5GR7

**Comment by GuruAmar9** [comment]
Google Doc on how to get full search access to our stock photos: https://docs.google.com/document/d/1wQzxOTuf2-wX-KdC31d2kjQI-WQ-1w7ajx0bxZ7LJKY/edit?usp=sharing

Most importantly for organizing photos in Google Photos, be descriptive when naming your photos. Don't just let it be C0003 or whatever the original file name is. While Google Photos is really good at reading what's in the photos, it's extra helpful if you add more info in the file name itself. List out neighborhood, park name, season (if it's anything besides summer), holiday, etc. For example: 

210423_Fort Hill Highland Park Roxbury spring-1
210211_Garvey Park Dorchester Snow-15
210311_Roslindale Village small biz photos-7
Jamaica Plain JP park spring pond-23.jpg

And label your folders sequentially, it should always be biggest to smallest: YYMMDD (year-month-day).

You can also add locations to each photo in Google Photos, and batch edit that. Go by neighborhood if possible, or get more specific, like the Public Garden.

**Comment by GuruAmar9** [comment]
Google Doc with the above best practices info: https://docs.google.com/document/d/101t1fIHDT1Ch8YVHbn70n8tDf_BBRmGWSAQSxv20jbY/edit?usp=sharing

**Comment by carolinestj** [comment]
Google drive folder 
https://drive.google.com/drive/folders/1g0Oe-V60JctB1lYu2srt0dkqN2_xYLbq
