### ISSUE TITLE
Font-scaling request - H1 (titles)

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/design-team-workflow#149]
Sometimes the fonts are just too big. That's ok! How should we scale them down?
![screen shot 2017-01-12 at 9 04 36 pm](https://cloud.githubusercontent.com/assets/3886936/21915897/bf182ee2-d90a-11e6-8a96-d65f26f610ec.png)

Should I be requesting this from you @sebastianebarb or @matthewcrist? Please comment and @ mention me below.

My goals is to have a definition for how the H1 (at least) scales down to accommodate column widths on Boston.gov.

Most obvious use case is for the 2/3 wide column on department pages. [Intergovernmental Relations example](https://www.boston.gov/departments/intergovernmental-relations).

[Example 1](https://www.boston.gov/economic-development/energy-efficiency-and-sustainability) and [example 2](https://www.boston.gov/parks-and-playgrounds) of how the font scales already. (decrease the size of the window) We may just need a font size in-between the level at ~960px and wider. 

Requested due date: Monday January 30. Let me know (here or in-person) whether that works.

**Comment by sebastianebarb** [comment]
@reillyzlab can we close this?
