### ISSUE TITLE
Definition request: which links should NOT be underlined

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/design-team-workflow#151]
As a website user with accessibility needs, I want hyperlinks to be underlined. 

Ok. But we're not going to do that for buttons, for example. What are other things we will not underline?

There may be a list of css classes that we could go through to be sure to catch all potential links. @matthewcrist any class naming convention we could use for searching for all links in the stylesheet?

Top Navigation
Hamburger menu
Breadcrumbs
Copy in the body of an article page
Sidebar copy
Downloadable resources (like in the bottom of the right sidebar on [this page](https://www.boston.gov/public-notices/13101))
Email address links (same page as above, sidebar)
Status bar items (should they _begin_ with underlines rather than having underlines on mouseover?)
FYI component CTAs
311 component links
[/News](https://www.boston.gov/news) cards
[/events](https://www.boston.gov/events) list links
[/events](https://www.boston.gov/events) big italicized Lora text at the top
Components currently with hover over state changes (usually white to optimistic blue)? Includes Transactions Grid, Upcoming Events, News & Announcements, Guides (colored changes to translucent photo), Transactions (big list on [Pay and Apply](https://www.boston.gov/pay-and-apply)), [Programs and Initiative cards](https://www.boston.gov/programs-initiatives)... others definitely.

Requested due by: Wednesday January 18, especially if Hondo shares a css convention we use.

**Comment by sebastianebarb** [comment]
@reillyzlab do we still need this open?

**Comment by reillyzlab** [comment]
No, closing
