### ISSUE TITLE
Boston Uncovered - BPL/Boston Research Center Digitizing Photos

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1520]
Point of Contact: Renee Barouxis
Just wanted to pass along an idea for the Boston Uncovered video series! The BPL and the Boston Research Center were just awarded a $650,00 grant from the Andrew W. Mellon Foundation to gather letters, photographs, and other historical materials from Boston homes and digitize them, so they're available to everyone. As you can imagine, there are some historical materials that exist only in people's homes, so it's a really cool project. Read more about it in the Boston Globe [here](https://www.bostonglobe.com/metro/2019/09/29/boston-research-center-embarks-archival-mission/tPD41PvYEUs7QETO6q47nJ/story.html)

Coming up: In the coming months, the center plans to hold informal forums at library branches to show what it has already gathered on the city’s neighborhoods. Residents will be asked to bring letters, photographs, and other historical materials that might fill in the gaps. With the new grant, we hope to hire a coordinator at the Boston Public Library to set up community meetings, gather these important materials, and make them digitally available to the public. 

Possible interviewees:
BPL Manager of Content Discovery Tom Blake
TBD coordinator for this project at the Boston Public Library
Karilyn Crockett, a lecturer of public policy and urban planning at the Massachusetts Institute of Technology, who was quoted in the article and fun fact used to work in Economic Development
Dan Cohen, the vice provost for information collaboration, dean of libraries, and professor of history at Northeastern
Bostonians bringing in their historical materials

**Comment by Neslihan-Sahinkaya** [comment]
https://bostondoit.atlassian.net/browse/DIG-643
