### ISSUE TITLE
Emergency kit gif 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#1536]
**Contact:** Kyron Owens 

**Task:** Take the kit graphic and make a moving animation out of with things being thrown into it. 
canned food 
baby bottles 
flashlight 

**original file:**
https://drive.google.com/open?id=0B0RwQU94BhGeSkNnWUE3aHpiRGM&authuser=sebastian.ebarb@boston.gov&usp=drive_fs

**Comment by brandoncolecreative** [comment]
![Emergency-Kit_1536](https://user-images.githubusercontent.com/62507887/81993606-0ecc3e00-9614-11ea-8aa0-b52b9496375e.gif)

@sebastianebarb

**Comment by sebastianebarb** [comment]
@brandoncolecreative great job so far, two quick points. Can we make the background our optimistic blue? And can we extend the line of the floor under the kit so it goes across? After we can show this to Emergency Management and see if they want us to add a url.

**Comment by brandoncolecreative** [comment]
![Emergency-Kit_1536-OptB](https://user-images.githubusercontent.com/62507887/82263927-ee60f400-9931-11ea-9de8-e5a3f824f5f4.gif)

**Comment by brandoncolecreative** [comment]
@sebastianebarb

**Comment by sebastianebarb** [comment]
This looks good, I will send it to the client and see what they have to say @brandoncolecreative

**Comment by sebastianebarb** [comment]
hey @brandoncolecreative 
we got a note from the client "Thank you for sending this over, I was wondering if we can replace one of the food cans with either something that replicates either important documents or a first aid kit?" 

If you can work on this great, but totally understand if you cant. 

No timeline.
