### ISSUE TITLE
Employee Giving (United Way) icon for Access Boston

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/design-team-workflow#1537]
In time for One Boston Day this year (April 15), A&F is looking to launch a connection to the United Way giving platform through Access Boston. A&F is replacing CoBEC with this. It will enable options for employees to volunteer or donate to the national network of 501c3 non-profits. 

They need an icon created that will symbolize this functionality.

**Comment by sebastianebarb** [comment]
![all icons2_United Way Philanthropy Cloud](https://user-images.githubusercontent.com/20642299/79131094-07481980-7d76-11ea-9351-5c4bc2329409.png)

**Comment by sebastianebarb** [comment]
@phillipbentonkelly I was asked to send this over to you.

**Comment by andreeaursu1981** [comment]
Security Group: cn=SG_AB_UNITEDWAY
https://sso-test.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Fwww.philanthropycloud.com
Tile: on this git see up.

**Comment by andreeaursu1981** [comment]
Title: Boston Gives Back

**Comment by andreeaursu1981** [comment]
Prod URL: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Fwww.philanthropycloud.com
Security Group: cn=SG_AB_UNITEDWAY
Title: Boston Gives Back
Tile: on this git

**Comment by phillipbentonkelly** [comment]
Ok.
