### ISSUE TITLE
New Eliot School: Student Tour

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1539]
6 students give us a tour around their newly refinished Eliot Innovation School. Filmed with Kris Carter. Awaiting edit.

**Comment by GuruAmar9** [comment]
Kris is planning on editing, timing TBD. Massive amount of footage to go through though.

**Comment by KristinaVicario** [comment]
Kris is taking the edit on this one so I think we can close?

**Comment by GuruAmar9** [comment]
Yeah, he is, so we can probably close!

[image: COB_B_Blue_square-01.png]

GuruAmar Khalsa (pronounced: grr-*aah*-mer) (pronouns she/her)

Digital Storyteller/Videographer, Digital Team

Department of Innovation and Technology

954-242-1444 (c)
