### ISSUE TITLE
Metrolist Mobil interface update 

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1544]
Owner: Susanna Ronalds-Hannon (Talk to Andre first)

Task:
The current file: https://drive.google.com/file/d/1Dsl4bBfU4agvk3Y2Zc4T1jgQRXi4oTPg/view?usp=sharing

(Fair warning: There is still a Drupal page contingent on content being created back/forth with layout, and some other written content still being drafted, marked up etc. There is some clipboard/component things happening surrounding that artboard.)

(Also, it's overdue for a cleanup/org of the symbols and groups which currently have no organization readable by anyone other than myself. I should be able to give this all a going over this week.)

You three *should* have invitations to the Invision. If there is any issue there LMK.

**Comment by reillyzlab** [comment]
PDF version of the above files: [Untitled.pdf](https://github.com/CityOfBoston/creative-team-workflow/files/4477565/Untitled.pdf)
