### ISSUE TITLE
Mayor Taping Edits from March - April 10 (17 total)

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1580]
Whenever press sends us over a Mayor's Taping, GuruAmar and I edit for sound, captions and color correction. 

A list of the one's we've done in the past month:

Mayor Walsh remarks on community resiliency: https://www.youtube.com/watch?v=DR-QYxsldO4&t=2s

Mayor Walsh on the budget overview: https://www.youtube.com/watch?v=HLjcFhPvDd0

Thank you grocery store workers, we see you: https://www.youtube.com/watch?v=YIE227N5ekI&t=3s

Mayor Walsh addresses small businesses: https://www.youtube.com/watch?v=UWmIde4SWDg&t=2s

Mayor Walsh on the importance of Fair Housing Month: https://www.youtube.com/watch?v=cOrX6-suSXE

Mayor Walsh reads How Do Dinosaurs Say Goodnight: https://www.youtube.com/watch?v=Zn7PjZXDBzM

Protecting Individuals Experiencing Homelessness: https://www.youtube.com/watch?v=9eh7vnL8vHA

Boston's FY2021 Recommended Budget (1 of 3 - Spending, Capital Plan and Revenue): 
https://www.youtube.com/watch?v=f1Xr_xVru6A
https://www.youtube.com/watch?v=pdQbbZCcTFY
https://www.youtube.com/watch?v=8KZxv5d7S8Q

BU video - not posted, for BU

BPS Athletics videos, 4 in total- not posted, for BPS 

Mayor Walsh thank you BPD: https://studio.youtube.com/video/dxdy2rAP1Is/edit

Mayor Walsh Message to City Employees: https://studio.youtube.com/video/RTmjfBDzwKI/edit

**Comment by GuruAmar9** [comment]
Adding in that there was also a video on the Mayor addressing city hall services and reducing some in-person services, but the situation was changing so quickly that it never got posted.
