### ISSUE TITLE
Access Boston Icon: Xybion

### ISSUE THREAD

**Issue by gmccarthy83** [CityOfBoston/design-team-workflow#1590]
Title = Worker Comp Invoicing
Name of the application = Xybion
Description = medical and other invoice processing for workers comp claims. It is closely related to the RiskMaster application (Worker Comp Claims) which you already designed an icon for.
Timeline = Week of May 11th

**Comment by sebastianebarb** [comment]
![all icons2_needs review  copy.svg](https://images.zenhubusercontent.com/582f674ab9dc3c6220223141/ed7a99cb-6fb2-458d-89d1-1605ec7fa1b6)
