### ISSUE TITLE
Access Boston : Phire 

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/design-team-workflow#1597]
@CityOfBoston/digital-team 
Name of the application: Phire
Description of what the app is (if it is not that obvious): internal HCM app
Timeline (when do you need to have live in Prod): May 6, 2020.

**Comment by sebastianebarb** [comment]
Hey @andreeaursu1981,

I know very little about Phire, can you give me a little more info.

**Comment by andreeaursu1981** [comment]
@sebastianebarb, in a nutshel this is \ Application Change Management for PeopleSoft.  I am attaching the whole documentation they gave me.
[Phire_Overview.pdf](https://github.com/CityOfBoston/creative-team-workflow/files/4553758/Phire_Overview.pdf)

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=1LVulkMFpdSl-WYYlpdcpCO4ZbdvsrZ-Q&authuser=sebastian.ebarb@boston.gov&usp=drive_fs

**Comment by andreeaursu1981** [comment]
Thanks so much. I will close this issue now. Looks great!
