### ISSUE TITLE
Mayor's Tapings 4/27-May 1

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1603]
Tapings for the week:

Ramadan 
Bottom Line 
City Year 
Harvard Remote Ceremony 
Thank you to Red Cross staff and volunteers 
Pine Street Inn “Stay Inn” campaign
Michael Botticelli retirement video
College Board message for BPS AP test takers

**Comment by GuruAmar9** [comment]
More tapings this week:
- MJW reads Goodnight Mouse
- Message on Duckling Day
- Message for NBC10 Virtual Commencement

**Comment by KristinaVicario** [comment]
https://www.youtube.com/watch?v=HPrbO632AU0&feature=youtu.be
