### ISSUE TITLE
Thank you B for  delivery workers.

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1615]
Contact: Sebastian

Task: Create an animated thank you B for delivery workers.

File: https://drive.google.com/open?id=1CWG-EysJRqfMt4XNT5By2jONUlghUGyr&authuser=sebastian.ebarb@boston.gov&usp=drive_fs

**Comment by brandoncolecreative** [comment]
@sebastianebarb 

![ThankYou_DeliveryB-1615](https://user-images.githubusercontent.com/62507887/81434241-dcae6e00-9133-11ea-9683-9e227ddb9850.gif)

**Comment by brandoncolecreative** [comment]
![ThankYou_DeliveryB-1615-Loop-2](https://user-images.githubusercontent.com/62507887/81443068-afb58780-9142-11ea-9dcf-0fa0784ed622.gif)

@sebastianebarb
