### ISSUE TITLE
Thank you B for nurses

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1617]
**Contact:** Sebastian Ebarb

**Task:** FYI -- Wednesday is National Nurses Day in case we want to work on a graphic.

Sounds like BPHC is going to try to make their own

**History:** 
Previous Bs-https://drive.google.com/open?id=0B0RwQU94BhGeUGhSRnA5aUxXbUE
and https://drive.google.com/open?id=1N6om0CPDw6hW3Lvu0irqZhM_JdTwO2ht

**Dr B-** https://drive.google.com/file/d/11MdP1AaJ3_FSpFjNTSgbBtuH14ln3Kwn/view?usp=sharing

**Comment by brandoncolecreative** [comment]
![ThankYou_Nurses_OptA-1617](https://user-images.githubusercontent.com/62507887/81081570-0fe8c700-8ec0-11ea-9bc0-dc8c87578aba.png)
![ThankYou_Nurses_OptB-1617](https://user-images.githubusercontent.com/62507887/81081573-10815d80-8ec0-11ea-9261-c60f8a99356d.png)

@sebastianebarb
