### ISSUE TITLE
Mayor Tapings 5/4-5/8

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1618]
Tufts University Commencement Message
Filippo Frattaroli 50th Anniversary
Catholic Charities Spring Celebration 
Roxbury Community College Class of 2020 Message

**Comment by GuruAmar9** [comment]
Tapings from 5.06:
- Teacher Appreciation Week (with captions)
- Saint John Paul Lower Mills School video for Teachers Appreciation Week
- Hospital Week Message for BIDMC
