### ISSUE TITLE
Email Template Header and Footer

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/design-team-workflow#162]
Need to create a master email template header and footer -- 600 px wide.

Probably requires some additional scoping from Upaknee.

**Comment by joshuagee** [comment]
Can you also provide a default city of Boston static image? We need a standard for system emails and if anything breaks.

**Comment by sebastianebarb** [comment]
@joshuagee its in there https://drive.google.com/open?id=0B0RwQU94BhGeei1OeXNiU2ZQTzQ
