### ISSUE TITLE
Construction Safety Video - Covid19 Updates

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1623]
Working with Peter Kenny from ISD, at Chief Brophy's request. 

Planning on a shorter video for social and a more general audience, and then a longer more detailed version for construction contractors etc. Filming at a construction site with Suffolk.

**Comment by KristinaVicario** [comment]
https://drive.google.com/drive/folders/1E6VIBKaSsM1hFABVFpXvRVmVxpnizt48

**Comment by GuruAmar9** [comment]
YouTube link: 
the short construction video: https://youtu.be/JZLNTULQW3g
and the full version: https://youtu.be/5Mts9GGv3gk
