### ISSUE TITLE
Social distancing from above (Video)

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1629]
Contact: c.princeboucher@gmail.com 

Due: before the next two weeks

Task: We need to create a video that shows all social distancing in a real-time example. we should work to get Drone footage people not social distancing (where we can't see their face) and show off the lack of space between them to push how important social distancing is.
- We will ask Kris to get the footage
- Sebastian or Brandon can add effects

Examples: 
https://vimeo.com/24572222
https://www.instagram.com/p/B_8c3snlIpa/

**Comment by KristinaVicario** [comment]
https://drive.google.com/drive/folders/1qBgzHEcXiS_4n7e2H4UFodrU5qU97q64?usp=sharing
