### ISSUE TITLE
BPS Commencement Video

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1640]
Due to Channel 5 by June 1st

Update from Jessica on 5/18:

Here is the valedictorian folder: https://drive.google.com/open?id=1C3z2suC-6vsJyuVNQg9H13ZV2VOdCjeR and the photos and videos for the montage: https://drive.google.com/drive/folders/1pLxV59KcJ9JhEZe9FcPJpjqpXRogcQ94?usp=sharing.

The deadline is today, however 2 schools asked for an extension and I told them to get them in by Wednesday. 

We will have the superintendent video to you on Friday. John King's video is being sent to us on May 27th.

***Need to send Channel 5 a script for the anchor later this week (by 5/22)

**Comment by GuruAmar9** [comment]
https://youtu.be/fBq2nQoBgQQ
