### ISSUE TITLE
Mayoral Tapings May 18-May 22

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1643]
Any tapings we need to help press with:

**Comment by KristinaVicario** [comment]
Project Place video
Virtual Graduation for the The Federation for Children with Special Needs​
Boston Arts Academy - MW
Ginormous Climb​ - NK
UMass Boston 2020 grad message​ - NK

**Comment by GuruAmar9** [comment]
From the 5.15 taping, edited this week:

Virtual Graduation Announcement - with captions
National EMS Appreciation Week - with captions
Academy of the Pacific Rim
WGBH Salute to Keith Lockhart
High School Quiz Show congrats to Boston Latin School 
Mass Military Heroes Fund
