### ISSUE TITLE
Core Priorities graphic update.

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1646]
Contact: David Elges
Due: Open
Tas: remake the attached graphic![Core Priortities.jpg](https://images.zenhubusercontent.com/582f674ab9dc3c6220223141/a5bbb0c8-07d7-49ac-b17a-fec6f745e7fb)

**Comment by navya-kaur** [comment]
![doit_priorities-03](https://user-images.githubusercontent.com/67284169/85768338-c487b380-b6cd-11ea-8dbf-f5d15f5aeef7.png)

**Comment by sebastianebarb** [comment]
![doit-01.png](https://images.zenhubusercontent.com/582f674ab9dc3c6220223141/603a40ac-8de7-4c50-acd8-083155904a80)![doit-02.png](https://images.zenhubusercontent.com/582f674ab9dc3c6220223141/0a8a70eb-e85b-489d-b1a4-d7fff7942923)![doit-03.png](https://images.zenhubusercontent.com/582f674ab9dc3c6220223141/f2e25c74-741e-44e9-9edd-5f868a81138a)

**Comment by navya-kaur** [comment]
[doit.pdf](https://github.com/CityOfBoston/creative-team-workflow/files/4966930/doit.pdf)
