### ISSUE TITLE
How to Make a Flower Box

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1659]
I saw how great your "how to make a face mask" video was, and thought we could make a "How To Make a Flower Box" video. Gardening seems to be very popular right now, and it's one of the few enjoyable activities you can do while socially distancing AND it helps beautify the city. 

Point of Contact: Nora Doherty

"I was planning on going over to the greenhouse tomorrow morning at 10AM and doing some filming with Tony Hennessy (the head of horticulture).

I'll plan on getting plenty of footage and then organize it nicely into a google drive folder and label everything accordingly. 

Would either of you be able to then edit the footage into a short 1-2 minute video for social? 

If so, I would make a news posting on Boston.gov with the video and then link to a bunch of local florists that folks can buy the "ingredients" from to then make their own boxes. I've been working with Main Streets on putting together a good list of places."

-Deadline is hopefully Thursday per Erin Santhouse's suggestion of getting it into the weekly employee resource email.

**Comment by sebastianebarb** [comment]
I'm not sure we have time for this right now. lets chat

**Comment by KristinaVicario** [comment]
Yeah I heard about the Mayor's request, pushing this to next week.
