### ISSUE TITLE
Virtual 4th of July Oration video

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1674]
Becca just heard back from the Mayor and he would like to record remarks for 4th of July. Traditionally, there is an oration at Faneuil Hall after the reading of the Declaration of Independence.  The Mayor did this oration in 2014.  
We are working on getting recordings of the Declaration of Independence, God Bless America and the Pledge to put together this virtual program.  
Ideally, we'd like to get this recording with time to produce it and we'd like to request DoIt/Monum help to put it all together so that it matches the quality of the other videos with the Mayor. If there isn't the capacity for that request, let me know so we can find an alternative.

**Comment by KristinaVicario** [comment]
No longer our project.

**Comment by GuruAmar9** [comment]
Mayor taping on 4th of July: https://youtu.be/mCzeTObV8KI

I ended up editing/making minor tweaks to these two:
The USS Constitution reads the Pledge of Allegiance: https://youtu.be/PhKw2tgDwhI

Declaration of Independence Reading by the Ancient and Honorable Artillery Company: https://youtu.be/9SRERwhsFlA
