### ISSUE TITLE
fireworks taskforce - pamphlet 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#1692]

**Comment by carolinestj** [comment]
Google doc with text 
https://docs.google.com/document/d/1mRvT51owptx1tdGOwMbz0HoC48zwWwjF0J9tl1GP6Xo/edit#

![Fireworks 01 - 000_1.png](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/df9cf6b8-e2a9-4cdc-9c54-9a666f0d2d6a)![Fireworks 02 - 001_1.png](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/6a77eabb-0cd4-486d-bc4e-62a37be228fe)

**Comment by carolinestj** [comment]
- [x] keep the hand but make it smaller 
- [x] make house a little bit bigger 
- [x] add logos to the bottom 
- [x] remove specific councilor name and have it be generic 
- [ ] cut some text

**Comment by sebastianebarb** [comment]
Add in 311 section?
