### ISSUE TITLE
Intern programing 2020

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1712]
Contact: jeanethe.falvey@boston.gov

Due: ?

Task
https://docs.google.com/document/d/1opLPmZ1cCoOxbjZ43RgXRkMHc5DcIomVscbnWTb8-GQ/edit?usp=sharing

**Comment by GuruAmar9** [comment]
Follow-up survey from our three BPS interns: https://docs.google.com/spreadsheets/d/1wBu3ZrpCSw4BijS2NfyZfvYCj2lPGc9qPoeBCSLxYu0/edit?usp=sharing

Wondering what other documentation should be added before we can close this?
