### ISSUE TITLE
Reverse white/black on the household icons for Metrolist SVGs

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/design-team-workflow#1713]
![image](https://user-images.githubusercontent.com/55395593/88838554-b97de280-d1a7-11ea-998b-4178ac658b36.png)

I'd like to have 1-6 size household icons in SVG format for a new feature for the AMI Estimator on Metrolist. Ideally by 8/3. Thank you!

**Comment by sebastianebarb** [comment]
@AmyWipfler
https://drive.google.com/open?id=1pTv1wZrB79KE6sIfb09reM7DdSHROITo&authuser=sebastian.ebarb%40boston.gov&usp=drive_fs

**Comment by AmyWipfler** [comment]
Thanks so much!

**Comment by hguiney** [comment]
Thanks @sebastianebarb. However, we are looking for the inverse of this: white figures with black outlines, so as to match the look & feel of the rest of the site. For reference, here is how the icons are currently used on Metrolist: https://d8-ci.boston.gov/metrolist/ami-estimator. But I see you are on vacation currently, so maybe @carolinestj can take this?
