### ISSUE TITLE
Comp request: Revised Boston.gov contact information

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/design-team-workflow#173]
Contact information on Boston.gov pages shows up immediately below the body section of pages. However, depts are getting called too frequently with questions that their web pages answer. Proposed solution is to hide dept contact information to the bottom of the page on mobile and keep the current set up on desktop.

Please do a comp for each of the following example pages:
[ISD](https://www.boston.gov/departments/inspectional-services)
[How to pay a parking ticket](https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket)

[Desktop low fidelity comp](https://docs.google.com/drawings/d/1a7F9vIu_1hRipnLP8pj_AQsFs8DqG79idFxMNd54DgQ/edit).

Desktop comp requirements:

- Create a new full-width section/component below a set of components that replicates the department contact information only (dept name, phone, email, address).

[Mobile low fidelity comp.](https://docs.google.com/drawings/d/1UQo1QqeU8MDlEMVu0SCzN8Q7o5CDsFUdGaLh58ZUlbw/edit)

Mobile comp requirements

- Create a mobile view of a new full-width section/component below a set of components that replicates the mobile department contact information only (dept name, phone, email, address).
- Hide normal sidebar department contact information (dept name, phone, email, address) from showing, but display any other sidebar items as normal on mobile.
- Add some kind of a prompt for people to jump to the (new) contact information at the bottom of the page. The prompt should be below any additional sidebar information.

**Comment by sebastianebarb** [comment]
@reillyzlab should I close this out?
