### ISSUE TITLE
Designs for new City Archaeology Lab

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#1734]
Contact: joseph.bagley@boston.gov and sarah.keklak@boston.gov

Due: April 2021

Task:
We are (finally) moving forward on the plans to move the current Archaeology Lab into a brand new (to us) space on the first floor of the Archives Building at 201 Rivermoor Street!  The reopening is currently planned for around April 2021

We will be carving out part of the City Archives reading room and installing new glass-walled laboratory and office areas in addition to storage rooms.  There will be a ton of places for new artwork in the laboratory spaces, offices, and glass walls.

I'm reaching out to ask if you may have the capacity and interest in designing some new creations for the new City Archaeology Lab?

I'm attaching the latest architect renderings of the space.  There will be about 1,000 square feet of public spaces in the new lab, all visible from the public reading room through the glass walls as well as during tours of the space. 

We already have one of the best archaeology programs in the country, and now I'm interested in making this the best looking archaeology lab in the country. I think your skills would be key in making that happen.    

I don't have a ton of details on how the designs would actually be implemented including the overall budget for implementing this (we're still in the first weeks of design/planning), but you'll see in the attached document that artwork on the walls/glass is part of the overall plans.  

I'm very open to designs and happy for you all to run wild with this.  If you and your team are interested, please let me know and I'm happy to share measurements as they become available.  The attached designs are the latest and total data I have. Given how little time we have, the overall room locations/sizes/walls are very unlikely to change significantly from here. Happy to answer any questions.

All files 
https://drive.google.com/drive/folders/1DFBNGgSQdgJURm2pgnOCR-VH-qDcLrL7?usp=sharing

https://drive.google.com/open?id=1qhNs6AAf1FeDRAQv1HQf96se3nBxHHKA&authuser=sebastian.ebarb%40boston.gov&usp=drive_fs

**Comment by sebastianebarb** [comment]
[200811 Meeting Slides_EMS Archaeology Scope (1) (1).pdf](https://github.com/CityOfBoston/creative-team-workflow/files/5105137/200811.Meeting.Slides_EMS.Archaeology.Scope.1.1.pdf)

**Comment by sebastianebarb** [comment]
[Archaeology Dept Environmental Graphics Mtg.pdf](https://github.com/CityOfBoston/creative-team-workflow/files/5429780/Archaeology.Dept.Environmental.Graphics.Mtg.pdf)
[Uploading 200811 Meeting Slides_EMS Archaeology Scope (1) (1).pdf…]()

**Comment by sebastianebarb** [comment]
Notes from meeting
https://drive.google.com/drive/folders/1WGpvLbPIo4VfIgGdu1Zzu7ci6_S1yHFt?usp=sharing
- Funny is great - Indiana Jones reference- Outhouse- Joe to select 20 objects (don't need to use all of them)

![faneul hall](https://user-images.githubusercontent.com/20642299/97010570-91d2b800-1513-11eb-91b0-77ba6d7193bd.jpg)
![Katherine Nanny Naylor Privy](https://user-images.githubusercontent.com/20642299/97010577-94351200-1513-11eb-9bc1-adc88c725640.jpg)
![Bagley-Poulsen_Boston-05](https://user-images.githubusercontent.com/20642299/97010583-96976c00-1513-11eb-8812-bf914ac8bf7a.jpg)

**Comment by sebastianebarb** [comment]
- Full back wall = 35'-3 1/2" overall (refer to the PDF sent along earlier and re-attached to note the presence of the door and sidelite within that dimension) 
- Both sides of the non-glass pillar = 1'-2 1/2" each face
- Half of the back wall = 8'-9" (overall length is 17'-6")
*All of these dimensions should be verified in field after construction is carried out on these spaces*

**Comment by carolinestj** [comment]
![Screen Shot 2022-02-15 at 13.58.24.png](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/e6d4cd2a-fc3b-4ba3-a89c-a407e67b673a)
