### ISSUE TITLE
COB Mayor's Scholarship Award Ceremony

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1735]
Main contacts Rachel Goldstein <rachel.goldstein@boston.gov>, Casey Brock-Wilson <casey.brock-wilson@boston.gov>

Short video with Mayor's taping, photos of each recipient and quotes from them, and a couple committee member messages to the college student recipients of the award.

Recipients are here: https://docs.google.com/spreadsheets/d/1-x_VYpAtccv6BwP9drN0OyU05NjT_0fxMiev64PnYFM/edit?usp=sharing

**Comment by KristinaVicario** [comment]
https://www.youtube.com/watch?v=_0G8-Hu3nTg&t=79s
