### ISSUE TITLE
Review final wireframes/deliverables from GAUXDI group re Status of City Departments page on boston.gov

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/design-team-workflow#1778]
The most recent General Assembly UXDI group looked at this [page](https://www.boston.gov/news/covid-19-status-city-boston-departments) on boston.gov, which is meant to provide users with an overview of the changes to City departments' hours and scope of operations. They provided some suggested UX and design improvements which you can see here:

https://docs.google.com/presentation/d/1JW89yZQWigvwdGRZ_TyZucQYUhctYCMR15doRLg83xc/edit?usp=sharing

@sebastianebarb based on the timeline we talked through, the goal would be to have you review/vet the wireframes, incorporate any changes you think are necessary, and hand them off to me in early October and I can work with the dev team to scope any custom development that would be needed to accomodate the designs.  Let me know if that works

**Comment by sebastianebarb** [comment]
@andrebtlima do you still need this from me?
