### ISSUE TITLE
Parks Pumpkin quick video

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1785]
Steve Kruszkowski <steve.kruszkowski@boston.gov> from Parks filmed himself carving a pumpkin for the Parks' jack-o-lantern contest this month. He provided all the footage and music. He'll be posting to social.

Youtube link: https://youtu.be/OdASIGpHpbE

https://boston.gov/pumpkin

**Comment by KristinaVicario** [comment]
https://www.youtube.com/watch?v=OdASIGpHpbE&feature=youtu.be

**Comment by GuruAmar9** [comment]
Updated link, had to make a new version because of a date change: https://youtu.be/1CQkJJTl9LU
