### ISSUE TITLE
Different Ways You Can Vote Video

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1792]
One video with all ways you can vote, and then broken up into smaller bits, one for each way to vote.

**Comment by GuruAmar9** [comment]
Already added this to the other ticket, but here's the 33 videos about voting (mail-in, early and on Election Day): https://drive.google.com/drive/folders/1zJU68kQ-Ubmd8AVtsjmS2-9WV-3SnoLE?usp=sharing
