### ISSUE TITLE
City Hall Plaza Makeover Video + Content

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1820]
Still figuring out what this is but connected with Nora on a request from pat Brophy about a video announcing the plaza makeover. 

Maybe some cute little stopmotion vids too!

**Comment by GuruAmar9** [comment]
This will be ongoing, until the renovation is done in a year or two! Made some gifs, hopefully will be making more once I have more old photos to combine with the renderings.

Current videos/files live here: https://drive.google.com/drive/folders/1USxCy8qav2hBMf_zzUcAp_HC4v366y11?usp=sharing
