### ISSUE TITLE
Capture footage of JP Library art installation

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1839]
Working with Kristina McGeehan <kristina.mcgeehan@boston.gov> from Arts, to document a long-awaited art project installation outside of the JP library. Captured brickwork being installed, project to be completed Spring 2021. 

Drive folder here with photos and video from 12/11: https://drive.google.com/drive/folders/1gj7Fqs3IGr3LI2WFsI6soF-1DXYytFtZ?usp=sharing

**Comment by KristinaVicario** [comment]
I think this was wrapped up and Kristina M. got what she needed.
