### ISSUE TITLE
Grab and Grow program with BPS

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1846]
From August 2020. In collab with Xavier and Nancy Fisher (nfisher@bostonpublicschools.org), GuruAmar filmed the packing and handout of "Grab and Grow" bags for BPS students to take home. 

More info about the program from Nancy:
"To excite kids about eating the New England grown vegetables and fruits that are more and more on school menus, we plan to distribute Grab and Grow kits to students who come to your site for meals, with the help of Boston Cares volunteers. The mini urban farm Grab and Grow kits, that are packed in brown paper lunch bags, contain a tiny planting pot, “soil” pellet that inflates in water, and seeds for growing herbs, along with instructions.  The kits will give students the experience of growing something edible at home. Box(es) of packed Grab and Grow kits will be delivered to your school site either late next week, or at the beginning of the week of August 10.  The box(es) will be labeled Grab and Grow. 
The 6,000 kits that were packed and distributed through Boston school summer meal sites relate to a grant from the Henry P. Kendall Foundation to embed local New England Grown foods within the Boston Public School meals.  The kits were intended to help students make the connection between their mini urban "farms" and the work of New England farms to grow the local foods that are being offered more frequently on school menus.  The two-year grant program runs through school year 2020-2021. "

Exported photos, and used the b-roll in other projects, but no final video for this has been put together. Was hoping for some footage from families that grew the plants, showing the progression of the herbs growing. Next steps TBD. 

Photos for BPS: https://drive.google.com/drive/folders/1IXlPwYOIKihTuGAXXd0-4fD2Le9rc7x_?usp=sharing

**Comment by GuruAmar9** [comment]
Pivoting to make this a mini City as a Classroom!

**Comment by KristinaVicario** [comment]
https://drive.google.com/drive/folders/1aprkJijdyMmk5dzAKQXe7X0eVNGaA-yY

**Comment by KristinaVicario** [comment]
https://drive.google.com/drive/folders/1aprkJijdyMmk5dzAKQXe7X0eVNGaA-yY
