### ISSUE TITLE
BAA progress video for BPS

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1862]
Short, 60-second video for social on the progress of the BAA construction.

**Comment by KristinaVicario** [comment]
All footage in folder GuruAmar created here: https://drive.google.com/drive/folders/1DeiIbjtGKk8B-L6w8_wosOt6QARLr8D6

**Comment by GuruAmar9** [comment]
Exported files here (ended up including a sound bite from everybody at the topping off ceremony, longer video): https://drive.google.com/drive/folders/10pf-bvsTUHZo555yb__2Q3zZOJe4rRYq?usp=sharing

Youtube here: https://youtu.be/r1_KbMl8ySE
