### ISSUE TITLE
Green Ambassadors - Thompson Island

### ISSUE THREAD

**Issue by GuruAmar9** [CityOfBoston/design-team-workflow#1924]
Connected to the Thompson Island Outward Bound, year-long program with BPS students. Contact is still Jennifer Novak <JNovak@thompsonisland.org>, make sure to get approval from her before posting anything.

More info on the Green Ambassadors program: https://thompsonisland.org/programs/green-ambassadors

Should be a smaller video since there's not a ton of b-roll. Filmed in 2019. Two interviews were done for that, one with a youth worker, and another with the coordinator of the program. There are already selects of everything, it just needs to be cut together! 

This project lives on the COB-DAC-3 hard drive, folder name: 190801_City as a Classroom - Thompson Island (#1301)

**Comment by KristinaVicario** [comment]
https://drive.google.com/drive/folders/1mfNOVn5vJxrohIorhbUOQNfpaVF1Xn_R

**Comment by KristinaVicario** [comment]
https://www.youtube.com/watch?v=4l4Gddywfbc
