### ISSUE TITLE
Email Preference Center Mockup

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/design-team-workflow#197]
Because we've requested more customized work, Upaknee has asked for a styled mock up of how we want the City of Boston newsletter subscription center to work. Below is a mockup, but here are some requirements. 

I am a user and I want to easily and quickly manage my City of Boston newsletter subscriptions. 

1. Users are coming to this page after clicking "manage my preferences" on an email, so they are in a semi-confirmed state. 
2. Fields at the top: email, zip, first name, last name - should be autopopulated from link.
3. Emails in a list form (similar to our list style), with headers for each section on the left. 
4. Top section is "my subscriptions" -- this is generated dynamically and if blank, should say "none" 

![Wireframe](https://cloud.githubusercontent.com/assets/20726937/22986295/04781ca8-f379-11e6-8395-0fba53026b22.jpg)

**Comment by joshuagee** [comment]
Updates:

- Change "subscribe" to "update my information" in the button on the top
- Remove "unsubscribe from all" 
- We want the headings to also be drawers. They will be default open, but once we have 30-40 newsletters, we'll need them default close. Please show one open drawer and one closed drawer. 
- Change the check box to a small button labeled "subscribe" 
- Shrink the fields so that subscriptions are visible above the fold. 

Can you also provide a mobile view? Condense the fields, drop the sidebar, and show the drawers closed.

**Comment by sebastianebarb** [comment]
@joshuagee @collinmgately try this on for size.  header and footer should be based on what is live on the site.
![email preference center](https://cloud.githubusercontent.com/assets/20642299/23765097/06d8c068-04ce-11e7-9bb3-3c6957617c4f.png)
![480-process](https://cloud.githubusercontent.com/assets/20642299/23765098/06e1afac-04ce-11e7-9998-13dc70430f86.png)



[Email Preference Center_phone.pdf](https://github.com/CityOfBoston/design-team-workflow/files/831991/Email.Preference.Center_phone.pdf)
[Email Preference Center.pdf](https://github.com/CityOfBoston/design-team-workflow/files/831990/Email.Preference.Center.pdf)
