### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#1971]
Contact: Emily Dydo, Maizie Nelson,

Lightkeeper icon: create a version of this icon to show a gender neutral person holding a lantern instead of behind the helm
Lantern: change the flame to a candle
Lighthouse: Please update this to a lighthouse instead of street lamp. There is an existing lighthouse icon (shown here). Can we use this as our main portal icon, or can you create a similar version, perhaps without the stripes?

In addition to the three icon updates she shared below, we also need assistance creating a character avatar to represent our Virtual Agent chat bot.

**Comment by sebastianebarb** [comment]
@carolinestj I can take this one!

**Comment by sebastianebarb** [comment]
Connected to ticket #1918 
Icons from that project can be found here: https://docs.google.com/document/d/1fWqhKkGuJ4kB6VhxmYwyImWsrMWBRuAsO0nfeVuwTkE/edit?usp=sharing
