### ISSUE TITLE
Mayor movie night intro video 

### ISSUE THREAD

**Issue by KristinaVicario** [CityOfBoston/design-team-workflow#1985]
Filming and editing a quick intro to play before the movies in the parks series.

Filmed the mayor 8/02 and editing 8/03 for a draft.

**Comment by KristinaVicario** [comment]
https://drive.google.com/drive/folders/17Ek841KqmfScdxQFM0kbKB-0Zpgovcl1

**Comment by Neslihan-Sahinkaya** [comment]
This looks so cute! Great work Kristina!
