### ISSUE TITLE
New Access Boston Icon for Avolve app

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/design-team-workflow#2056]
Name of the application = Avolve
Description of what the app is = used by ISD for planning (way for constituents to upload plans, ISD folks to refine, share and store them)
Timeline (when do you need to have live in Prod) = end of Feb 2022, UAT is end of October (but we can use a placeholder icon for that).

Client = Kelly Mackey

**Comment by sebastianebarb** [comment]
![Avolve-379](https://user-images.githubusercontent.com/20642299/136437458-26d1ac96-a072-421a-ac3c-d7f942c17f0b.png)

**Comment by g-grozier** [comment]
Kelly says: That was speedy! This works as is, but if it's an easy switch out an image of a building (see pulled from the branding icons below or similar) in place of the lines on the paper that would be a great representation of a building plan. Thanks! 
![building](https://user-images.githubusercontent.com/91092683/136562005-82b556ae-96f0-4454-a146-5fc0026ba383.png)

**Comment by sebastianebarb** [comment]
[image: all icons2-379.png]

On Fri, Oct 8, 2021 at 9:04 AM Gretchen Grozier ***@***.***>
wrote:

> Kelly says: That was speedy! This works as is, but if it's an easy switch
> out an image of a building (see pulled from the branding icons below or
> similar) in place of the lines on the paper that would be a great
> representation of a building plan. Thanks!
> [image: building]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_91092683_136562005-2D82b556ae-2D96f0-2D4454-2Da146-2D5fc0026ba383.png&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=Ojfn8jzyZqnDhEJtmlbvT_EqiZq5hiJihBNLGp5RAC8&m=mvXUss15RW8NKUz5XDbtQ4fpRzOc1CDvbfXZOtuPu-U&s=SZd4O12FPEaKtjyJFS9J8-EuZ427SCHOpxOjBaPuu1Q&e=>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CityOfBoston_creative-2Dteam-2Dworkflow_issues_2056-23issuecomment-2D938626855&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=Ojfn8jzyZqnDhEJtmlbvT_EqiZq5hiJihBNLGp5RAC8&m=mvXUss15RW8NKUz5XDbtQ4fpRzOc1CDvbfXZOtuPu-U&s=QvT0Q9zq5FaipB0bo-m471OREQs9aHA95CMUffXI65A&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AE5PT65JC5FG654QQD23BNLUF3T65ANCNFSM5FRRZVKQ&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=Ojfn8jzyZqnDhEJtmlbvT_EqiZq5hiJihBNLGp5RAC8&m=mvXUss15RW8NKUz5XDbtQ4fpRzOc1CDvbfXZOtuPu-U&s=854hAqqhrUzrQ5VKLAA8pMQI3YODlM2vnVxNFv3wzqw&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=Ojfn8jzyZqnDhEJtmlbvT_EqiZq5hiJihBNLGp5RAC8&m=mvXUss15RW8NKUz5XDbtQ4fpRzOc1CDvbfXZOtuPu-U&s=CVwBMcOVIygLmkHHZ1GXebvXKHI0VHd2gV2Hy-ZG74s&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=Ojfn8jzyZqnDhEJtmlbvT_EqiZq5hiJihBNLGp5RAC8&m=mvXUss15RW8NKUz5XDbtQ4fpRzOc1CDvbfXZOtuPu-U&s=z2VoBlAyzww_VZzqOn3GERcEOzmk6gcvNl4DydU4-sA&e=>.
>
>


-- 

Sebastian Ebarb (*pronouns he/him/his*)

Design Director for the City of Boston

Department of Innovation & Technology

www.boston.gov/digital

You can check out *www.boston.gov/brand <http://www.boston.gov/brand>* for
all your *BOSTON* brand needs. You can sign up for design/Canva class here
<http://Boston.gov/canva>, and you can also see samples of our work at
*boston.gov/design-portfolio
<http://boston.gov/design-portfolio>.*

**Comment by sebastianebarb** [comment]
![all icons2-379](https://user-images.githubusercontent.com/20642299/136575981-d8d1d89b-7843-4057-a126-3252fac7aaa9.png)

**Comment by sebastianebarb** [comment]
@g-grozier checking in on this!

**Comment by g-grozier** [comment]
@Sebastian Ebarb ***@***.***> we've been going back and
forth with the vendor for months as they aren't able to support standard
authentication protocols.
Their app is dependent on i-frames (welcome back to the 20th century).  So
this integration is still IN PROGRESS

**Comment by carolinestj** [comment]
@g-grozier is this ticket still open?

**Comment by g-grozier** [comment]
they ended up not being able to support single log-out so won't have an
icon on AB Portal.
Ticket can be closed
