### ISSUE TITLE
Request for a new icon for Access Boston Portal - Qualys

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/design-team-workflow#2075]
Name of the application = Qualys
Description of what the app is = it's a Vulnerability Scanner that the IT Security Ops team uses to check traffic on City networks (the company logo is a shield with a Q on it, yawn).

Timeline (when do you need to have live in Prod) = this is probably end of November/early December and it's internal DoIT (not huge user base) so I say go super nerdy with this icon. : )

**Comment by g-grozier** [comment]
final testing for this app has begun...any estimate on an icon? (sorry I know there is a lot going on right now) @sebastianebarb

**Comment by sebastianebarb** [comment]
@g-grozier thoughts

**Comment by sebastianebarb** [comment]
![Screen Shot 2021-11-08 at 2 29 39 PM](https://user-images.githubusercontent.com/20642299/140805717-e1c064c9-dd4e-4c17-bda8-7fb20984e637.png)

**Comment by g-grozier** [comment]
I like this ..vaguely creepy.  I shall run it by my office mate to see what
he thinks -- it's his tool.  G.




[image: COB_B_Blue_square-01.png]

*Gretchen Grozier *(pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)

**Comment by sebastianebarb** [comment]
@g-grozier check-in on status

**Comment by g-grozier** [comment]
This one is waiting on the vendor @Sebastian Ebarb
***@***.***>
@Alex Tsichlis ***@***.***> has been working with Qualys and
I believe we are nearly there. But still IN PROGRESS
G.

**Comment by g-grozier** [comment]
Awesome, thanks for the updates.

On Thu, Dec 16, 2021 at 12:51 PM Gretchen Grozier <
***@***.***> wrote:

> This one is waiting on the vendor @Sebastian Ebarb
> ***@***.***>
> @Alex Tsichlis ***@***.***> has been working with Qualys
> and I believe we are nearly there. But still IN PROGRESS
> G.
>
>
>
> On Thu, Dec 16, 2021 at 12:20 PM Sebastian Ellington Flying Eagle Ebarb <
> ***@***.***> wrote:
>
>> @g-grozier
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_g-2Dgrozier&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=_OsXyK-KmXSXIV0mmKyHwKalFB8AoBYCd_Aj2dKZtak&e=>
>> check-in on status
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CityOfBoston_creative-2Dteam-2Dworkflow_issues_2075-23issuecomment-2D996020843&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=howC2fh9cTdFwaqpGdx1WXKze8qLTCHkqJg8jVqHlVo&e=>,
>> or unsubscribe
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVW7NS5UYWULXLL6FCQCH3DURINVHANCNFSM5GWB33EQ&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=EyMhIAWHElaBr2DV_J_6FcvFje-ITR3mJd908tciW98&e=>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=QDoMl7IDRvr-ex0RiZP6RjQZcm-P8b8NPy9Tz6p54M4&e=>
>> or Android
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=_XBOcOIKhNEOhhNbFuAKuE0f0BtVehruxCLf5pvrUQk&e=>.
>>
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

-- 

Sebastian Ebarb (*pronouns he/him/his*)

Design Director for the City of Boston

Department of Innovation & Technology

www.boston.gov/digital

You can check out *www.boston.gov/brand <http://www.boston.gov/brand>* for
all your *BOSTON* brand needs. You can sign up for design/Canva class here
<http://Boston.gov/canva>, and you can also see samples of our work at
*boston.gov/design-portfolio
<http://boston.gov/design-portfolio>.*

**Comment by g-grozier** [comment]
Hi There,

We do have a ticket opened with Qualys support and  I just followed up with
them again. I suspect they could be slammed with log4j related tickets.

--Alex

On Thu, Dec 16, 2021 at 12:52 PM Sebastian Ebarb ***@***.***>
wrote:

> Awesome, thanks for the updates.
>
> On Thu, Dec 16, 2021 at 12:51 PM Gretchen Grozier <
> ***@***.***> wrote:
>
>> This one is waiting on the vendor @Sebastian Ebarb
>> ***@***.***>
>> @Alex Tsichlis ***@***.***> has been working with Qualys
>> and I believe we are nearly there. But still IN PROGRESS
>> G.
>>
>>
>>
>> On Thu, Dec 16, 2021 at 12:20 PM Sebastian Ellington Flying Eagle Ebarb <
>> ***@***.***> wrote:
>>
>>> @g-grozier
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_g-2Dgrozier&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=_OsXyK-KmXSXIV0mmKyHwKalFB8AoBYCd_Aj2dKZtak&e=>
>>> check-in on status
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CityOfBoston_creative-2Dteam-2Dworkflow_issues_2075-23issuecomment-2D996020843&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=howC2fh9cTdFwaqpGdx1WXKze8qLTCHkqJg8jVqHlVo&e=>,
>>> or unsubscribe
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVW7NS5UYWULXLL6FCQCH3DURINVHANCNFSM5GWB33EQ&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=EyMhIAWHElaBr2DV_J_6FcvFje-ITR3mJd908tciW98&e=>
>>> .
>>> Triage notifications on the go with GitHub Mobile for iOS
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=QDoMl7IDRvr-ex0RiZP6RjQZcm-P8b8NPy9Tz6p54M4&e=>
>>> or Android
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=exO2fkHp3C8oRxaPdb618USIsT1gpGj0oRZK8FXgQnI&m=vzevZsLXp4ylMC5bEO2gml3mnhAUtvX0bTK4bDlJips&s=_XBOcOIKhNEOhhNbFuAKuE0f0BtVehruxCLf5pvrUQk&e=>.
>>>
>>> You are receiving this because you were mentioned.Message ID:
>>> ***@***.***>
>>>
>>
>
> --
>
> Sebastian Ebarb (*pronouns he/him/his*)
>
> Design Director for the City of Boston
>
> Department of Innovation & Technology
>
> www.boston.gov/digital
>
> You can check out *www.boston.gov/brand <http://www.boston.gov/brand>*
> for all your *BOSTON* brand needs. You can sign up for design/Canva class
> here <http://Boston.gov/canva>, and you can also see samples of our work
> at *boston.gov/design-portfolio <http://boston.gov/design-portfolio>.*
>
>
>
>

-- 



*Alex Tsichlis*

*Principal Information Security Analyst*



*Department of Innovation & Technology City of Boston | City Hall Room
703 ***@***.***
***@***.***>*  *| 617.635.2272 (w)*

**Comment by carolinestj** [comment]
@g-grozier Is this one still open?

**Comment by g-grozier** [comment]
Same thing, Qualys is integrated but not on the AB Portal (they cannot do
SLO).
This ticket can be closed




[image: COB_B_Blue_square-01.png]

*Gretchen Grozier *(pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)
