### ISSUE TITLE
Janey fairwell video

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#2080]
Building off of the 100-day video we will add in new items that the Mayor would like to highlight. 
additional we should swap the music, title screen, and any other assets we feel would keep the video fresh but is low effort.

**Comment by Neslihan-Sahinkaya** [comment]
[](https://drive.google.com/drive/folders/1i4uCEnGmLz29qLAKlkRpGRXmSwKrab7r?usp=sharing)

The Mayor's Office will show the video during the Farewell Speach this afternoon and they will also post across their own social media accounts.
