### ISSUE TITLE
Boston Uncovered: Landmark Videos

### ISSUE THREAD

**Issue by Neslihan-Sahinkaya** [CityOfBoston/design-team-workflow#2094]
Teamed up with Nicholas Armata from BLC for this project. Thinking about linking Joe Bagley as well. 

This project will highlight a Boston Landmark and the history behind it while giving information on how BLC operates. 

We are in the process of creating a list of Landmarks we can highlight, then we will choose 1-2 and start filming before it gets too cold.

**Comment by carolinestj** [comment]
@Neslihan-Sahinkaya is this ticket still open or can we close it?
