### ISSUE TITLE
Updates to Parking Ticket Screens

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/design-team-workflow#212]
We've gotten a number of user compliants about the online parking ticket forms. There are a lot of problems, but we don't have the ability to make any significant changes to it (yet). 

What we can do is edit text and make basic html edits. Even with those limitations, I think there is a lot we can do. 

Can you mock up some new versions of the screenshots below that have cleaner flow. I'm also going to work with James to clean up the language. 

One particular complaint is that the credit card fee isn't clear. I think this might be an occasion of too many warnings. People are glossing over the big scary looking warning box. 

Step 1
![parkingstep1](https://cloud.githubusercontent.com/assets/20726937/23365756/38f0f718-fcd2-11e6-82f9-4f48cb8ac57b.JPG)

Step 2
![parkingstep2](https://cloud.githubusercontent.com/assets/20726937/23365754/38e76cd4-fcd2-11e6-8efa-ac4175aa2d66.JPG)

Step 3
![parkingstep3](https://cloud.githubusercontent.com/assets/20726937/23365755/38efe346-fcd2-11e6-81e9-0226816ec935.JPG)

**Comment by sebastianebarb** [comment]
[Updates to Parking Ticket Screens.pdf](https://github.com/CityOfBoston/design-team-workflow/files/838648/Updates.to.Parking.Ticket.Screens.pdf
@joshuagee I would love to hear you thoughts. I tried to design for the least amount of dev time. I can go further if needed.

**Comment by joshuagee** [comment]
This is great. I think we can also punch of the text, but I'll ask @jduffy2001 to handle that.
