### ISSUE TITLE
Request for Icon for Access Boston Portal - Fair Housing (Salesforce)

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/design-team-workflow#2183]
Name of the application = Fair Housing Salesforce
Description of what the app is = FH uses this app for case management, data collection and reporting
Timeline (when do you need to have live in Prod) = late March

further info: Salesforce is setting a requirement to use Multi-Factor Authentication so we are integrating the SF Orgs in use around the City, since Access Boston has MFA already (and all employees use AB). They asked for a house (like their department logo)

**Comment by g-grozier** [comment]
@carolinestj meeting with this group on 3/9 at 13:30 so would love to have something to show them then!

**Comment by carolinestj** [comment]
See if any of these work @g-grozier 
![house_2](https://user-images.githubusercontent.com/22770827/157074558-1be79008-adaa-4799-9797-8de9e1164f93.png)
![house](https://user-images.githubusercontent.com/22770827/157074560-453d1412-9b33-4f07-9637-0267e23accba.png)
