### ISSUE TITLE
Comp request: Budget exec summary graphs

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/design-team-workflow#221]
Screenshots below. 

Ask: Please create Boston.gov styled graphs of the following screenshots. Please keep the same information as on each screenshot, but styled similarly to how the current budget graphs were styled (ref #179). Don't include any references to Figure ## - just couldn't get the screenshot to exclude that part of the image.

Sizing: please no smaller than 250w x 300h and no larger than 350w x 425h. Ideal size is ~300w x 400h, but please keep consistency with #179 as far as standards. 

Due Tuesday March 14th at the latest, but happy to receive earlier.

@sebastianebarb let me know if you have any questions or need clarification. Otherwise, looking forward to more great work!

![screen shot 2017-03-01 at 11 19 01 am](https://cloud.githubusercontent.com/assets/3886936/23511532/5a5fbfc8-ff2b-11e6-9db1-a0d3da21440d.png)
![screen shot 2017-03-01 at 10 52 49 am](https://cloud.githubusercontent.com/assets/3886936/23511534/5a606f72-ff2b-11e6-9a17-f10215d6fb81.png)
![screen shot 2017-03-01 at 10 16 36 am](https://cloud.githubusercontent.com/assets/3886936/23511535/5a64291e-ff2b-11e6-8662-49572a2257e2.png)
![screen shot 2017-03-01 at 10 09 47 am](https://cloud.githubusercontent.com/assets/3886936/23511533/5a600000-ff2b-11e6-8e39-f607a2f14b91.png)
![screen shot 2017-03-01 at 9 53 58 am](https://cloud.githubusercontent.com/assets/3886936/23511536/5a68e8d2-ff2b-11e6-9db5-4c8ac9a33d44.png)

**Comment by sebastianebarb** [comment]
@hackajesse take a look
https://drive.google.com/open?id=0B0RwQU94BhGeT2JiaG1CRFgxVW8

![budget exec summary graphs-05](https://cloud.githubusercontent.com/assets/20642299/23754713/fddadea0-04ab-11e7-871e-a4c9b9e11e61.png)
![budget exec summary graphs-01](https://cloud.githubusercontent.com/assets/20642299/23754716/fdde2c72-04ab-11e7-8deb-7d56d44d5ce8.png)
![budget exec summary graphs-02](https://cloud.githubusercontent.com/assets/20642299/23754714/fddd827c-04ab-11e7-8274-8dcdca1220e8.png)
![budget exec summary graphs-03](https://cloud.githubusercontent.com/assets/20642299/23754717/fde0ace0-04ab-11e7-9f58-762c12b8c4b0.png)
![budget exec summary graphs-04](https://cloud.githubusercontent.com/assets/20642299/23754715/fddda3a6-04ab-11e7-94fe-30f4dbc25c84.png)
