### ISSUE TITLE
Request for Icon (Access Boston) for 'Confirm ID'

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/design-team-workflow#2218]
Confirm ID 
new workflow Digital has helped create which will allow IT support staff across the City to confirm the identity of a user before doing a password reset (or other account update) in a non-AB application
To avoid confusion with the Identity Verification that is for Access Boston this workflow will be behind the icon
UI done, and Phill is working on code - so need by end of March pls

**Comment by carolinestj** [comment]
@g-grozier would either of these work? ![id_badge.svg](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/05978bc5-658c-4ece-b898-3c4347eb0f6b)![id.svg](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/bdd4ce7e-93d6-40b8-8777-bbcb797daf0b)

**Comment by g-grozier** [comment]
Let's go with the ID badge one please!!  G.
