### ISSUE TITLE
"Splash" screen image for app opening

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#2265]
This image is used in app. When the customer opens the app, they will be provided this image.

**Comment by duffy-james** [comment]
Example below of what the splash image looks like. @carolinestj maybe potentially use the same image noted in Ticket #2266 #2266 for the ParkBoston website.

![ParkMobile-Splash-Screen](https://user-images.githubusercontent.com/7929556/168819504-52d48423-3b52-4415-85e5-70e68259891b.PNG)

Dimensions appear to be 750 x 1334 px

Julia was hoping for two different versions of the splash screen to share with them, ideally by end of week (May 20).

**Comment by carolinestj** [comment]
@duffy-james Yup feel free to add any photos you think would work, no preference from me!
