### ISSUE TITLE
Image for ParkBoston website

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#2266]
Request here is to provide a high-resolution City of Boston image for the homepage of the new Park Boston website.

[You can see an example](https://meterup.parkmobile.io/) of what it looks like. Caroline, I could just pull a few photos from the [Digital Team photos folder](https://photos.google.com/share/AF1QipN5rSTBHNYcqTqHLL5lVBYo6knY081PjfQ8NENFVZRZoLfLsOiPV462fzolNkQwHg?key=eXJUNHR1SmRGd09mZElBekQwczBqeEdfZGdiTzNB), but wanted to defer to you in case you had a preference.

Could you provide two options / recommendations for photos by the end of the week (May 20)?

**Comment by carolinestj** [comment]
@duffy-james Yup feel free to add any photos you think would work, no preference from me!
