### ISSUE TITLE
Logo URL

### ISSUE THREAD

**Issue by LindaBAIS** [CityOfBoston/design-team-workflow#2267]
Could you please send me the Logo URL that I can use within iCIMS.

**Comment by carolinestj** [comment]
@LindaBAIS Hi I need more context, what is this ticket for?

**Comment by LindaBAIS** [comment]
It's for branding within iCIMS.

**Comment by LindaBAIS** [comment]
Any update on this @carolinestj? I need this soon to complete the project I am working on.

**Comment by carolinestj** [comment]
@LindaBAIS Hi Linda, I need more context for what this project is about? What branding do you need and for what?

**Comment by LindaBAIS** [comment]
It is for a login page for internal employees. All I need is a URL provided
that links to the standard B logo. I am not in need of any other assistance.

Best, Linda

<http://goog_590114115>
<https://www.boston.gov/>
 Linda Monteiro
 Department of Innovation & Technology (DoIT)
 One City Hall Plaza
 Boston, MA 02201
 ***@***.***
 617.961.1063

*"We cannot solve a problem by using the same kind of thinking we used when
we created them.' ~ Albert Einstein*
