### ISSUE TITLE
Pick primary color and secondary colors for the Park Boston app

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#2268]
In the attached example, you can see what it looks like for the City of Des Moines. Blue color is their primary color and the green color (only reflected on sign in page) is the secondary.

We need to specify what the primary and secondary color of the app should be. We also need to make sure the secondary color is accessible.

We have a meeting with them tomorrow (May 18) in the afternoon -- could you provide recommendations for us ahead of that meeting?

[Des Moines Example.zip](https://github.com/CityOfBoston/creative-team-workflow/files/8708602/Des.Moines.Example.zip)

**Comment by duffy-james** [comment]
@carolinestj BTD already shared the brand guidelines with the vendor, but I definitely want us to provide input on what the best color scheme would be to use, especially as it relates to accessibility.

**Comment by carolinestj** [comment]
My suggestions:

PRIMARY COLOR

OPTIMISTIC BLUE
HEX: #288BE4
PANTONE: 2174C
RGB:40,139,228

SECONDARY COLOR

FREEDOM TRAIL RED DARK
HEX: D22E23
PANTONE: 485 C
RGB: 210, 46, 35
