### ISSUE TITLE
RGB color codes (web) and CMYK color codes (print) for City of Boston branding

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#2269]
- [x] Share RGB color codes for the ParkBoston website
- [x] Share CMYK color codes for print

@carolinestj BTD already shared the brand guidelines, so I think we want to prioritize this. Hopefully we can avoid them just picking a few random colors from our template.

We have a meeting with them tomorrow (May 18) in the afternoon -- could you provide recommendations for us ahead of that meeting?

**Comment by carolinestj** [comment]
My suggestions: 

**PRIMARY COLOR** 

OPTIMISTIC BLUE
HEX: #288BE4
PANTONE: 2174C
RGB:40,139,228

**SECONDARY COLOR** 

FREEDOM TRAIL RED DARK
HEX: D22E23
PANTONE: 485 C
RGB: 210, 46, 35
