### ISSUE TITLE
Preservation Month

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#227]
We are trying to come up with a logo for Preservation Month in May We are thinking of a triptych of 3 logos; the Landmarks, the archaeology logo with shovel and trowel and then the image of City Hall that's on the Hub Login page- 

 The phrase we are thinking of- May is Preservation Month- Celebrate Boston
We like the idea of the red underlining each of the images. Excited to see what you come up with.

Best,
Kathleen

**Comment by carolinestj** [comment]
wants icons or imagery that embodies landmarks. Important that archeology is included as well as show that they are not just old buildings but modern and contemporary as well.

The image will go on social media and other digital collateral like facebook and emails.

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=0B0RwQU94BhGeWHNmZmZQOW9seDg

**Comment by carolinestj** [comment]
https://docs.google.com/a/boston.gov/document/d/11XKZU90B4AMUaxx8lZv3xWv1hlN5YrRuj5WssE0L9Fw/edit?usp=sharing

Bookmark copy
