### ISSUE TITLE
B notecards and bookmarks - how to fix URL to be able to use?

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#228]
All B bookmarks and notecards have pilot.boston.gov listed as URL.

Since we still have a lot of both bookmarks and notecards it would be nice to use them until we run out. Is there a way we can cover or convert them so that we don't have pilot.boston.gov showing?

**Comment by sebastianebarb** [comment]
Merging with #604

**Comment by carolinestj** [comment]
Staples will print for you if you provide paper

**Comment by carolinestj** [comment]
https://docs.google.com/document/d/1lRJfe0vjm2KbV3PUcxdphzfGIqm6S39cOBFpGrx6_ts/edit?usp=sharing
