### ISSUE TITLE
Decals for Trash Cans and Recycling bins

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#232]
- The stickers will be 18" x 24".

- Similar to our wifi project, young people voted to fund 80 trash cans and recycling bins in Dorchester, Roxbury, and Mattapan. Public Works is installing them and would like have decals to denote that they're funded by Youth Lead the Change.

When you get a chance, can you design something similar to the wifi poster you did for us? Instead of "Powered by...", young people would like it to say "Keeping it clean thanks to...". They would also like to incorporate the following message (inspired by this wholesome meme):

ANYONE CAN BE GREAT. THAT’S WHY I’M A “GARBAGE CAN”, NOT A “GARBAGE CANNOT”.

This isn't high priority, but it would be great to have it within two weeks. Let me know if this is possible.

**Comment by carolinestj** [comment]
size: 18" x 24".
