### ISSUE TITLE
leaf schedule Senior Mag

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#233]
I just wanted to confirm to you that we will be putting in the winter weather brochure (2 pages).  Sebastian (cc'd) is just waiting for the final approval from the departments and it should be signed off on by tomorrow or Friday the latest.  

Thanks for your help on this, I think we can all agree that this is a great avenue to get this information out to one of Boston's most vulnerable populations.

**Comment by carolinestj** [comment]
[2017 Yard Waste  Calendar Website.pdf](https://github.com/CityOfBoston/design-team-workflow/files/845590/2017.Yard.Waste.Calendar.Website.pdf)

**Comment by carolinestj** [comment]
![2017 yard waste calendar2](https://cloud.githubusercontent.com/assets/22770827/24928152/5cb27b30-1ecf-11e7-8e6b-358a791dff28.png)
