### ISSUE TITLE
Request for icon: leave buy back tile - InFlight/ESS

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#240]
Request for icon for main employee self service dashboard seen at ESS.boston.gov

Logo for "Leave Buy Back" - certain employees can purchase back sick or vacation time

Perspective with surrounding tiles: 
![img_6036](https://cloud.githubusercontent.com/assets/20731897/23815464/5bec7264-05b6-11e7-929c-9345dcdd8f45.PNG)

**Comment by sebastianebarb** [comment]
![experiential icons leave buy back](https://cloud.githubusercontent.com/assets/20642299/23861420/5dca0f70-07e0-11e7-9ba1-0033c8633112.png)
