### ISSUE TITLE
Neighborhood Career Fair Flyer

### ISSUE THREAD

**Issue by taniadelrio** [CityOfBoston/design-team-workflow#242]
Hi! I am attaching a first attempt at a flyer for an event we are holding on May 1. The event is a Career Fair to be held at the Bolling Building on May 1. 

If possible, we would love some help with the design. We are looking to receive a file to which we can still add additional logos as we are still adding participating employers. 

Thanks a lot for your help!

Tania (Diversity Office).

![copy of now hiring 8](https://cloud.githubusercontent.com/assets/26231957/23872233/da07c154-0803-11e7-91ce-d52a6b21daf6.jpg)

**Comment by sebastianebarb** [comment]
@taniadelrio i have a few questions. When would you like the flyer done by? It looks like you set the dimensions to 11"x17" is the the correct size?  What did you build this in originally?

**Comment by taniadelrio** [comment]
Hi Sebastian!
Thank you for your help with this! I originally did this on a site called Poster My Wall (before I was aware that you guys could help us!). I am not married to this design or anything, we just need the info to be displayed in a friendly way. We are going to print both posters of this and postcards, so those dimensions seem fine to me. 

We also need to add the Water & Sewer Commission and the Boston Public Health Commission to the list of participating departments. We need to have a flyer by the end of next week.

**Comment by sebastianebarb** [comment]
Thanks @taniadelrio we will start working on it. @carolinestj can put it in Canva.com so you can edit it later if needed.

**Comment by taniadelrio** [comment]
Sounds great! Thanks guys!
