### ISSUE TITLE
Comp request: Summary Budget graphs

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/design-team-workflow#245]
Screenshots below.

Ask: Please create Boston.gov styled graphs of the following screenshots. Please keep the same information as on each screenshot, but styled similarly to how the current budget graphs were styled (ref #179 and #221 to see what you've done already).

Sizing: please no smaller than 250w x 300h and no larger than 350w x 425h. Ideal size is ~300w x 400h, but please keep consistency with #179 and #221 as far as standards.

Possible to get by Weds, March 22nd?

@sebastianebarb let me know if you have any questions or need clarification. Otherwise, looking forward to more great work!

![expenditures-trends](https://cloud.githubusercontent.com/assets/3886936/23962753/7f4cb3a4-0985-11e7-8c9a-d73373725184.PNG)

![recurring-revenue-trends](https://cloud.githubusercontent.com/assets/3886936/23963002/49a8ae3c-0986-11e7-959a-ce8f25754578.PNG)

![employee-health-insurance-share](https://cloud.githubusercontent.com/assets/3886936/23962754/7f4ce0c2-0985-11e7-8135-bc663906449c.PNG)

![charter-school-enrollment](https://cloud.githubusercontent.com/assets/3886936/23962755/7f4dc9ba-0985-11e7-9ada-f883d08dff02.PNG)

![change-in-net-state-aid](https://cloud.githubusercontent.com/assets/3886936/23962750/7f4bdb64-0985-11e7-8b11-d7fed1206fd2.PNG)

![sources-of-property-tax-growth](https://cloud.githubusercontent.com/assets/3886936/23962751/7f4bd3e4-0985-11e7-9309-e07c891d7935.PNG)

**Comment by sebastianebarb** [comment]
Thursday is best

**Comment by hackajesse** [comment]
@sebastianebarb use this PDF
[Copy of FY17 Employee Share Charts and Calculation - FY17 Tiered Chart.pdf](https://github.com/CityOfBoston/design-team-workflow/files/868276/Copy.of.FY17.Employee.Share.Charts.and.Calculation.-.FY17.Tiered.Chart.pdf)
 for the FY17 Estimated share of employee health care costs.

Working on getting a pdf of the others.

Also no need to do "Recurring Revenue" and "Expenditures" graphs any longer. Please disregard.

**Comment by hackajesse** [comment]
@sebastianebarb updated versions from an exported PDF:

[figure-5-charter-schools-boston.pdf](https://github.com/CityOfBoston/design-team-workflow/files/876095/figure-5-charter-schools-boston.pdf)
[figure-4-change-net-state-aid.pdf](https://github.com/CityOfBoston/design-team-workflow/files/876096/figure-4-change-net-state-aid.pdf)
[Figure-3-property-tax-growth.pdf](https://github.com/CityOfBoston/design-team-workflow/files/876097/Figure-3-property-tax-growth.pdf)
