### ISSUE TITLE
Comp request: table for budget

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/design-team-workflow#246]
Request mockup for Jim of a budget table. Requested due date Friday 3/24. Please confirm.

Requirements per discussion w/Seb and Hondo the other day:

- Header should be dark background
- Header columns w/numbers in them should be equal width
- Header copy in all columns should wrap if it doesn't fit in the set width of the column (primarily for columns with numbers in them)
- No column lines
- Rows are alternately shaded (what color should the shade be?)
- No row lines
- Columns with numbers should be justified right
- Columns with copy in them should be justified left
- Final row should read "Totals" and be dark background
- Totals row should have the word "Totals" indented from the normal left justified state

@sebastianebarb here is [some example data](https://docs.google.com/spreadsheets/d/14nge-i2uFYr97isxdtKV9s_tILcUdLm3jEYYHqUxcz4/edit#gid=0)

**Comment by sebastianebarb** [comment]
![capital](https://cloud.githubusercontent.com/assets/20642299/24214465/f96247b8-0f0b-11e7-98a4-468279972f02.png)
