### ISSUE TITLE
Coordinating IB2030 categories with Budget Office

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#255]
Categories and descriptions below.  above line need something different

- (farmer's market shot?) Health:  Initiatives to increase access to quality healthcare and improve public health.
https://photos.google.com/u/1/album/AF1QipMttrRTCgPYnsKvvydVZ5vPNVP2t_hIliJCiPhF/photo/AF1QipMGhgvoXiFQbe1dklwnO7ibCxx1WcFNEjBb5V9l

- (kids, but not looking at the camera?) Education:  Initiatives to strengthen e ducation, job training, and career connections.

- (small biz of some kind) Economy:  Initiatives to improve economic mobility and strengthen Boston’s core and emerging industries and small businesses.

- (they forgot this one) Open Space:  Initiatives to strengthen our existing park system and invest in new open spaces.

- (Need something cars, busses, bikes, walking ideally)Transportation:  Initiatives to support an accessible multimodal transportation system that gets Bostonians where they need to go reliably and safely.

--------------------------------------------------------------------------------------------------------------

Housing:  Initiatives to encourage housing production, increase affordable housing options, and reduce displacement.

Energy and Environment:  Initiatives to support a healthy environment, reduce energy consumption and greenhouse gas emissions, and prepare for climate change.

Technology:  Initiatives to make Boston’s infrastructure and services dynamic and responsive to residents' needs in realtime.

Arts and Culture:  Initiatives to support a thriving, diverse arts and culture ecosystem throughout the city.

**Comment by sebastianebarb** [comment]
@hackajesse Links below title

- Health: 
https://goo.gl/photos/b3SwUSfxoqF97drPA
https://goo.gl/photos/U3qM3S1YFBLGchnv8
https://goo.gl/photos/yDLATrvfVyxLpbz16
https://goo.gl/photos/B418MfBGfCm1bPnk7

- Education:  
https://goo.gl/photos/mDYjtaJ1t7RG1ebw7
https://goo.gl/photos/nTVk3wN1cpipXuiv8

- Economy:  
https://goo.gl/photos/rA6y5yPrGJ321iqQ9
https://goo.gl/photos/Mm5Leg8CbhXmfXDu6
https://goo.gl/photos/i5k9omyusZvUcRaZ6
https://goo.gl/photos/xoBSEQzNGVgXkrYc7

- Open Space:  
https://goo.gl/photos/x1kk2AFYYpXgVyru9
https://goo.gl/photos/67yrf4rETK7T6HGM9
https://goo.gl/photos/KQbNA4r39xFm6fcX7
https://goo.gl/photos/3Bm6dku2WSRmZKPLA

- Government:
https://goo.gl/photos/akfHBYdB1uacciXy9
https://goo.gl/photos/16b3k8YrAh46FJVbA
https://goo.gl/photos/tCHWuJf3zFVUo6EVA

- Transportation:  
https://goo.gl/photos/M2KrJVEqAW6mSgeU9
https://goo.gl/photos/wZb4p8XghfHvEhW46
https://goo.gl/photos/FKXbhfDuHjLhsnjWA
https://goo.gl/photos/ybWmgJfLE8bMtiUe6

**Comment by hackajesse** [comment]
@sebastianebarb 
Transportation - These were ok. Do you have anything with biking along the Charles, Neponset?
Government - something with people interacting with the govt asset we built? Not just the asset itself.
Open space - we'll use Jackie's fall foliage
Economy - Do we have permission to use the food truck one (e.g. from Clover)? Dandelions is a good one, too.
Education -https://photos.google.com/share/AF1QipOvgZWBRZZKfdLAHaRoofdosJ8MvGIkAJOgyhoJLdmeM3M636v0eldzNGIv8TRg_g?key=R1JQQkVpakNFa2JJRTVjYzNHbG9uM2s4ZjhhbnNn
Health -  https://photos.google.com/share/AF1QipMkBkWQksGywE7txtazyIja0qAIDTj8ogwojb9wkmOfLBEcDS-E1EM7921uoIJzuA?key=Q3lLS3ZhaW0tcHNIMU9HRFU0Z0VCVHgyTHpKUUNn

**Comment by sebastianebarb** [comment]
https://goo.gl/photos/s2kKcc4cugrwgSer7
