### ISSUE TITLE
Career Fair Brochure, Spanish

### ISSUE THREAD

**Issue by taniadelrio** [CityOfBoston/design-team-workflow#256]
Hi We need the Spanish version of this flyer. The design Caroline did is on this Canva link (we are still using it so don't delete!):

[](https://www.canva.com/design/DACP38X_DXQ/1KkkM40N1VWQnxoMSiCdjw/edit)

Here is the Spanish text:

_La Oficina del Alcalde Martin J. Walsh le da la bienvenida a:

Ferias del Empleo

Cuándo: Lunes 1 de mayo, 5:30-8:30 PM
Dónde: Bruce C Bolling Building, 2300 Washington Street, Roxbury 02119

¡Conozca empresas en Boston y obtenga información sobre trabajo en la Alcaldía!

Entidades participantes:_

Thanks so much!

Tania

**Comment by sebastianebarb** [comment]
Thanks @taniadelrio we will get on it.  When do you need it by?

**Comment by taniadelrio** [comment]
Ideally before this Friday

**Comment by carolinestj** [comment]
@taniadelrio I've updated the canva template with an editable version (scroll down) where you can edit the text and add the spanish! Let me know if you need any help.

**Comment by taniadelrio** [comment]
Thank you! Very helpful
