### ISSUE TITLE
Revise footer for websites

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#258]
We should start thinking about how we can rework the websites footers/make them more useful and/or maybe more robust. Let's brainstorm ideas from funky to practical. 

Ideally, we'd rethink/potentially re-do footer this summer/early fall.

**Comment by reillyzlab** [comment]
Canva footer: Although they are thinking 'contributor' in a slightly different way than we are for boston.gov I like how they specifically call out that they are looking for help. Think it could be interesting for us to consider doing a call out like this on boston.gov to see if we can get the public to contribute more on github/to our projects:

![screen shot 2017-03-04 at 1 50 28 pm 1](https://cloud.githubusercontent.com/assets/20731897/24167002/95452752-0e4b-11e7-977f-f1a80a2cde96.png)

**Comment by sebastianebarb** [comment]
http://www.creativebloq.com/web-design/website-footers-1131597
![screenshot 2017-03-24 16 50 55](https://cloud.githubusercontent.com/assets/20642299/24313328/bfdbcc28-10b2-11e7-9e32-7c223cbb8f2e.png)
![screenshot 2017-03-24 16 53 33](https://cloud.githubusercontent.com/assets/20642299/24313326/bfd9a542-10b2-11e7-94c2-b3cdfe655764.png)
![screenshot 2017-03-24 16 53 47](https://cloud.githubusercontent.com/assets/20642299/24313327/bfdb395c-10b2-11e7-95a3-ebb42258c533.png)

**Comment by reillyzlab** [comment]
nebraska.gov

Like that they call out 'most visited' pages and that they include promo about the awards that the site has won

![nebrasksa gov footer](https://cloud.githubusercontent.com/assets/20731897/24664262/3616c852-1928-11e7-95f5-ee7fe7ecfa7b.PNG)

**Comment by reillyzlab** [comment]
Let's be sure to include a way to access city of boston social accounts and/or landing page with all city social accounts - @collinmgately if you could advise here and/or have good examples would be great to get your input

**Comment by reillyzlab** [comment]
Potentially add RSS feed info in here

**Comment by reillyzlab** [comment]
Link to open data portal?

**Comment by reillyzlab** [comment]
Definitely need to add:

Terms of use (Josh can provide you accurate link)
Site Feedback: Links to feedback modal


All the links causing wrapping on large screens now, can we just move to a vertical layout?

**Comment by sebastianebarb** [comment]
![boston gov updated footer](https://user-images.githubusercontent.com/20642299/31562436-706c1136-b029-11e7-8bb9-a3e2fae4a181.png)
