### ISSUE TITLE
Additional design work for 'no results'

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#260]
Sebastian initially created design for 'no results' pages in Drupal for at the very least /events, /public-notices and /news but realizing we need to consider how the no results shows for pages that have in page search. Can you take a look at that and provide designs?

Not needed immediately - putting in your que as a nice to have when you have time.

Few examples:

https://www.boston.gov/pay-and-apply

https://www.boston.gov/guides

See ticket for reference: https://github.com/CityOfBoston/boston.gov/issues/10

**Comment by sebastianebarb** [comment]
@reillyzlab all not found messages should be accompanied by a new search field, text, and popular hits for the category. 
![guides not found](https://cloud.githubusercontent.com/assets/20642299/26248885/0c916182-3c72-11e7-868f-4dacbd69d371.png)

![pay and apply not found](https://cloud.githubusercontent.com/assets/20642299/26248827/e2d69b8c-3c71-11e7-865d-24d185c1f5fe.png)
