### ISSUE TITLE
Need a style for in page error blocks

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/design-team-workflow#262]
In the event that one of our integrations fails, it would be nice to be able to show an error message in place. Can you come up with a style for this? Am attaching a screenshot of a starting point. The block should have a title and room for body copy.

<img width="1555" alt="screen shot 2017-03-24 at 8 58 48 am" src="https://cloud.githubusercontent.com/assets/9234/24295262/3f718b32-1070-11e7-9996-f3a5f06281f6.png">

**Comment by sebastianebarb** [comment]
![in page error blocks](https://cloud.githubusercontent.com/assets/20642299/26222357/af275482-3be7-11e7-9827-3663d0a77db5.png)
