### ISSUE TITLE
Adding another logo to this Career Fair flyer

### ISSUE THREAD

**Issue by taniadelrio** [CityOfBoston/design-team-workflow#263]
Hi Team!

Sorry to do this (again) but the Diversity Office logo is not on here! OOPS Could we have it added?

https://www.canva.com/design/DACP38X_DXQ/1KkkM40N1VWQnxoMSiCdjw/edit

THANKS!!!

Tania

**Comment by carolinestj** [comment]
@taniadelrio Hi! The logo should be added now!

**Comment by taniadelrio** [comment]
Thanks Caroline! looks great.
Tania
