### ISSUE TITLE
Request: Budget social graphic templates - April 5

### ISSUE THREAD

**Issue by collinmgately** [CityOfBoston/design-team-workflow#266]
Budget team has asked us to put together some social media graphics. 

Sebastian/Caroline - could we get a template in Canva for FB and Tw dimensions that I can drop budget toplines into when their team gets that info to us?

Let me know if I did this the wrong way or if it's already in the works.

thanks!

**Comment by hackajesse** [comment]
Here's an example @collinmgately @sebastianebarb of what Budget will be looking for.
https://twitter.com/marty_walsh/status/844658644125995009

**Comment by carolinestj** [comment]
@collinmgately 
Twitter: https://www.canva.com/design/DACQ_ix0hw0/share?role=EDITOR&token=CZMs014Gvns_y-ltUuRTgQ&utm_content=DACQ_ix0hw0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

Facebook: https://www.canva.com/design/DACQ_njSIjM/share?role=EDITOR&token=PiTkgjTCnnjbx54K2hM84Q&utm_content=DACQ_njSIjM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton
