### ISSUE TITLE
CodeRed / Emergency Alerts Signup form mockup

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/design-team-workflow#270]
Different than Email #261 

We also need to design a signup for emergency alerts. This should be a full-width component. It should have three these fields:

Single field entry - Email Address
Single field entry - Phone number
- Check box - Call me / Send me text messages 
- If they click yes on text: Dropdown - Cell phone service provider 

(one of these has to be filled out)

Optional fields:

Single field entry - First name
Single field entry - Zip Code
Dropdown - What language would you like to receive your alerts in
Options - English, Spanish, French and Cantonese Chinese

Please put together two mobile mock-ups. 

1. Mockup one -- all fields open with data in them. 
2. Mockup two -- Information submitted

**Comment by joshuagee** [comment]
Made updates

**Comment by sebastianebarb** [comment]
![signup w text zip copy 2](https://cloud.githubusercontent.com/assets/20642299/24804674/323b449a-1b7d-11e7-842b-f9d3f96103fc.png)
![signup w text zip copy 3](https://cloud.githubusercontent.com/assets/20642299/24804675/32424c68-1b7d-11e7-88fa-b46f253721c1.png)
![signup w text zip copy 4](https://cloud.githubusercontent.com/assets/20642299/24804676/3242792c-1b7d-11e7-874a-3a5ed38e9bd4.png)

**Comment by joshuagee** [comment]
Two edits now that I'm reviewing it again. 

1. "Call me" or "text me" should be different check box options. Maybe stack them?

2. Need "last name" field as well.

**Comment by joshuagee** [comment]
@sebastianebarb Can you make those updates? Maybe just to the one that has all fields open?

**Comment by sebastianebarb** [comment]
@joshuagee Updated here:
![signup w text zip copy 2](https://cloud.githubusercontent.com/assets/20642299/24923023/3d239116-1ebe-11e7-8907-a051310b9f52.png)
![signup w text zip copy 3](https://cloud.githubusercontent.com/assets/20642299/24923026/3d32fcc8-1ebe-11e7-9717-828c9606272e.png)
![signup w text zip copy 4](https://cloud.githubusercontent.com/assets/20642299/24923025/3d2b8704-1ebe-11e7-997a-cce3e915451a.png)

**Comment by joshuagee** [comment]
The smallest nitpick -- move the check mark to "text me" instead of "call me" change "send feedback" on button to "submit"

**Comment by joshuagee** [comment]
I also just learned that I don't need to ask the question about their cell phone provider, so can you cut that question? Just the check box between "call me" or "text me"

**Comment by sebastianebarb** [comment]
![signup w text zip copy 2](https://cloud.githubusercontent.com/assets/20642299/25136231/6654e1e8-2422-11e7-9132-cb088ac4ee96.png)
![signup w text zip copy 3](https://cloud.githubusercontent.com/assets/20642299/25136232/66578592-2422-11e7-8a63-28fcf29ea938.png)
![signup w text zip copy 4](https://cloud.githubusercontent.com/assets/20642299/25136233/66594ddc-2422-11e7-9014-573d5508cd35.png)
@joshuagee happy to make more changes
