### ISSUE TITLE
Budget graph request - big pie chart

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/design-team-workflow#273]
Request for a decently sized pie chart of the below PDF. This is mean to be the only major highlighted graph on the operating budget landing page. Will appear next to a block of text in a full-width text component. 

Requirements:
 - The order of the slices shouldn't change.
 - The bracket on the right should still exist, but look better.
 - Definitely put identifying copy on the graph, but no obligation to have it placed the same as in the PDF below. Put them anywhere that makes sense.
 - Keep all percentages visible
 - Add title anywhere that looks good. Use copy: "FY18 Recommended Expenditures"

[FY18 Recommended Expenditure Pie.pdf](https://github.com/CityOfBoston/design-team-workflow/files/891229/FY18.Recom.Expenditure.Pie.1.pdf)

**Comment by sebastianebarb** [comment]
@hackajesse what size do you need it?

**Comment by sebastianebarb** [comment]
![fy18 recom expenditure pie 1-01](https://cloud.githubusercontent.com/assets/20642299/24723121/3a4ca210-1a14-11e7-8fe4-cbc2f1a668c8.png)
