### ISSUE TITLE
GDUSA award submission

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#285]
http://gdusa.com/competitions/enter-now/enter-the-2017-american-inhouse-design-awards

**Comment by sebastianebarb** [comment]
![city fo boston icons-01](https://cloud.githubusercontent.com/assets/20642299/24937409/946a8e08-1efe-11e7-9995-174d3dc90eee.png)
![city fo boston icons-02](https://cloud.githubusercontent.com/assets/20642299/24937411/94766e1c-1efe-11e7-8703-876064104e72.png)
![city fo boston icons-03](https://cloud.githubusercontent.com/assets/20642299/24937410/9471fba2-1efe-11e7-9deb-b413494fd64f.png)

**Comment by sebastianebarb** [comment]
@carolinestj please add image here

**Comment by carolinestj** [comment]
![mockup2](https://cloud.githubusercontent.com/assets/22770827/24958978/37961ca4-1f5f-11e7-9310-d55cf503515f.png)

**Comment by sebastianebarb** [comment]
@jduffy2001 Above you will find 2 submissions for http://gdusa.com/news/top-stories/enter-the-2017-american-inhouse-design-awards
- the first should be entered under 15. Logos + Symbols
- The second should be entered under 23. Public Service + Pro Bono Projects
