### ISSUE TITLE
311 ticket: Design for translation(s) screen

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#293]
We'd like to incorporate a way to support non-English as first language speakers on 311.

Thoughts are that we'd keep 'translate' in header (no currently on 311) and then:

Ideally, someone would click the word 'translate', select the language that they're hoping for support, and a screen would pop up in that language with instructions on how to contact 311 for help.

Help with design of what this looks like would be helpful. Doesn't need to be super complicated - maybe even something as simple as language towards bottom of search.boston.gov.

Language will be something like:

If you are in need to report a non-emergency issue with the City of Boston, please call BOS:311 at 311 or 617-635-4500.

Reilly will get translations needed for the different languages we support on boston.gov but are not needed for designs.

**Comment by sebastianebarb** [comment]
![311 translate](https://cloud.githubusercontent.com/assets/20642299/25240882/196c5e50-25c2-11e7-8bab-6c04f54c425c.png)
thoughts?

**Comment by reillyzlab** [comment]
I like this!

@jduffy2001 can you look at this text and advise on alternate language or if you think it's okay?

**Comment by duffy-james** [comment]
You don't really need "are in":

"If you need to report a non-emergency issue with the City, please call BOS:311 at 311 or 617-635-3500."

Alternatively, you could do a question and answer format:

"Need to report a non-emergency issue with the City? Please call BOS:311 at 311 or 617-635-3500."
