### ISSUE TITLE
Mapbox - City of Boston Color Pallette

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#296]
@sebastianebarb can you reach out to Loosine and see if see can provide you with the City of Boston color pallette she put together for the snow map?

**Comment by reillyzlab** [comment]
Sebastian reached out to Loosine on 4/10/17 to see if we can get this.

**Comment by carolinestj** [comment]
@reillyzlab here are the additional colors!  

![colors-01](https://cloud.githubusercontent.com/assets/22770827/25135664/fc13098c-2420-11e7-8015-8bf5360d4954.png)

**Comment by sebastianebarb** [comment]
Closing and adding to #304
