### ISSUE TITLE
311: Combining 311 on the go and FAQ (desktop and mobile)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#297]
During UI review, we discussed combining FAQ and 311 on the go page.

@sebastianebarb can you provide updated comps with these two pages combined - including both desktop and mobile comps

https://github.com/CityOfBoston/311/issues/186

**Comment by sebastianebarb** [comment]
![480-combining on the go and faq mobile](https://cloud.githubusercontent.com/assets/20642299/24975670/8021b71e-1f94-11e7-9c7d-99fdbf0c4c03.png)
![311 on the go](https://cloud.githubusercontent.com/assets/20642299/24975684/8822f9be-1f94-11e7-94d9-1889ee066633.png)

**Comment by sebastianebarb** [comment]
[311 on-the-go icons.zip](https://github.com/CityOfBoston/design-team-workflow/files/929897/311.on-the-go.icons.zip)
