### ISSUE TITLE
311: Use browser location for picker default

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#298]
https://github.com/CityOfBoston/311/issues/41

- Also show the current browser location as its own dot. Needs design for indicating this.

- update waypoints

**Comment by reillyzlab** [comment]
Think we'll want something similar for map for food trucks - think we can probably re-use

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=0B0RwQU94BhGeMER6MGUtWWRwQVU
