### ISSUE TITLE
Pdf icon question

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#301]
Good Afternoon Sebastian, 

I hope this email finds you well. I am currently working on a program page with the Boston Home Center involving their Maximum Resale Price program. They currently have an pdf that they would like for constituents to have available in the side bar. 

Could we have a "Document" icon include in the sidebar similar to Form icon for the Metrolist? If so, could it look like a paper with scribbled lines on it, mimicking text?

**Comment by sebastianebarb** [comment]
![small-circle-icons-document](https://cloud.githubusercontent.com/assets/20642299/25148111/be8c2dec-2447-11e7-800a-67a991edc3bb.png)

**Comment by reillyzlab** [comment]
Doesn't match the styling of other sidebar component icons:

![look of sidebar](https://cloud.githubusercontent.com/assets/20731897/25674819/418d06e4-300a-11e7-9dd4-c8db22bbead9.PNG)

Please update/re-export
