### ISSUE TITLE
Death 💀 Certs to do

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#302]
Mobile comments 
- [x] add advanced search to mobile.

A way for the user to open and close advanced search fields, which lets them search plaint text fields for first name and last name.  Then allow them to enter ranges for birth date, death date, and age at death.

- [x] Change search results list

Only display full name, birth date, death date, and some indication if cause of death is pending or not. Remove box to add.  

- [x] crate product details page to results list. 

On clicking a search result, this opens a new page (or possible expands the search results) and displays first name, last name, birthday, death date, age at death, ID number, and if the cause of death is pending or not. Details page also needs a way to go back to search results and a way to add X number of records to your cart. 

- [x] Change Cart page

Remove "keep shopping" button. Move total cost language and "pay and finish" to the bottom. Show "total cost" of $14 per record and display 2.95% credit card fee. 

- [x] Change checkout

Start with shipping address. Default to billing address being the same as shipping with a check box to say "billing address is different than shipping" (@joshuagee and I reshaped this, billing is first)

**Comment by joshuagee** [comment]
Updated above. Please load new screens into invision. Please also upload different versions of all the actions (i.e. billing address is same checked and unchecked).

**Comment by reillyzlab** [comment]
Just looked through DESKTOP designs to glance thru, take or leave following: 

- Overall was great. 

- These felt a little off to me: 

1. On cart drop down: 'Go to cart to view all selections' seems a little odd because entire list of selections is already showing

2. The drop down of the cart says 'total' but then total will be more due to fees and shipping so does this actually need to be 'subtotal' rather than total because more fees will be added? 

3. Seems a little funny to add "review before you submit" right next to the submit and pay button. Could you just make the button review and submit instead?

**Comment by sebastianebarb** [comment]
@joshuagee combining ticket #140 with this one.

**Comment by sebastianebarb** [comment]
@finneganh - feedback May 19th

- I think for the certificate page, have a link back to search rather than a big button. 
- Also, wondering about cribbing Amazon mobile’s UI for carts: a “Quantity” dropdown, and a big “Add to Cart” button.
-As it stands the “add certificates to cart” UI seems confusing.
- Quantity text box might be better on desktop, drop down on mobile
- I’m also interested in the experience right after you press “Add to Cart”. Should have some confirm feeling, and probably immediate access to changing / removing / checking out.
- I think we’ll also need pagination controls on the search results. But TBD whether that’s next / previous or if we’ll be able to jump to a page

**Comment by sebastianebarb** [comment]
Desktop notes:
- Re work search to look like mobile
   - Filters?
- still working on notes

Mobile notes:
- number selector on details page

**Comment by sebastianebarb** [comment]
Comments from @finneganh:
Most death certs do not have a date of birth, just an age. For newer certs, we have date of birth, which would let us calculate age at death.

[8:51] 
I think that it’s not necessary to say “cause of death: known” in the list view. We could say something if cause of death is pending.

[8:52] 
I also don’t understand why the rows have a “Search” button next to them.
