### ISSUE TITLE
Request for OCR scan of document

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#318]
Could you output and OCR scanned version of this document? Sorry to keep bothering you for these requests. I just sent an email asking for access to Adobe Acrobat Pro.

[PhaseC_approval_letter_4.24.17 (1).pdf](https://github.com/CityOfBoston/design-team-workflow/files/954986/PhaseC_approval_letter_4.24.17.1.pdf)

**Comment by sebastianebarb** [comment]
[PhaseC_approval_letter_4.24.17.1.pdf](https://github.com/CityOfBoston/design-team-workflow/files/955092/PhaseC_approval_letter_4.24.17.1.pdf)
