### ISSUE TITLE
Swap out images for presentation template

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#320]

**Comment by carolinestj** [comment]
Master city of boston slide deck: https://docs.google.com/presentation/d/1wbaK7UNyMpA-FAH9gQNB-cg4LzPhsqxnLXYKcRyOOxY/edit#slide=id.g1020bb9de2_1_1

doit slide deck: https://docs.google.com/presentation/d/1DqKCYGRBytWGvg-FzJihl4TExFxK_1g4pp2Fm826svQ/edit#slide=id.g1020bb9de2_1_25
