### ISSUE TITLE
311: Designs for Live Chat Testing

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#321]
We should draft up at least two variations to test live chat functionality.

Both should be a replacement of the feedback modal - i.e. click feedback or similar words like 'get help' and screen appears much like feedback modal would.

One draft simply opens up the 'live chat' screen

Second draft exposes list of 'helpful items', such as top five 311 services, list of departments (or similar ideas from Sarah's research), and link to live chat

Ideally we'd have by 4/28 but we can be negotiable

**Comment by sebastianebarb** [comment]
![311 live chat](https://cloud.githubusercontent.com/assets/20642299/26014556/118b156c-372b-11e7-88e5-b7fc497d7331.png)
![311 live chat 2](https://cloud.githubusercontent.com/assets/20642299/26014557/119f7804-372b-11e7-8ec5-9e4301084d30.png)
