### ISSUE TITLE
Brand guidelines update

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#328]
- Legal language around Brand
- Photo shoot Legal language
- 
- Add pronoun info
- survey monkey

**Comment by sebastianebarb** [comment]
"The City of Boston brand belongs to the citizens of Boston. Our brand guidelines and assets are open and free to use for the public. However, this does not include commercial or political uses without the express permission of the City's Head Designer, Chief Digital Officer, or Legal Department. If you have questions, please contact the City's Digital Team."

**Comment by duffy-james** [comment]
Edited this, but we still need to confirm with legal what to do.

**Comment by sebastianebarb** [comment]
Text for survay monkey https://docs.google.com/a/boston.gov/document/d/1C6guD5Fw9cfGEzY4p_abaK8QihaRcsQn2Ix462ZuypI/edit?usp=sharing
