### ISSUE TITLE
Add the bottom piece of Hyde Park to Boston map

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#330]
Looks like we're cutting off a piece of the map at the bottom:
https://ww.boston.gov/sites/default/files/boston_outline_map-01_1.png

Here's an old map for a comparison:
https://www.cityofboston.gov/images_documents/Neighborhoods_tcm3-8205.pdf

**Comment by sebastianebarb** [comment]
map is here.
https://drive.google.com/open?id=0B0RwQU94BhGeMkljVk9qNzlodms

Sreen shot was taken from 
http://www.openstreetmap.org/#map=13/42.3361/-71.1069
