### ISSUE TITLE
Rethink Display of Employee Directory on Hub

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#339]
We removed the avatar images from the employee directory on the Hub because images weren't contributing anything meaningful.

Would like to rethink what employee directory display looks like moving forward, because there is much unneeded white space with adjustment.

**Comment by sebastianebarb** [comment]
We should make ID photos defalt into avatar images. but I know that would never fly
![screencapture-hub-boston-gov-my-profile-1495053159078](https://cloud.githubusercontent.com/assets/20642299/26174916/e7f5ec2a-3b1e-11e7-8d62-95a8420cb06b.png)
![screencapture-hub-boston-gov-employee-directory-1495053230640](https://cloud.githubusercontent.com/assets/20642299/26174939/fcf88b28-3b1e-11e7-8936-a184c8545362.png)
