### ISSUE TITLE
Greenovate custom jobs graphic 

### ISSUE THREAD

**Issue by collinmgately** [CityOfBoston/design-team-workflow#342]
My bad for not following up and submitting a ticket, but we talked about this last week a little. 

Could we get three custom jobs campaign social media graphics for Greenovate that say the following?

Now Hiring: Climate Saver
Now Hiring: Climate Fighter
Now Hiring: Climate Warrior

**Comment by sebastianebarb** [comment]
![greenovate employment brand social 12](https://cloud.githubusercontent.com/assets/20642299/26168104/f0e844c6-3b06-11e7-9146-6e395f506727.png)
![greenovate employment brand social 11](https://cloud.githubusercontent.com/assets/20642299/26168105/f0eea172-3b06-11e7-8163-4a6dc043d5fc.png)
![greenovate employment brand social 10](https://cloud.githubusercontent.com/assets/20642299/26168106/f0efc9a8-3b06-11e7-9b1a-18b92cbc0ee2.png)
@collinmgately they need these to be approved by Vivian in human resources beofre posting
