### ISSUE TITLE
Update broken Career Center social graphic 

### ISSUE THREAD

**Issue by collinmgately** [CityOfBoston/design-team-workflow#343]
This file is a little wonky: https://drive.google.com/a/boston.gov/file/d/0B0RwQU94BhGeQlk4R2lOZmhBcWc/view?usp=sharing

The line is too thin and the "C" in City of Boston is clipped.  Can you update?

**Comment by sebastianebarb** [comment]
https://drive.google.com/a/boston.gov/file/d/0B0RwQU94BhGeZWFOby1lVERWYzA/view?usp=sharing updated
