### ISSUE TITLE
Icons for new HCM ESS pages

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#346]
we talked a couple weeks ago about creating some icons for new pages on our ESS page.

It looks like the scope of my current project will include 4 new pages all relating to absence management.  For reference i included the three images that already appear on the ESS site for existing absence management pages.

the four new pages are:

Absence Request History - this page is for employees to view absence requests they made in the past

Manager Absence Request - this page is for managers to enter absence requests on behalf of their employees

Manager Absence Request History - this page is for managers to view absence requests their employee have made in the past

Manager Absence Balance - this page is for managers to view their employees absence balances

Please let me know what other information would be needed or helpful to create this content for us.

**Comment by sebastianebarb** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/20642299/26315691/eeea3e04-3edf-11e7-8902-8fa4a3189949.png)
