### ISSUE TITLE
Icon for Recovery Services department page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#354]
We need an icon for the Office of Recovery Services department page. The page will be based on information from here:

http://www.bphc.org/whatwedo/Recovery-Services/Pages/RecoveryServices.aspx

**Comment by sebastianebarb** [comment]
@jduffy2001 can you send these to whoever need to provided approval?

<img width="484" alt="recovery services 1 2x" src="https://cloud.githubusercontent.com/assets/20642299/26694698/4c4cb9de-46d6-11e7-9fcc-4175fb67a75b.png">
<img width="488" alt="recovery services 3 2x" src="https://cloud.githubusercontent.com/assets/20642299/26694700/4c518b12-46d6-11e7-876c-3d77c472455e.png">
<img width="485" alt="recovery services2 2x" src="https://cloud.githubusercontent.com/assets/20642299/26694699/4c4f3bfa-46d6-11e7-81e9-d6068bd773e2.png">
