### ISSUE TITLE
Decal for Lunch on the Lawn in July

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#359]
Hi Sebastian and Caroline,

During the first week of July, City Hall Plaza will become a Summer Meals site, offering meals for low-income BPS students. The program is tentatively called Lunch on the Lawn. It is a collaboration between Property Management & Operations, BPS, Food Initiatives, and New Urban Mechanics.

Jaclyn Youngblood from the New Urban Mechanics is the lead on this project. Chief Brophy put her in touch with me to make sure that the decal design for the large refrigerator they will be using is properly branded and complements the new decals we just finished for the lobby! It will be placed on the "lawn" at City Hall Plaza so we want to make sure it goes. At this point, the concept is very simple: dark blue background, Mayor's name, maybe the relevant department logos, maybe food icons, and the big B. We will use the same printer to keep things easy.

Would you be able to help me help them? If so, I will introduce you to Jaclyn and we can set some deadlines. 

Thanks for your consideration!

Best,
Renee Barouxis
Program Manager of Marketing and Communications for the City of Boston
Mayor’s Office of Tourism, Sports, and Entertainment
617.635.4137 (w)

**Comment by carolinestj** [comment]
![milk chest dimensions](https://user-images.githubusercontent.com/22770827/27050031-27ad5a0a-4f7f-11e7-9f5f-401eb7fcb8d1.jpeg)
