### ISSUE TITLE
Styling ISD speed letters

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#364]
Hello,

Wing and I are working with the plans examiners at ISD to update the "speed letters" they sometimes need to send to applicants of complex construction projects after an initial review of the application. These letters explain what additional materials need to be submitted for a complete review/approval. I realized that this is an opportunity to make the letter more "on brand," to the extent that Wing, the permitting team's report developer (cc'ed), is able with the tool he has. 

Attached is an example. The content of the crystal report is dynamic, based on what items are selected by the plans examiner in the back office. Most speed letters are not so lengthy; this is an example where literally every possible item is selected, to test out how it looks when it has to go onto the next page. 

I'm thinking the obvious design changes would be font and city seal, but other suggestions are welcome. With your feedback, we can figure out what is possible with the tool we have (SAP BusinessObjects Crystal Reports). Would be nice to see what we can do with it, as there are a lot more where this came from... but that's a conversation for another day. Thanks!

Anytime next week?

Suggestions for how to make it more on brand, but also if you have materials or specifications for incorporating the design elements across platforms would be great. Thank you.

**Comment by carolinestj** [comment]
[Example speed letter 2017.pdf](https://github.com/CityOfBoston/design-team-workflow/files/1047734/Example.speed.letter.2017.pdf)

**Comment by sebastianebarb** [comment]
[Styling ISD speed letters.pdf](https://github.com/CityOfBoston/design-team-workflow/files/1055356/Styling.ISD.speed.letters.pdf)
