### ISSUE TITLE
Now hiring description

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#385]
Hey James,
over the next week can we write up a paragraph description of the now hiring camping and why we created ?

**Comment by duffy-james** [comment]
The City of Boston is busy building a government that works now and in the future, and we need your help. That's the message behind our recent "Now Hiring" campaign. We're less focused on open positions, and more focused on personality types that fit.

We ignored the typical messaging around jobs and got to the point. It doesn't matter what the title is, we need workers who are passionate about what they do. Are you a "pothole hater"? Great, we need you. Do you consider yourself a "helpful human"? We want more people like you at the City.

To be even more blunt, we need people who know how to get s*** done at the City. We wanted that to come across in our simple and direct "Now Hiring" campaign.

@sebastianebarb is this along the lines of what you were looking for?
