### ISSUE TITLE
Web site anniversary graphic

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#391]
- B balloons?
-

**Comment by carolinestj** [comment]
https://docs.google.com/a/boston.gov/document/d/1ecNVcVnJclrNycPPZCuU4WrmRZWOru0hr0VBMcq2qSU/edit?usp=sharing

**Comment by sebastianebarb** [comment]
![screenshot_2017-07-20_09 29 58_720](https://user-images.githubusercontent.com/20642299/28431346-1270b7ae-6d52-11e7-978c-2007f068ca11.png)
In  Boston.gov>blog
