### ISSUE TITLE
Rethink unofficial election results

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#397]
Rethink display of unofficial elections results on boston.gov

Ideally this would be done by the end of July.

**Comment by reillyzlab** [comment]
@matthewcrist or @jduffy2001 can you insert a screenshot of what these results looked like on cityofboston.gov for reference?

**Comment by duffy-james** [comment]
![image](https://user-images.githubusercontent.com/7929556/28070597-7f5c8a02-661b-11e7-9b1d-c56f1042d423.png)

**Comment by sebastianebarb** [comment]
![election results](https://user-images.githubusercontent.com/20642299/28574222-4eeef3ea-711b-11e7-8ee0-4454dfd08aea.png)
