### ISSUE TITLE
Video Brand Guidelines

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#400]
Main Contact: Darren Cole

Things to cover:
- Color / recoloring 
- use of brand
- length of video
- encoding / formatting 
- web use
- use of outside footage
- camera angles (see photo guidelines)
- music
- lighting 
- closed captioned/ subtitles / translations
- story arc, tone (see voice in brand guidelines) 
- script (see writing guidelines)

**Comment by DACole** [comment]
Formulating a draft of concepts for each section. 

google doc:
(https://docs.google.com/a/boston.gov/document/d/1D4xwHBoh65yjHmUrKugwrKk6j6mtNfy8Y98UZdPqdpU/edit?usp=sharing)

**Comment by sebastianebarb** [comment]
https://docs.google.com/a/boston.gov/document/d/1u1EjKEWKvav3X2GUzNowOvis4HrshVC6G1RKwCucrVg/edit?usp=sharing
