### ISSUE TITLE
Email header

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#403]
Contact: hey - would you be able to mock up how we'd like the final design of the header to look?  I'm thinking that we can replace the B with the seal, clean up the alignment and maybe reduce the white space in the header?
 mock up how we'd like the final design of the header to look?  I'm thinking that we can replace the B with the seal, clean up the alignment and maybe reduce the white space in the header?

**Comment by sebastianebarb** [comment]
<img width="360" alt="screen_shot_2017-07-11_at_2 37 33_pm_720" src="https://user-images.githubusercontent.com/20642299/28084602-1228c2a8-6647-11e7-9373-ee85971c3770.png">

**Comment by sebastianebarb** [comment]
![email template header and footer_email header](https://user-images.githubusercontent.com/20642299/28084970-5876224a-6648-11e7-91ac-d4be3e8ccf23.png)
@collinmgately toughts

**Comment by collingately** [comment]
It feels like the "City of Boston" is a little too high compared to the seal?

**Comment by collingately** [comment]
Could you also factor in the sub head underneath "city of Boston" like where the department name would go? Or for our list "Updates from around the City"

**Comment by sebastianebarb** [comment]
![email template header and footer_email header](https://user-images.githubusercontent.com/20642299/28138587-562df7a6-671f-11e7-8ab9-04ebe6130d92.png)
![email template header and footer_email- footer](https://user-images.githubusercontent.com/20642299/28138586-562a9c3c-671f-11e7-9a43-da743a371f9b.png)
