### ISSUE TITLE
Resume tips graphics

### ISSUE THREAD

**Issue by taniadelrio** [CityOfBoston/design-team-workflow#406]
Hi Design team!

Hope you're well. We need to make some graphics to share on social media but to also put on a power point presentation for all interns about how to make your resume stand out. We have these bullet points that we would like to see in separate shareable graphics. Can you do your magic?

We need it by the end of next week if possible.

Tania :)

-Highlight your “Best Stuff” above the fold.

-Work Experience: Keep it Recent, Keep it Relevant! Update your resume often.
-Use as many facts & figures as you can to highlight your achievements! How many people were impacted by your work? By what percentage did you exceed your goals? Don’t be afraid to brag!

-Be specific! “Increased sales by 15%” is more impressive than “Increased sales”.

-Be specific! “Managed a $5 million Department budget” is more impressive than “Balanced the budget”.

-Experience First: Unless you’re a recent graduate, put your education after your experience. Chances are, your last couple of jobs are more important and relevant to you getting the job than where you went to college.

-Highlight Honors, Not GPA: If you graduated from college with high honors, make note of it!

-Constantly Refresh! Have you taken on new responsibilities? Learned new skills? Add them in!

-Show off your awards! If you were the “Volunteer of the Year” or the Class President, employers care!

-Diverse Career Interests: Have you had a long and diverse career? Include an Executive Summary.

-Use Action Verbs!: "Led", "accelerated", "enhanced", or "activated" paint a clearer picture than "did".

**Comment by sebastianebarb** [comment]
@Tania  I will try my best to get it to you end of the week.  right now Caroline is out for the next two weeks and I have a long line of requests.

**Comment by taniadelrio** [comment]
Hey Sebastian! Thanks! We totally understand the time issue, no worries. All your help appreciated! 

Tania

**Comment by taniadelrio** [comment]
Bullets for Linked In tips:

- Use Professional Photos: LinkedIn profiles that have a picture are 11 times more likely to be viewed!

- Write a Ridiculously Good Summary: Your summary should highlight your specialties, experience, accolades, and thought leadership!

- Terminate Typos: poor grammar, typos, and miss spelling are not a good look. Avoid typos at all cost.
 
- Get a Custom URL: It’s much easier to publicize your profile with a customized URL (ideally linkedin.com/yourname), and not the clunky combination of numbers that LinkedIn automatically assigns.

- Personalize Invitations to Connect: When you invite someone to connect, make it personal. Making it more personal will increase the odds they’ll accept your request.

- Ask for Recommendations:  LinkedIn makes is super easy, providing an "Ask to be recommended" link, where you can specify what you want to be recommended for, who you want to recommend you, and write a personal message. Pick specific people. Don't just randomly ask all your contacts if they can recommend you. Be selective.

**Comment by sebastianebarb** [comment]
Here you got @taniadelrio. https://drive.google.com/open?id=0B0RwQU94BhGeWExYOGtQMTlYQ3M

I also sent you a canva template so you can make your own

**Comment by taniadelrio** [comment]
Love this! Thanks! The template is awesome!
