### ISSUE TITLE
OEM Annual Report

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#410]
Contact: Christopher.Coakley@boston.gov

I'm in the process of writing the Annual Report for OEM. When it's completed, I'm curious if you might be able to assist in "dressing" it up in terms of lay-out? Caroline did an awesome job with our brochure - so I would like work with you again on this project and utilize your skills (that pay the bills). Let me know if you have some time to chat in the next couple of days.

**Comment by carolinestj** [comment]
[2016 Annual Report Outline.docx](https://github.com/CityOfBoston/design-team-workflow/files/1215770/2016.Annual.Report.Outline.docx)

Not finished but just the basic outline of the text

Check in one week from now 17/8

[Pics for Annual Report.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46d89d9930c285a69da99e4daa48f198697422632616b7693cc7f33ab0487e021b4d44be445f0c44fbfcdc2ca3be3e258a0909ecd16f0e21c23b42a5aa9e0dfd50e474d412dcfce9c85ecafa3f23ed8a8a4f3c1d0d1d8eff5a37a49e5985.zip)

**Comment by sebastianebarb** [comment]
After speaking with Rene, she's not a huge fan of the first pic on the Annual Report because it's more Fire Department focused. As opposed to one pic, how you would feel about placing 5 or 6 pics on the front page? Think that could work? We can throw a few community event photos, SWAT trainings we've paid for etc...  

Also, on the very last page, could substitute the attached photo? We like it because many staff members are in it. Thanks.

I appreciate all your help and patience. See you at 3.

**Comment by sebastianebarb** [comment]
[OEM REPORT v4.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c7b1b763b0a699a0db8b03b209b2d86b56357c2301a03f32dfa17de8412b565a0a49a9495a0a44a9fb882ba4e769748c0f02ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98b4fc9ed3e27e18c884f3c0c48.pdf)
