### ISSUE TITLE
Employee Experience Survey

### ISSUE THREAD

**Issue by taniadelrio** [CityOfBoston/design-team-workflow#414]
Hi Design team, 

We are getting ready to administer a city-wide Employee Experience Survey to compliment the quantitative information we compiled in the 2015 Workforce Report and learn about city employee engagement with their work. 

Here is a background note about the survey and our process: 

https://docs.google.com/document/d/1mQkbZxV1ujmV-VTw_qFaSTdcw3wOpxD99mpGhF7M9Cs/edit?usp=sharing

We are shooting for at least 40% participation, so we will need to do a ton of work to encourage folks and communicate why it is important. We hope that this informs what projects the diversity team prioritizes.

We need your help coming up with materials to promote the survey. We will need:

1) print posters
2) graphics for the City Hall screens, the template for those is here: https://docs.google.com/presentation/d/16OuNI1oarLPSB6k0_w807WcNwaqKuRym2XQrnubLI3M/edit?usp=sharing
3) postcards/or small flyers, as reminders to hand out to employees during the survey period. 

The survey will run during the first three weeks of October 2017. We would like to start promoting it in September, so there is time. :)

THANKS for the help!!!!

Tania & team

**Comment by sebastianebarb** [comment]
@taniadelrio we are on it!

**Comment by taniadelrio** [comment]
Hi guys, one more thing for this. We are going to need to also have kiosks, or places for people to fill out the survey in written form. We had thought that it may be possible to use the attached suggestion boxes which Property Management has agreed to lend us. We would need to adapt about ten of them. Attaching a picture. Do you think they are usable for this purpose and if so, could you help us make the materials to adapt them to the survey?

![img_8791](https://user-images.githubusercontent.com/26231957/29083225-f8442756-7c35-11e7-9f7d-ca859df16e21.JPG)

**Comment by carolinestj** [comment]
@taniadelrio do you have the size for the poster above the suggestion box?

**Comment by taniadelrio** [comment]
Sorry Caroline, not sure why I thought this was Sebastian!!!!

**Comment by carolinestj** [comment]
Keep graphics but update text from this doc https://docs.google.com/document/d/1tlWhSz7pyWwERuftzDfegt7a7o92UXKapTJ50zQGbvk/edit
