### ISSUE TITLE
Student move in

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#430]
Contact: 
Yissel Guerrero yissel.guerrero@boston.gov 
warren Reilly warren.reilly@boston.gov,

Thanks for reaching out. I only got one follow-up from Carla (BTD). She suggested that we check if all the links on the guide are accurate and if not, can we activate them for this year's move-in.

2. She caught a minor grammar mistake on the "Transportation and Parking" page. There should be a space in between "Sticker.(Space) Your" It's the paragraph under "Is your car with you?"

3. Carla also mentioned that the Hubway bike share is just that. There is not "New Balance in front of it.

4. The default speed limit in Boston is 25 mph. If you don't see a sign, the speed limit is 25 mph. https://www.boston.gov/departments/transportation/25-boston

Best,

**Comment by duffy-james** [comment]
This short url works for the 25 mph information: boston.gov/25-boston

I'll read through and offer notes.

**Comment by duffy-james** [comment]
Suggested rewrite here:

https://docs.google.com/document/d/1OHij6lvcsDS1qahVkOwHC64Es9vDm26UYoXNEuV-F-Y/edit
