### ISSUE TITLE
dog licenses UI / workflow

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#433]
can I put this in your queue to take a look at when you get a chance? We need to design a UI / workflow for the dog license app. Currently we have a landing page with two primary actions: renewing a licenses and registering for the first time. As it stands, there's not much to it:

We'd love to get your input around workflow in order to provide a good user experience, as well what we should do aesthetically. Please let me know if I can provide any additional information that would be helpful! Thanks!

https://github.com/CityOfBoston/dog-licenses/issues/25#issuecomment-323775480

**Comment by sebastianebarb** [comment]
Via @finneganh 
A few responses:
 - Need room for text above “Add a new Dog” to explain the flow. Also, should be “Register a New Dog”
 - Home page needs a “don’t know dog license” link that goes straight to the recovery form
 - Should “Neighborhood” be something you need to fill in?

Would be slick to dynamically change “neuter”/“spay” based on the assigned sex of the dog.
