### ISSUE TITLE
Boston Artists in Residence program flyer

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#434]
I would like to introduce you both to Karin and Sharon, they are throwing an event for the Boston Artists in Residence program on September 16th and were interested in releasing a flyer to help spread the word. 

Are you able to chat with them about putting something together? Below is the language they are looking to use. 

Let me know if I can help in any way. Much thanks in advance! 

https://docs.google.com/document/d/1tkium7mR5DhRJP5vnP_Uag50zW-A8eGtA0gvSkawtSc/edit

**Comment by carolinestj** [comment]
Boston air 2.0 
10 artist 
Not an exhibition but more of an artist panel with reception party 
for social media (print if they can) 
BCYF logo needs to be on there

**Comment by sebastianebarb** [comment]
https://drive.google.com/drive/u/1/folders/0B3K8sW-w3BEGaE9TYzhGRHZFUlE?usp=sharing_eip&ts=59a07325
