### ISSUE TITLE
Boston 2030 new logo

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#436]
Contact: Natalia Urtubey <natalia.urtubey@boston.gov>
I am hoping to rethink the IB2030 logo (attached here, along with other branding tools we've used) into one with the new branding guidelines.

**Comment by sebastianebarb** [comment]
![ib2030 logo 1](https://user-images.githubusercontent.com/20642299/29890844-fcc65426-8d96-11e7-838a-705f37ff1000.jpg)
![ib2030 logo 2](https://user-images.githubusercontent.com/20642299/29890841-fcbf2f5c-8d96-11e7-8dab-dd20f018dfb2.jpg)
![ib2030 logo 4](https://user-images.githubusercontent.com/20642299/29890843-fcc18b8a-8d96-11e7-9d12-423a20208855.jpg)
![ib2030 logos-color palette-01](https://user-images.githubusercontent.com/20642299/29890842-fcbfdd30-8d96-11e7-8cee-8d924a458b8b.jpg)

**Comment by sebastianebarb** [comment]
[IB2030 logo options.pdf](https://github.com/CityOfBoston/design-team-workflow/files/1312069/IB2030.logo.options.pdf) @reillyzlab

**Comment by carolinestj** [comment]
![imagine boston 2030 logo .png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46e1999b248b8daccfebb050b052fed47b1674236908ac2c7fc5a164fd52690e050a1de853524d41fbaa892ca3e33b75825e5eed846f5e74c46c44a8bed116ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b071d81f65d3da59a4ec95ee406.png)
![Imagine boston 2030.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46c1999b248b8daccfebb050b052fed47b1674236b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e58e87463e16001b8cfe5827ed.png)

**Comment by carolinestj** [comment]
https://drive.google.com/drive/folders/1qeT_5urQWeiON5IsBV5YFDaWWwYvsH-w
