### ISSUE TITLE
Services Graphic for City Hall to Go

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#442]
Sebastian and Caroline,

Would one of you be able to help design a graphic listing the services that City Hall to Go offers? We are hoping to have this available for three distinct purposes: posting on social media and boston.gov, printing out to hand to constituents, and a graphic that could be printed as a poster and attached to the truck itself. Let me know what further details you might need, I'd really appreciate your help with this.

Our list of services are available here: https://www.boston.gov/departments/city-hall-go#city-hall-to-go-services

Best,
Jacob

**Comment by carolinestj** [comment]
For digital: whatever you think works best for facebook and twitter and boston.gov

For print: I'd love to have something for an 8.5 x 11 piece of paper to be able to print out.
