### ISSUE TITLE
311 revisit translation options

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#453]
Got more translations for 311 translation options than we were expecting: https://docs.google.com/a/boston.gov/document/d/1nLwnxDgQCyCjXUra1Xlt75UifNpIxIa4g_hSIlnrysE/edit?usp=sharing

Sebastian, can you work with Fin to ensure everything fits and/or to rethink the page so that we can fit all languages in with good UI.

**Comment by sebastianebarb** [comment]
@finneganh resolved this one @reillyzlab 

![screen_shot_2017-09-12_at_12 08 26_pm_1024](https://user-images.githubusercontent.com/20642299/30338939-54c9f6ea-97bb-11e7-817e-dbf9f8562cda.png)
