### ISSUE TITLE
Icons (Bulk) V3

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#454]
Having icons represent issues on 311 is a nice to have and could potentially create a better user experience on the web map but it is not a priority for go-live.

Next steps:

1. Ideal target: 30-40 icons. Aggie will group the SRs that could share an icon. Find here: https://docs.google.com/spreadsheets/d/1keg36-2ja7RlhPIWesp0BRS4FJ_eIhKHYIROPkFAzOw/edit?ts=59ad7dd0#gid=615382675

2.Starting our test with 3 "easy"/"hard" to represent icons. Example traffic signal/park equipment. Sebastian could have the 6 ready for test by mid September.

3. Reilly will verify with other depts.

**Comment by sebastianebarb** [comment]
- [x] Animal Found
- [x] Animal Generic
- [x] Animal Lost
- [x] Pick Up Dead Animal
- [x] Rodent Activity
- [x] Catchbasin
- [x] Fire Hydrant
- [x] Sidewalk cover
- [x] Unshoveled Sidewalk
- [x]  Sidewalk Repair
- [x]  Pothole repair
- [x] Unsanitary Trash Conditions
- [x] Illegal Dumping
- [ ] Improper Storage of Trash
- [x] Needle Pickup
- [x] Park Equipment
- [x] Park Lighting
- [x] Park Graffiti
- [x] New Tree Request
- [x] Tree Maintenance
- [x] Overgrown Vegetation
- [x] Empty Litter Basket
- [x] Snow Plow 
- [ ]  Ice Control
- [x] Street Light Outages
- [x] Abandoned Bicycle
- [x] Abandoned Vehicles
- [x] Parking Enforcement
- [x] Missing/Damaged Sign
- [x] Traffic Signal
- [x] Traffic Signal Repair
- [x] childcare
- [x] services for families
- [x] School Facilities

**Comment by carolinestj** [comment]
Davids icons 
https://docs.google.com/spreadsheets/d/1pOnZ9ZIkw8h4NSaNKMp_gHYKdkCGufJJ0CVHtUnR33k/edit?ts=5bbe1c15#gid=1262158913

**Comment by carolinestj** [comment]
300 x 225 
Base theme 
Hub theme 
Admin theme
