### ISSUE TITLE
Retirement Calculator

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#455]
Digital will help with designs of a retirement calculator for employees. Build will happen with UMass.

Requirements here: https://mail.google.com/mail/ca/u/0/#advanced-search/from=luella.wong%40boston.gov&subset=all&within=1d&sizeoperator=s_sl&sizeunit=s_smb/15d9954551601416?compose=15e76df56856cf68&projector=1

Additional notes:
- translations: do like we did with 311 app
- Reilly has additional notes on flow display if helpful

https://drive.google.com/open?id=0B_zP1ba56BBEZ19uamRfZ1NjbDg

**Comment by sebastianebarb** [comment]
![img_8696_720](https://user-images.githubusercontent.com/20642299/30341635-c272c5ec-97c4-11e7-8bba-e593aafab7e7.jpg)

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=0B_zP1ba56BBEZ19uamRfZ1NjbDg

**Comment by sebastianebarb** [comment]
![retirement calculator](https://user-images.githubusercontent.com/20642299/30385467-4528ad34-9875-11e7-9689-2ca4d5445f9f.png)

![retirement calculator on track](https://user-images.githubusercontent.com/20642299/30385468-452b09f8-9875-11e7-90a0-73c5559e9ff7.png)

**Comment by sebastianebarb** [comment]
![Retirement Calculator on track.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46da918e2a9086a48ae7ab03875cfc973c4a26672616e3247ec5f73abe417043434d0eee1e020a17b8eb8339a3b16f708d595eead4655d21c66813adb8804eea05bc73825d99a4fedb1294b7607caddecd5d340c041083fe5835a69a4dcb50f648e44b51b65e.png)
![Retirement Calculator.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46da918e2a9086a48ae7ab03875cfc973c4a26672616e1673295f127b54778154d555ca9460b5f43f9ac8e2eaeb46970df5e0aedd33c0a70c06e18bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8f493d18061089fc5b34a78b06.png)

**Comment by sebastianebarb** [comment]
[Retirement Calculator.pdf](https://github.com/CityOfBoston/design-team-workflow/files/1415943/Retirement.Calculator.pdf)

**Comment by sebastianebarb** [comment]
Natacha Thomas is the associate general counsel for the Boston Retirement System.  She has provided disclaimer language for the tool below.  She asked that we have a checkbox after this language that the user must check before they are allowed to enter data into the tool.  Something like "I agree, continue" after the text is presented.

Luella



---------- Forwarded message ----------
From: Natacha Thomas <natacha.thomas@boston.gov>
Date: Thu, Nov 2, 2017 at 11:35 AM
Subject: Disclaimer Language
To: Luella Wong <luella.wong@boston.gov>
Cc: Christine Weir <christine.weir@boston.gov>, Padraic Lydon <padraic.lydon@boston.gov>


Hi Luella, 

Per our conversation today, please find the disclosure language below.   Please do not hesitate to contact me if you have any questions. 

The information and/or calculations displayed on this site do not necessarily reflect the actual amount of your retirement allowance. The results provided by this calculator are approximations and should not be considered as the final determination of your retirement benefit or relied upon for planning purposes.   The Boston Retirement System will not use this estimate to calculate your official monthly benefits.   

Note: This tool does not calculate benefits based on a disability, death of an active member, or a domestic relations order (“DRO”).

**Comment by sebastianebarb** [comment]
[Retirement Calculator.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46da918e2a9086a48ae7ab03875cfc973c4a26672616e1673295f127b54778154d555ca9460b5f43f9ac8e2eaeb46970df5e0aedd33c0a70c06e18bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8e4e371e011b88ff5830a78b06.pdf) for the meeting
