### ISSUE TITLE
Plaque Mockup

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#475]
Main contact: Eric Prentis,  eric.prentis@boston.gov

Would it be possible for a member of your team to mock up a bench plaque.  We are currently putting together a proposal to pitch to private entities in hopes of them sponsoring phases of this program.  And with that we would like to show them what a proposed plaque could/ would look like.

Ideally it would have a city seal or logo, sponsor logo ( first pitch is going to be with the City of Boston Credit Union so incorporating their logo or a space that says " your logo here" could suffice) along with the title Age- Friendly Boston and Mayors name.  we are open to any and all ideas with keeping in mind it would need to be produced in bronze or something similar.

Dimension wise we are probably looking at 4" by 11- 12".

Is this possible?

My apologies for the low quality photo, it was the only one I could find on the web

Eric Prentis

We are presenting the pitch to Chief Osgood next Thursday morning and have an eye on presenting to the first possible partner the following week.

**Comment by carolinestj** [comment]
![img_0116 1](https://user-images.githubusercontent.com/22770827/31234914-1dec1f12-a9be-11e7-9224-5a53057c5fd9.PNG)

**Comment by carolinestj** [comment]
notes after meeting dec 11 2018
![Image from iOS (2).jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46c1999b2487c3af9de6b203ad72c3d461146e316546b3397f8fe62bab0021435a581dac465d0a43f9f18b7ea6e33e718a5e5ab8d56b0c7dd42103eee9dc4be05ce36ade0d97bcae8b44cae93821e38e8a4b3f16031e80fc4f78.jpg)
![Image from iOS (1).jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46c1999b2487c3af9de6b203ad72c3d461176e316546b3397f8fe62bab0021435a581dac465d0a43f9f18b7ea6e33e718a5e5ab8d56b0c7dd42103eee9dc4be05ce36ade0d97bcae8b44cae93821e38e8a4b3f160d1c8dfe4f78.jpg)

**Comment by carolinestj** [comment]
They can accommodate the same size for the historical and modern bench. So only two sizes. The 3x9 and the 5 1/4x 11

**Comment by sebastianebarb** [comment]
[475_01_Bench_Plaques.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46bcc3cf1cd2d296adecb140ac62c098285732763a46ef696097ec22ba416f43554d4bab12585841a9fe8c23a4e33c25885d0bef80385b72953403b0aac04ee155e57dd205d0f4ae805ec2e83724e28f8a4f391a011080fc5432b2d4.pdf)

**Comment by sebastianebarb** [comment]
Per usual, nailed it!  I like it- clean looking.

One minor edit from the Chief and it makes sense.  Can we change some wording around to make it either "City of Boston bench" + "Age Friendly Initiative"  OR "City of Boston" + "Age Friendly Bench Program"

While the bench does meet age friendly criteria we want to draw the distinction that the bench is part of a larger "thing".  Does that make sense?

**Comment by sebastianebarb** [comment]
[475_02_Bench_Plaques.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46bcc3cf1cd2d196adecb140ac62c098285732763a46ef696097ec22ba416f43554d4bab12585841a9fe8c23a4e33c25885d0bef80385b72953403b0aac04ee155e57dd205d0f4ae805ec1ef3724e28f8a4c3d1b0c198cf7543db2d4.pdf)
