### ISSUE TITLE
Applications team branding

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#482]
Main contact: joseph.zeinoun@boston.gov 

NEED DONE by next wednesday!
Hi Reilly & Sebastian,

I would like your help to design a branding logo for the Enteprise Applications group.
Please let me know how we can proceed.
Thanks.

Joe

**Comment by carolinestj** [comment]
![enterprise logo _Artboard 5.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ed9a8e269093bb86faba03a852f79b697906613d06ac2a6281a37dfd0e39111d0014f9121c4d4eeefc8e78a6b139258d5903ef846d0a76c73d13fded8619ec08a83c990dd4e8e8d51199a26867f5819d4e3914041d89f85435a39c4aca5ff243f300.png)
![enterprise logo _Artboard 6.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ed9a8e269093bb86faba03a852f79b697906613d06ac2a6281a37efd0e39111d0014f9121c4d4eeefc8e78a6b139258d5903ef846d0a76c73d13fded8619ec08a83c990dd4e8e8d51199a26867f5819d4e3714041d89f85435a39c4aca5ff24ef300.png)
![enterprise logo -01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ed9a8e269093bb86faba03a852f79b690b77226b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e78c864f3d1b041a8efb5e27ed.png)

**Comment by carolinestj** [comment]
![enterprise logo _Artboard 6 copy 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ed9a8e269093bb86faba03a852f79b697906613d06ac2a6281a37eff417411164f4cbe5d4a1f06a3a3dc78e2a436628f5b58edd6680a73c33513f9b8d71dbe01b871de4b83e5b59850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec851f649e74954ac103063f43b.png)
![enterprise logo _Artboard 6 copy 3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ed9a8e269093bb86faba03a852f79b697906613d06ac2a6281a37eff417411164f4dbe5d4a1f06a3a3dc78e2a436628f5b58edd6680a73c33513f9b8d71dbe01b871de4b83e5b59850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec851f649e74954ac123266f43b.png)
![enterprise logo _Artboard 6 copy 4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ed9a8e269093bb86faba03a852f79b697906613d06ac2a6281a37eff417411164f4abe5d4a1f06a3a3dc78e2a436628f5b58edd6680a73c33513f9b8d71dbe01b871de4b83e5b59850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec851f649e74954ac133263f43b.png)
![enterprise logo _Artboard 6 copy.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ed9a8e269093bb86faba03a852f79b697906613d06ac2a6281a37eff417411164d52be011a001ea9aacd39aca43977d95c0ce8846a5a7cc46811f9ba831fbd50ef248d1c8ca4a0980e91b6697abad2c51a7c0c0f0a88f75734a59942c85af04fe04554a516242e.png)

**Comment by carolinestj** [comment]
![enterprise logo2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ed9a8e269093bb86faba03a852f79b7b046b313916ac217586f76ae5002e560c5f49a9145f5a4cfeac897ea4b73c72db090feb82644d68d47f40f2ecdd42e64bef62994597b7bb804dc5e93820ee8e87473a180d1f9bb2.png)

**Comment by sebastianebarb** [comment]
![enterprise applications logo](https://user-images.githubusercontent.com/20642299/41916891-1a18d266-7927-11e8-9ecc-ee0ac614bda4.png)
