### ISSUE TITLE
New Email Header

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/design-team-workflow#494]
Deadline: Nov 5-6

Problem

Some departments want to use Upaknee to send out press releases. The current template design doesn't quite fit that format. 

Solution

Design a new template that is very similar to the other one, but works better with the press release format. Pass to Upaknee to build. 

I sketched out an idea. Department logo centered on the template above the Boston.gov squiggly horizontal rule. Same footer as the other template. I defer to you completely on what you think.

![unnamed 4](https://user-images.githubusercontent.com/20726937/31945345-eeb8db5c-b89c-11e7-9aeb-4f840b90ae23.jpg)

Josh

**Comment by sebastianebarb** [comment]
![Press Template Header_email header.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46d8869f3091c39d8ae4af4fa549f5d4014326772c169c2e7d84ea24ff4a7e000b0a0cbe5d4a1f06a3a3dc78e2a436628f5b58edd6680a73c33513f9b8d71dbe01b871de4b83e5b59850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec958f74ce04451ac173167f43b.png)
