### ISSUE TITLE
Department icon needed for Returning Citizens

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#498]
The Office of Returning Citizens needs a new department icon. Here's a description of their work:

"The newly formed office will support the nearly 3,000 individuals who return to Boston after being released from state, federal and county facilities each year, as well as others who were previously incarcerated. . . The Office aims to help individuals who have taken healthy steps and prepared themselves to move past the consequences of their past actions, and coordinate the work done by Boston's social service and law enforce partners. This office will incorporate best practices from local, state, and federal partners and include a review of similar offices in Washington D.C. and Philadelphia."

**Comment by sebastianebarb** [comment]
![Screenshot 2017-11-14 15.54.14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36417763e7850e37a25cbb67cf1132f43434d0eee1e020a17b8eb8339a3b16f708d595eead4655d21c66813adb8804eea05bc73825d99a4fedb1294b7607caddecd5d340c071883fe5834a09f42cb58f04ae94550b65e.png)
