### ISSUE TITLE
Mock-up of potential receipt

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/design-team-workflow#499]
For the death certificate ordering application, we'll need to send out a receipt after a user orders a certificate. This needs to clearly show the user what they ordered as well as make it clear what percentage of what they paid went towards credit card processing. Tagging @finneganh so they can keep an eye on this. Hoping to have this mockup by Friday (doesn't have to be final, but we need something to present for a meeting). 

Please create a mock-up of a receipt with the following information:

Thank You for Your Order with The City of Boston
Date: 10/11/2017 11:00AM
Order Number: 123123 

Your shipping information:
Joshua Gee
123 Fake Street
Boston, MA 02120

Your order:
4 x Death Certificate for John Smith (Record # 123123) - $56
6 x Death Certificate for Amy Smith (Record # 123124) - $84

Subtotal - $140 
STRIPE online credit card service fee - $14

TOTAL CHARGE -- $156

If you have any issues or questions, contact 555-555-5555 or email registry@boston.gov. 

--

Potential receipts for inspiration: 
![receipt3](https://user-images.githubusercontent.com/20726937/32227509-04bb5a3a-be22-11e7-9fab-55bd8b72d2f7.JPG)
![receipt2](https://user-images.githubusercontent.com/20726937/32227510-04cb1132-be22-11e7-8f00-1006dc1efadd.JPG)
![receipt 1](https://user-images.githubusercontent.com/20726937/32227511-04dcaf32-be22-11e7-9856-b0c58d4c84e8.JPG)
![receipt4](https://user-images.githubusercontent.com/20726937/32227586-2eeb41c6-be22-11e7-9734-56c15e9fbcbe.JPG)

**Comment by sebastianebarb** [comment]
![screenshot 2017-11-02 09 58 17](https://user-images.githubusercontent.com/20642299/32329908-c9f9f53e-bfb4-11e7-9963-df4883f13035.png)

**Comment by joshuagee** [comment]
- [ ] Headline should be "Thank you for your order"
- [ ] Can the total charge line up with the sub charges
- [ ] Can there be more space between subtotal, fee, and total charge. Giving more emphasis to the credit card fee. 
- [ ] The em-dash before each number sort of makes it look like the dollar amounts are all subtractions. 

General note: not sure if I like the skeuomorph affect of the paper receipt.

**Comment by sebastianebarb** [comment]
What is your issue with the paper receipt?
Reasons to keep it:
- Added more attention to the total given the difference in line
- It adds a more defined end
- The template will be used beyond things relating to death and should be thought of in a winder way.
- It allows us to add warmth to the official nature of the email

![Mock-up of potential receipt v2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c59b9928cf96b9cfe6b903b452e49127522e722544b12e7380ea38ab026d534d435cec03070511afbd9b21b4b33b238a5b0eb8d6685776933d44aeb9821dee54be26d84697aaaec81d9ebc6278bec1da0d2c14171a89f55c30a0904dcb5bf543e04d53a7017b.png)

**Comment by joshuagee** [comment]
That all makes sense. I don't have a strong reason to call it out, so it might just be a personal bias. I defer to you.

The light blue for text is hard to read. Also want to get feedback from @finneganh

**Comment by fionawhim** [comment]
Is the blue text on purpose?

I'm ok with this. It looks feasible to implement given limitations of email.

**Comment by sebastianebarb** [comment]
![Mock-up of potential receipt v3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c59b9928cf96b9cfe6b903b452e49127522e722544b12e7380ea38ab026d524d435cec03070511afbd9b21b4b33b238a5b0eb8d6685776933d44aeb9821dee54be26d84697aaaec81d9ebc6278bec1da0d2c1417198ef55c30a0904dcc5cfe4fe14e53ac017b.png)

**Comment by joshuagee** [comment]
Two additional changes. Sorry, I think it's awesome but this will help us with legal. 

- [ ] Replace "STRIPE online credit card service fee" with "STRIPE online credit card service fee*"

- [ ] Add the following text to the email, inside the receipt but below the total charge. No need to make it too small or try to hide it. 

*To be as transparent as possible (and to follow state 
law) we list the credit card processing fee as a separate line item. This fee goes to an outside company to handle secure credit card transactions. The city contracts with Stripe to handle transactions like this one.

**Comment by sebastianebarb** [comment]
![Mock-up of potential receipt v4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c59b9928cf96b9cfe6b903b452e49127522e722544b12e7380ea38ab026d554d435cec03070511afbd9b21b4b33b238a5b0eb8d6685776933d44aeb9821dee54be26d84697aaaec81d9ebc6278bec1da0d2c1417198ff55c30a0904dcd59f049e54d53a1017b.png)

**Comment by joshuagee** [comment]
Can you make that footer text a bit more readable? Maybe just make it the same color as the rest of the text or only a bit lighter?

**Comment by sebastianebarb** [comment]
![Mock-up of potential receipt v5.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c59b9928cf96b9cfe6b903b452e49127522e722544b12e7380ea38ab026d544d435cec03070511afbd9b21b4b33b238a5b0eb8d6685776933d44aeb9821dee54be26d84697aaaec81d9ebc6278bec1da0d2c1417198ef55c30a0904dcd5af74ee34857a6017b.png)

**Comment by joshuagee** [comment]
Can you bump up the size of the disclaimer text and swap it out: 

Replace:

*To be as transparent as possible (and to follow state law) we list the credit card processing fee as a separate line item. This fee goes to an outside company to handle secure credit card transactions. The city contracts with Stripe to handle transactions like this one.

With:

*To be as transparent as possible (and to follow state law) we list the credit card service fee as a separate line item. This fee is 2.1% of your total transaction, plus $0.25. The city doesn't keep any of this money. The entire fee goes to an outside company. The city contracts with STRIPE to handle transactions like this one. If you have questions or want to know more have questions about the fee, go [here](url).

**Comment by sebastianebarb** [comment]
![Screenshot 2017-11-27 16.06.27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36417763e7b53e37a26cbb37ef1102c43434d0eee1e020a17b8eb8339a3b16f708d595eead4655d21c66813adb8804eea05bc73825d99a4fedb1294b7607caddecd5d340c041f83fe5834a1914ace51ff4ae24551b65e.png) @joshuagee

**Comment by joshuagee** [comment]
@finneganh FYI
