### ISSUE TITLE
Comp need: Layout/design for auto generated city record [with idea that we'd potentially pump RSS of advertisements into Upaknee and/or Google Docs

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#522]
We would like to explore re-thinking the City Record. 

Ideally, bids/rfp, etc. advertisements would only need to be entered into Drupal once and then we'd use an RSS feed to feed the advertisements into other systems.

We'd like a design comp to think through how individual advertisements [https://github.com/CityOfBoston/design-team-workflow/issues/519] can we fed into Upaknee and/or Google Docs and look nice as a re-thought City Record. We would post this online as well as send out paper copies. To my understanding we need to display the entire record, but we can regroup with Kevin Coyne if we want to revisit including entire piece of content.

Ideally, the design would also include a cover (front for sure, back negotiable) and potentially a table of contents.

**Comment by sebastianebarb** [comment]
![City record google docs.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46cb9d8e3ac291ac8ce6ad47e45aff9b2e4a22332d0ba03832c9a138ad4d71040c1b5ca6535d5817fcfe8c7ea1b33472df5c5eefd06d5d25933917ffb19003ad43eb7edf10d8eff6df0ed2e22f27e7818e4a3f1a01108efc5a31a9984dda15.png)

![City Record gmail.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46cb9d8e3ac2b1ac8ce6ad47e45afd95204a653f6b14b1247a80e03cfd183954580c4eab440d5841f4fbdc2bf3b43d70880d5ee9d73e5666da2f53fde6d640e258f075c95d8fa4bd8346c1ed3c21e383884c3716041f81ed10.png)


[Bids:RFPs.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46ca9d9e30d8b18fbffafd0fe64de29b234324676b5ee17e2786b37fea472c54575d1bac145a5e44fea8dc2fa0e53562964e49bc8f3900299f7744eeaa880dbe08b0218e4e81b2b48d4fc7ec3523ee99c2.pdf)

**Comment by sebastianebarb** [comment]
All files. https://drive.google.com/open?id=14MYSCB9mpRUjU5Gl9r5F-s0nyMw31Cmo
