### ISSUE TITLE
Mockup of Credit Card Statement

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/design-team-workflow#523]
I need to mock up what a credit card statement will look like under Stripe. 

Please photoshop this statement:

![unnamed 1](https://user-images.githubusercontent.com/20726937/32793546-41d5d018-c934-11e7-90af-a15dffc7aa4e.png)

Replacing "0609 Boston Parking Tickets" with "Boston + 130.45 CC fee"

**Comment by joshuagee** [comment]
I need this by Thursday morning -- sorry for the quick turnaround.

**Comment by sebastianebarb** [comment]
![mockup of credit card statement 3x](https://user-images.githubusercontent.com/20642299/32805810-8e270fe4-c958-11e7-83dc-1db52e837101.png)

**Comment by joshuagee** [comment]
Can you redo this, swapping out "BOSTON + 130.45 CC FEE" for "BOS Death Cert + CCfee" 

@finneganh

**Comment by sebastianebarb** [comment]
![Mockup of Credit Card Statement-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c59b99289793e980efff60b658f49d3d0604723b00e3186484f72db2477515425f4fbe5d4a1f06a3a3dc78e2a436628f5b58edd6680a73c33513f9b8d71dbe01b871de4b83e5b59850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95af74fe5455ca51b3463f43b.png)
