### ISSUE TITLE
Broadcast email header

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#524]
A request just in from Jascha to have us create an e-mail header for the Cable office to send updates internally that appear legitimate. Is this something you'd be able to take on? Sounds like they're sending just from Gmail, but I can confirm.

**Comment by jfalvey** [comment]
Misspoke in my original note this is actually for DOIT-wide e-mails (via Gmail) out to internal City audiences.

**Comment by sebastianebarb** [comment]
![Broadcast Email Header-03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46ca8695228680a89cfdff66a95cf998696e22722d01b16620d6a164fd52690e050a1de853524d41fbaa892ca3e33b75825e5eed846f5e74c46c44a8bed116ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b041981fe5c34a89e42c05ce406.png) 
@jfalvey this should work
