### ISSUE TITLE
Flyer for BPS

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#533]
Contact: natalia.urtubey@boston.gov
BPS students don't know that they can use their M-7 T-passes for the Fairmount Line, so instead, they're taking multiple buses and adding unnecessary travel time.

Would you be able to help me come up with a really fun flyer for us to send to students and families? Basically, something simple and fun that says:

Cut your travel time down! Use your M-7 pass on the Fairmount Line!
Your student T-pass works on the Fairmount Line

Maybe add the following images, or a version of it? Maybe it can have a back and the back can include the schedule or a map?

I leave it to you to get creative. I am meeting with BPS during the first week of December-- is that a feasible timeline?

**Comment by carolinestj** [comment]
- The line is called the Fairmount Line (M-7 is the name of the student passes)

- We will be sending these out as physically and digitally -- feel free to make one of them more printer friendly (black/white or easy to print in black in white if necessary) 
postcard size for the physical stuff 

- Logos should include; Mayor's seal, IB2030 logo (attached) and I am getting approval to use the MBTA logo and one of our community partner logos.

- Here is the schedule (kind of complicated to read, feel free to only use the times that would be relevant to students, i.e. start/end times of schools)-- I can help narrow this for you if that's helpful.​ https://d3044s2alrsxog.cloudfront.net/sites/default/files/route_pdfs/commuter-rail-fairmount-2017-11-20.pdf

- Not in a terrible rush, but by early January would be ideal. We will likely do a few phases of an awareness campaign (January and August).
