### ISSUE TITLE
#LetsAllShopSmall

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#538]
Contact:crystal.torman@boston.gov
Mayor's Office of Economic Development	

help me get our message to the right audience!), Deisgn something that helps to make something that tells people about #LetsAllShopSmall. The initiative was announced on Saturday

Audience: Consumers and small businesses citywide.

**Comment by carolinestj** [comment]
old graphics
![C0TliwdXUAAqe-w.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cbc4ae2f8b94adb7dc9e62b558bd836b0a65633b0ba92e7391a172fd172c025f584bf9465d5746a9f9dc29a7b63e21df580dbed87f4366846c4ff8e7df46f554f832815d84b1b68b49c1e93a2ce28b8e473e1c010ac4.jpg)
![CzFi5wYW8AEgJSe.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cb8ebc2ad79490b8b19e66a377c3916b0a65633b0ba92e7391a172fd172c025f584bf9465d5746a9f9dc29a7b63e21df580dbed87f4366846c4ff8e7df46f554f832815d84b1b68b49c1e93a2ce28b8e473f1f0c0ac4.jpg)
![C0NP6-qUkAA7eSD.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cbc4b413d4ceb8bae29e62f358c3b06b0a65633b0ba92e7391a172fd172c025f584bf9465d5746a9f9dc29a7b63e21df580dbed87f4366846c4ff8e7df46f554f832815d84b1b68b49c1e93a2ce28b8c493918020ac4.jpg)
![Screen Shot 2017-11-27 at 10.07.04 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f46b7191a379ef0c2b56415f4abc30254d58eeb9cb74fce36f34985619e8d63e5f73c36816a9b0804abf54b8218b4dd4e3b88c1fc9fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae04a5ca1123f67e277316e0a.png)
![Screen Shot 2017-11-27 at 10.07.22 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f46b7191a379ef0c2b56415d4cbc30254d58eeb9cb74fce36f34985619e8d63e5f73c36816a9b0804abf54b8218b4dd4e3b88c1fc9fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae04a5ca1123f67e2753e6e0a.png)
![Screen Shot 2017-11-27 at 10.07.39 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f46b7191a379ef0c2b56415c47bc30254d58eeb9cb74fce36f34985619e8d63e5f73c36816a9b0804abf54b8218b4dd4e3b88c1fc9fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae04a5ca1123f67e277356e0a.png)
![Screen Shot 2017-11-27 at 10.08.10 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f46b7191a379ef0c2b59415e4ebc30254d58eeb9cb74fce36f34985619e8d63e5f73c36816a9b0804abf54b8218b4dd4e3b88c1fc9fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae04a5ca1123f67e2773e6e0a.png)
