### ISSUE TITLE
Tres Reyes Celebration

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#549]
https://docs.google.com/a/boston.gov/document/d/1CHTLJpe6eRINlzNZH3mTsYMNgl-7_Xnekp6eLdTvlfI/edit?usp=sharing
update from last years 3 kings day

**Comment by carolinestj** [comment]
Create canva program template 8.5 x 11 folded in half 
1 or 2 weeks before date of event 

contact:
Alexandra Valdez

**Comment by sebastianebarb** [comment]
https://docs.google.com/a/boston.gov/document/d/1CHTLJpe6eRINlzNZH3mTsYMNgl-7_Xnekp6eLdTvlfI/edit?usp=sharing

**Comment by sebastianebarb** [comment]
![Tres Reyes2017-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46dc869f30c2b1ac96ecac11f40ca7d97917653f6b14b1247a80e03cfd183954580c4eab440d5841f4fbdc2bf3b43d70880d5ee9d73e5666da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3c26e48e8f4b361e0d1a88ed10.png)
![Tres Reyes-2017_web.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46dc869f30c2b1ac96ecac0ef60da1c3165122716b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e6888c4a3e1a0d188efa5a27ed.png)

**Comment by sebastianebarb** [comment]
[Uploading Three Kings Celebration Program.pdf...]

**Comment by sebastianebarb** [comment]
[Three Kings Celebration Program.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46dc9c882687c38286e7b850e47ef5982c4435723d0dac2530b5f127b8507a0c4d435cec03070511afbd9b21b4b33b238a5b0eb8d6685776933d44aeb9821dee54be26d84697aaaec81d9ebc6278bec1da0d2c14171980f55c30a19d42ca51f64fe84450ac017b.pdf)
