### ISSUE TITLE
New icons for New Urban Mechanics page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#551]
New Urban Mechanics has a section for its fellows. I'm wondering maybe if you could take a shot at creating better experiential icons for them. The subjects are "Year-long fellowships" and "Summer fellowships." Basically, they're interns:

![image](https://user-images.githubusercontent.com/7929556/33773513-222c2ae8-dc06-11e7-8a04-3debd6d83903.png)

**Comment by sebastianebarb** [comment]
![EXPERIENTIAL ICONS _MoNUM Fellow.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46cdacaa06b0aa8ca1dd9662881dd9b7066814331629ac0545a8a30eba4e770e184d52be011a001ea9aacd39aca43977d95c0ce8846a5a7cc46811f9ba831fbd50ef248d1c8ca4a0980e91b6697abad2c51a7c0c0f0a88f65734a59848ce5bf442e14857a512242e.png)
![EXPERIENTIAL ICONS _FELLOWSHIP.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46cdacaa06b0aa8ca1dd9662881dd9b706681433162286075caad41b976b4b43434d0eee1e020a17b8eb8339a3b16f708d595eead4655d21c66813adb8804eea05bc73825d99a4fedb1294b7607caddecd5d340c041f83fe5834a39f48ca51f64ee34d56b65e.png)
