### ISSUE TITLE
Adobe Government awards

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#555]
Projects we might submit 
– Help for Houston 
– Food maps 
– Preservation month campaign 
– One of Darren's videos 
– Career Campaign 
– boston.gov redesign 

Up to three unique submissions in each category
no more than 27 total 

Have to upload to behance 

deadline may 31st 

all rules https://adobecreativityawards.com/files/AGCA_Official-Rules_171102_EN.pdf?1513170635

**Comment by sebastianebarb** [comment]
- https://www.behance.net/gallery/59441611/Preservation-month-campaign-2017
- https://www.behance.net/gallery/59441905/Food-Access-list-map
- https://www.behance.net/gallery/59884355/Help-for-Houston
- https://www.behance.net/gallery/53252769/Now-hiring-everyday-heros

**Comment by carolinestj** [comment]
- make behance projects for all the projects that are being submitted
