### ISSUE TITLE
Tree waste graphic

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#558]
showing the circle of life for a christmas tree

**Comment by sebastianebarb** [comment]
[Uploading tree_recycle2_square_1024.png...]

**Comment by sebastianebarb** [comment]
![tree_recycle2_square_1024.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46fc869f26bd91ac8cf0bc4fa10fcf87385326612c3bf27b22d1a164fd52690e050a1de853524d41fbaa892ca3e33b75825e5eed846f5e74c46c44a8bed116ad1da862da11d1e9e1d30695aa2f2ff5898f453f1b041c8df65d36a3994bc95ce406.png)
