### ISSUE TITLE
2017 Workforce Report - Diversity Tea,

### ISSUE THREAD

**Issue by taniadelrio** [CityOfBoston/design-team-workflow#570]
Hi guys,

Hope you are well!

Our office completed its second Workforce Report, which has been OK'ed by Chief of Staff and Policy Office, so we are now pretty much ready to launch! Can you help us make its design presentable? 

Timeline, we would like to be able to launch it before the end of January 2018, let us know if this is feasible for you. 

Here is the file: [https://docs.google.com/document/d/18vzIctjP0DqS1nNfqaEyiEgXpLCmZQGLxdGmlWbNcnM/edit?usp=sharing](https://docs.google.com/document/d/18vzIctjP0DqS1nNfqaEyiEgXpLCmZQGLxdGmlWbNcnM/edit?usp=sharing)

Tania

**Comment by carolinestj** [comment]
Current draft

[workforce report.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ff9b8828848cbb8cecff51a14dff863d046b313916ac217586f76ae5002e560c5f49a9145f5a4cfeac897ea4b73c72db090feb82644d68d47f40f2ecdd42e64bef62994597b7b5804dc5ea3527e68286473c1a041d9bb2.pdf)

google folder https://drive.google.com/drive/folders/1Cmv-27wzvdpZM5DLb-uQbeJKvRypFaHA

**Comment by carolinestj** [comment]
Ticket closed - report not being published
