### ISSUE TITLE
New logo for Boston Police Cadet program

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#579]
I attached the logo given to me by the police. Just hoping we can get something similar that fits our branding.
![police-cadet-patch](https://user-images.githubusercontent.com/7929556/35005181-92530430-fac0-11e7-9eb2-864ba823482c.jpg)

**Comment by sebastianebarb** [comment]
![images.duckduckgo-2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46e1999b248790e78bfcbc48a048f39f2e496a216b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e68d8d4f3e19051f80f65927ed.jpg)

![images.duckduckgo.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46e1999b248790e78bfcbc48a048f39f2e49653f6b14b1247a80e03cfd183954580c4eab440d5841f4fbdc2bf3b43d70880d5ee9d73e5666da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3c23e58b8f483e1605108ced10.jpg)

**Comment by sebastianebarb** [comment]
![images.duckduckgo-1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46e1999b248790e78bfcbc48a048f39f2e496a226b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e68d8d4f3e19041e8afc5e27ed.jpg)

**Comment by sebastianebarb** [comment]
![Cadet logo@3x.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46cb959e2696c3a580eeb063f745b2d86b56357c2301a03f32dfa17de8412b565a0a49a9495a0a44a9fb882ba4e769748c0f02ffcd7f1d2598694ef1e1c84afd13b0328a478fb7b98b4ac8e83425ef898c4d3f0c48.png)
