### ISSUE TITLE
BCYF Logo for Newsletters

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/design-team-workflow#584]
The BCYf logo doesn't fit in the standard icon slot. I can remove the icon, but they really want a logo. 

![bcyf color 1](https://user-images.githubusercontent.com/20726937/35235107-31aa4156-ff71-11e7-9566-931e3920b895.png)

We can use the full-width image content block to drop the image right below the header. However, that content block stretches out the image. 

Can you create a 600px-wide image that's between 75-150px tall. The logo should be inside white space (transparency may work) so that it is a decent, header-ish size.

**Comment by sebastianebarb** [comment]
![BCYF_COLOR_and_BW-02.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46cab7a305bda086a3c68d7ca553f4ab0b716a237b46ef696097ec22ba416f43554d4bab12585841a9fe8c23a4e33c25885d0bef80385b72953403b0aac04ee155e57dd205d0f4ae805ec1e13724e28a89493a1903188ef6543cb2d4.png)
