### ISSUE TITLE
Icons for Maps

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/design-team-workflow#593]
We need a set of icons to offer content editors when creating maps. Planning on adding to this collection if/when we need, but we should start with:
- Pointer icons, like what are used in [this mock-up map](https://camo.githubusercontent.com/2500dc67bdfc4a3ef4abff009d68e88787f5c3a8/68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3537396134323661386635393461313330303834323261332f31323535313663363665383263373238616365323165306434366331626162333137616261323964613664663961303165383166653038363236346332323730336434366639363932356432653037386538313737653536356135373463663934313064356434356663666264383765613262303666373939383430313961663830333330623262396236343562663966613930313561643030626432613861346138346230623538623466633065653361323565363833396430322e706e67) in a few of colors: 
     - Freedom Trail Red 
     - Charles Blue
     - Optimistic Blue
- This [parking icon](https://drive.google.com/open?id=0B0RwQU94BhGedlFMU0IwYUFOeEU) with a white background
- Replacements for the food truck and farmer's market icons used [here](https://cob-maps.herokuapp.com/farmers_markets.html) that are small-circle icons to stay with a consistent look and feel across maps
- Public bathrooms icon, which needs no changes - we already have it with a white background and it can be found in the drive folder below

Created this [drive folder](https://drive.google.com/drive/folders/1dMg5VeP2EcLoPFd-qfvDnETEyLBMutwm?usp=sharing) where we can aggregate these icons. Icons as SVGs would be great.

**Comment by sebastianebarb** [comment]
@paylakatel  please check the previously created folder for requested SVG and PNG Icons.  happy to make changes.  If it's to your satisfaction done please close the ticket.

**Comment by paylakatel** [comment]
Looks great - thank you!
