### ISSUE TITLE
Syllabus for user testing class

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#594]
Main contact: Sebastian
Priority: Low 
Due: --

- [ ] Need to look up other syllabi 
- [ ] Develop tailored Syllabus 
- [ ] Set date for the class

**Comment by jiaoruijiang** [comment]
https://docs.google.com/document/d/1GUURfKrGqdXFRRTHXFAQS0p0Afx_EiOFqVHCWp_ZVPY/edit
