### ISSUE TITLE
Boston Public Improvement Commission logo

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#602]
Through a discussion that I had with Chief Osgood, he suggested that we reach out to you regarding developing a City department logo for the Public Improvement Commission (PIC).  After looking at other department's logos and considering the PIC's functions, we drafted the attached mockup showing generally what we feel might be appropriate.  To give you some background, the PIC is responsible for considering and approving all improvements within the City's streets and sidewalks, including (as shown within the mockup) street lights, trees, building elements, roadway design, and subsurface utilities.  Most of these improvements are associated with building development.  We tried to capture as many aspects as we could while not making it too similar to, for example, the BPDA's logo.

I'm not sure if what we've come up with is too cluttered or busy, but we're happy to give you and your team the creative liberty necessary to make this adhere to whatever criteria you have for department logos.  We threw this together relatively quickly so recognize that there are changes that may be needed to improve the spacing, scaling, etc.

Let us know if you have any questions for us.  Thank you!

CONTACT: 
Todd Liming

**Comment by carolinestj** [comment]
![Boston PIC Logo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ca9b89378d8de9bfc09c038852f79b6b0a65633b0ba92e7391a172fd172c025f584bf9465d5746a9f9dc29a7b63e21df580dbed87f4366846c4ff8e7df46f554f832815d84bfb68b49c1ef3523e48f874c3719030ac4.png)

**Comment by sebastianebarb** [comment]
![screenshot 2018-04-12 14 21 15](https://user-images.githubusercontent.com/20642299/38696649-c0d2924a-3e5d-11e8-800a-035ef076557b.png)

**Comment by sebastianebarb** [comment]
![Screenshot 2018-04-17 11.35.47.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6416733e7853e37a21cbb07df1162c43434d0eee1e020a17b8eb8339a3b16f708d595eead4655d21c66813adb8804eea05bc73825d99a4fedb1294b7607caddecd5d340c041083fe5837a3904cc15df04ae14c53b65e.png)

**Comment by sebastianebarb** [comment]
![full lock up.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46ee81962fc28fa68ce2ff56b41fbcd6395428792c07b7692ac7b67fbc122c540a584ba4430d5f11fef88929f7e33876d95519f1c32f0e2a92624cf5f2d75dad0ba821824584b3be8945c8e83e26e5838b492c53.png)
![icon.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46e197952dc0cfeb9ffbb049a15ee4d6730472242a54f47e75d2b670ed472b045d5e4eae100d5b42aff09b37b4f46d2ede0356b49b381d66cc2f10a4b2831abd02b3288b4c86b4b8824dd2a5.png)

**Comment by sebastianebarb** [comment]
Todd Liming
Attachments11:20 AM (2 hours ago)
to me, Amy, Caroline 
This looks fantastic, thank you again.  Our final (I believe) request would be to add a narrow white strip separating the top edge of the street from the tree/buildings.

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=1PZKKY4LfWuXNR1JPZ2xdhhhTyLhvBgM4
