### ISSUE TITLE
Modify Black History Month Art Contest graphic

### ISSUE THREAD

**Issue by taniadelrio** [CityOfBoston/design-team-workflow#605]
Hey guys! Quick and time sensitive request. We have confirmation from TD Garden that they will donate Celtics tickets to the winners of the BHM Art contest. Can we add some sort of banner or marker or any flashy design to the graphic that can highlight this? We have not gotten too many submission and we think this will help a lot.

Attaching the file we are currently using.

Tania
![bhm art contest](https://user-images.githubusercontent.com/26231957/35998028-6be0c13a-0ce9-11e8-99b0-87b29053a78a.png)

**Comment by sebastianebarb** [comment]
@carolinestj this is first priority
