### ISSUE TITLE
Imagine Boston - UPHAMS CORNER

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#607]
contact shaun.blugh@boston.gov

https://drive.google.com/open?id=1scLHzMQ-4KkuV-iwtES3Bhjkzk3b786V

**Comment by sebastianebarb** [comment]
![1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b9d6d6619291a685ecbc57e607b2c17e4577247c01f47e28d7e678ba102a515d0e1ba8470b5656e0ebcb7af8e2632dd3165eafc3674d75c13710a9ba8317be03b9208f4f8db3aec7.png)
![2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46bad6d6619291a685ecbc57e607b2c17e4577247c01f47e28d7e678ba102a515d0e1ba8470b5656e0ebcb7af8e2632dd3165eafc3674d75c13710a9ba8317be03b9208f4f83b0aec7.png)

**Comment by sebastianebarb** [comment]
Hey Sebastian,

Can you please make the following edits to this flyer?
Move BPL to the top with the City ones 
Add DBEDC logo to the bottom 
 DB_Color.jpg
​
Change the BPM logo to this one ​
 BPM-logo-solidgreen-trans.png
​
Can we change the apple to another fruit or vegetable, maybe a broccoli or carrot? Someone said it looked like the Apple (Mac) company. 
Can we also change the heart to a paint brush?
Thank you, as always!!

**Comment by sebastianebarb** [comment]
![UPHAMS CORNER (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46dda4b202afb0e9acc68d6d816fb0dc780f653f6b14b1247a80e03cfd183954580c4eab440d5841f4fbdc2bf3b43d70880d5ee9d73e5666da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3f27e58e884b3f16021989ed10.png)

**Comment by sebastianebarb** [comment]
Hey there!

We have a kick-off date! 

1. Can we update the flyer and window posters to say:

Join us for the the Upham's Corner Farmer's Market and Historic Walking Tours from July 18 - October 24!

Wednesdays:
Farmer's Market 3-7
4th Wed- Boston By Foot Historic Walking Tour 6pm

Thursdays:
Read-In 4pm

Saturdays:
2nd Saturday: Boston By Foot Historic Walking Tours 10am

2. Can we update the posters to 11x17  so I can print in-house?

FYI: Here is the shared calendar: https://calendar.google.com/calendar?cid=Ym9zdG9uLmdvdl9hcm0yNGNxc2ZlNGlrNW8xY2hlOHFkdGk5OEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t
