### ISSUE TITLE
No Plastic Bags

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#608]
Contact: gerard.gorman@boston.gov
Due:

We were hoping you could help with this postcard that will possibly go in the mail to 75,000 + residence in the Dorchester area.

Please feel free to make any changes you feel that are necessary and this will be sent out for print.  I have also added the links to were this information is available to view.

Please let me know if you have any questions.

https://app.box.com/s/vcd7e5qy8vu4urf63ecacizcmibxij8y/folder/11638777793

https://app.box.com/s/vcd7e5qy8vu4urf63ecacizcmibxij8y

**Comment by carolinestj** [comment]
[DEP No Plastic Bags.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ccb1aa63ac8ce9bfe5be50b054f3d40b4720606b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984ec3e23c20e683894d381a0d1089fd5b27ed.pdf)
