### ISSUE TITLE
Working event flyer

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#616]
Contact: John Dunham
Find the attached flyer for our last event it needs to be remade for the template.
https://drive.google.com/open?id=0B0RwQU94BhGeZnotNUVxeW1iMEJSczR2NTV0Sm5VY0w2TFhr

Partners, CBO's, Contractors and Building Trades Unions	4/27/2018	This will be our third Policy & Placement Workshop	Christopher L Brown - BRJP Mgr./Sheryce Hearns Dep. Director

**Comment by sebastianebarb** [comment]
Text: 
ATTENTION!!
CITY OF BOSTON POLICY & PLACEMENT WORKSHOP FOR BOSTON RESIDENTS PEOPLE OF COLOR & WOMEN 
“BOSTON JOBS FOR BOSTON RESIDENTS”
The City of Boston will present on the new BRJP ordinance, best practices for contractors will be shared, union sign-up with DC 35 for Boston Residents and attending contractors will have the opportunity to interview unemployed union journey workers & apprentices


Dear Business Agents, Reps., Organizers, Contractors & Boston Residents you are cordially invited to spend the morning with the

Boston Residents Jobs Policy Staff
Painters & Allied Trades District Council 35
Boston Jobs Coalition
Policy Group on Tradeswomen Issues
Boston Residents People of Color & Women
Contractors

What:  On-site Employment & Union Sign-up Opportunity
When:  Friday, January, 26th 2018 From 9:00 am to 11:00 am
Where:  26 Court Street, Boston, Ma 02108 In the Winter Chambers Conference Room 1st Floor

**Comment by carolinestj** [comment]
https://www.canva.com/design/DACyFy4QYzs/rDutZrJmyXn76QwKJrEEYA/edit
