### ISSUE TITLE
Templates for FY19 city budget & capital plan

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#617]
Ideal start date 12/3/2018
Contact: Samantha Ormsby

**Comment by sebastianebarb** [comment]
https://www.canva.com/design/DACyMz4emLE/share?role=EDITOR&token=53hNelwG4GAcdZO6wX1bBA&utm_content=DACyMz4emLE&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton
