### ISSUE TITLE
Evacuation Day graphic

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#620]
Tied to epic https://waffle.io/CityOfBoston/design-team-workflow/cards/5ab25dbb6d2315001bc4d71c

**Comment by sebastianebarb** [comment]
![John Branagan, Evacuation Day.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c29b922dc2a1bb8ee7be44a553bcd40c5026703c05b7227f8ba30cbe5b394d4d1f0cf31b0d0c00eef39b2ea1e53c778f090ce8d96f0a74933f10acbad34abb07e929995397f4edd4189fb5646fb2c99d452c1f0d1288fa5e30a09d43c95df142e44547e9.png)
