### ISSUE TITLE
Double Up- Boston Marketing

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#625]
Contact: Stephanie Voltaire <stephanie.voltaire@boston.gov>

Due: 
Next deadline: March 13th

The FFN Branding Guide is attached to this email. As mentioned, as an organization participating in this program we do have to follow their branding guide but are able to make changes where it is necessary.

The materials discussed and approximate numbers for each are listed below. Please keep mind if there are any changes I will be sure to let you know. I forgot to mention, but we would also like to use the postcard and poster images for social media purposes. 
Postcards- 3,000
Stickers for eligible items- 1,000
Poster for windows (11 X 17)- 20
Interchangeable Poster/Banner- 10
Shelf Talkers (To place on basket/space where produce are)- 100
Participating Stores 

Ales Market 
77 Stoughton St, Dorchester, MA

Davey's Super Market
438 Dudley St, Roxbury, MA 

World's Best Food Mart
645 River St, Mattapan, MA 

Daily Table Grocery-Dorchester
450 Washington St, Boston, MA

Daily Table Grocery- Roxbury 
2201 Washington St, Roxbury, MA

**Comment by carolinestj** [comment]
[BDUFB Marketing Materials Edits.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cab0af05a0c3848efbb446b054fe93696b26672c16aa2a7c96a30dbb4b6f124d435cec03070511afbd9b21b4b33b238a5b0eb8d6685776933d44aeb9821dee54be26d84697aaaec81d9ebc6278bec1da0d2c1417198ef55c30a2984cca5ef149e54456a6017b.docx)
![EBT Card.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cdb6ae63a182bb8babf301b44fff9e2c4533317346f67c73d5b47dba152e595d0a4ef943595f46adac8d2df5bf2e6c981e5ab38532022d8c6853beb2901eb60bbb25894e82b4ba8d4ec9e13b24f5c6.jpg)
