### ISSUE TITLE
Comp need: Boards and Commissions Look-up Landing Page

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/design-team-workflow#627]
Comp need: Page layout for new landing page for boards and commissions look-up. We are looking to enhance the user experience of this [page](https://www.cityofboston.gov/boardsandcommissions/Default.aspx) that allows users to look up a specific board/commission and click on it to find out more information. 

There are 73 boards and commissions. We’d like the landing page for this application to allow a user to:

- See all the boards and commissions as [cards](https://patterns.boston.gov/components/detail/grid_transactions--default.html) or something similar? (may be too much with the number of boards and commissions, if it is we don't need to include it) 
- Search for a specific board/commission by name and display matches
- A drop down that allows the user to filter/show just the boards and commissions in a specific Policy Area (e.g. Administration and Finance, Arts and Culture, Transportation and Public Works, etc.) and display matches
- A checkbox filter that allows users to show boards/commissions that have vacancies or holdover members and display matches

If we could have this by Monday, 3/12, as pdfs that would be great.

**Comment by sebastianebarb** [comment]
![Boards and Commissions.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46ca9b9b318690e98ee7bb038752fd992055347a260ab0693cc7f33ab0487e021b4d44be445f0c44fbfcdc2ca3be3e258a0909ecd16f0e21c23b42a5aa9e0dfd50e474d412dcfce9c85ecafa3c2ced8a8a4d3f16041188f95933a5915985.png)

**Comment by sebastianebarb** [comment]
@reillyzlab and @paylakatel  please take a look.  My only major concern is the use of icons as most boards don't have one.  We can substitute for something closer to the grid of cards? https://patterns.boston.gov/components/detail/grid_cards--hub.html

**Comment by paylakatel** [comment]
Looks great - thank you! I think using the grid cards will be fine so we don't need to worry about icons. I'll talk to stakeholders about images for each board/commission. Will likely be easiest to use the cards with no icon or image and just text of their name, but if images would be great if feasible. Will let you know any comments after this weeks' meeting with the Clerk's and Policy Offices and close this issue then if we're good. Thanks again!
