### ISSUE TITLE
2018 Award submission

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#646]

**Comment by carolinestj** [comment]
https://docs.google.com/document/d/1ffmv300XRLxIvi9CsDOsJz0dlNvwxpwGe6xGeeLaPaA/edit?ts=5aabc7c1#
https://docs.google.com/spreadsheets/d/1N4umJWJ9n9EoV5MjIKWLGV86I-K9gCppX82DfI7nsbw/edit#gid=0
