### ISSUE TITLE
Proclamation

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#647]
Jake is looking for some assistance with the proclamation form (here's an example of one). We get requests for proclamations fairly frequently, and it's important that the formatting on these forms always stays exactly the same. People tend to have trouble sticking with the correct format making the submission process more time consuming and difficult. Looking for some sort of template/generator that would force people to stick to the template a little more and streamline the process. 

https://docs.google.com/document/d/1ygA9XZwTh5CC0hk72rgUnT-7L3opg60zt0LTo2og1yY/edit?ts=5aaab9fe#heading=h.v5djdh5pwt8f

https://docs.google.com/document/d/1jRPlEVyaOrX3qc_tWW3l-oe7ykrBC0JdW27bWkbyshw/edit?ts=5aaaba52

**Comment by reillyzlab** [comment]
Three potential options to connect google forms to google docs:
- https://chrome.google.com/webstore/detail/form-publisher/hgmhbdjdjoahflgfmfpjlgpplihlechm?hl=en
- https://chrome.google.com/webstore/detail/doc-to-form/paadgjaehgkbopbjfaomaophiphlmalh?hl=en-GB
- https://zapier.com/apps/google-docs/integrations/google-forms

Reilly will also ask Patrick for any recommendations

https://github.com/OSCELOT/Certificate-of-Completion
