### ISSUE TITLE
Awards list 2018

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#649]
- Add to roadmap
- update old list
- send to JF

**Comment by carolinestj** [comment]
https://docs.google.com/spreadsheets/d/1N4umJWJ9n9EoV5MjIKWLGV86I-K9gCppX82DfI7nsbw/edit#gid=0
https://docs.google.com/document/d/1ffmv300XRLxIvi9CsDOsJz0dlNvwxpwGe6xGeeLaPaA/edit?ts=5aabc7c1#
