### ISSUE TITLE
Age-Friendly  review and tweek.

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#657]
Contact: Nicole Chandler <nicole.chandler@boston.gov>

We have a few items for the business that we would like you to review for branding purposes. I've made them in Canva but I think because it's part of a team account anyone who tries to edit them can't access them. If I send you a PDF of them, is there a way you can edit them in a different program? I'm still working on trying to change the settings.

**Comment by sebastianebarb** [comment]
Attached are the business packet items for the Age-Friendly Business project. Please review for branding and layout changes. I don't think you'll be able to edit the documents in Canva because others haven't been able to and I've been trying to fix the issue with no luck. I've included PDFs and the links despite this issue. 

tips sheet
checklist
application form
business cover page
business data 

Can you have these completed by April 2? Please let me know if you need anything else.

**Comment by carolinestj** [comment]
https://www.canva.com/design/DACyqVQ4RUE/j97XXSg-vaXqqKtMDfN50w/edit
https://www.canva.com/design/DACyqYcUuSk/gbV00H1mJIBiRtY3GO9UwQ/edit
https://www.canva.com/design/DACypkrhFQE/8Y4f71wmCWIxxMksWlvskg/edit
https://www.canva.com/design/DACnZypMjDs/oFTCO8w1qX6GGRZ7-vQ1bQ/edit
https://www.canva.com/design/DACwyDY-xDs/CTT3NNFB5GlZC-z6c0vmVA/edit
