### ISSUE TITLE
Returning citizens collateral

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#660]
Contact: adam.wheeler@boston.gov

- [ ] Postcard
- [ ] One-pager for funders 
- [ ] Brochure

**Comment by sebastianebarb** [comment]
[DOIT Design Notes - March 20, 2018.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46ccbbb317c2a7ac9ce0b84de473ff802c55673e6929a239738da37aef0e3b535f5e46be5d4a1f06a3a3dc78e2a436628f5b58edd6680a73c33513f9b8d71dbe01b871de4b83e5b59850d2aa6c7bb3d4d216744b470a83ed5c33aa984eca59f34ce54550a7133463f43b.pdf)

**Comment by sebastianebarb** [comment]
@carolinestj try these patterns https://drive.google.com/open?id=1SGFeuoQjax_gKw9duPy4jDKgoPpxZEo5

**Comment by carolinestj** [comment]
Parent of #865
