### ISSUE TITLE
Earth day graphics

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#665]
Hi Caroline!

We wanted to provide the Press Office and other departments social media content to share for Earth Day next month. We've already drafted the text for the campaigns, and I was hoping you could create graphics for everyone to share as well.

Here's the copy - https://docs.google.com/document/d/1D-MoSActEpCpSWGrqHeZlVXnK7JzIeOWSlYtQZc1P-0/edit?usp=sharing

I'm open to your suggestion as to what graphics make the most sense based on our campaigns. I'm also open to how many graphics you think are needed. Ideally we'd have something available to Press starting in April but that's a quick turnaround time. Earth Day is on April 22nd.

Happy to chat if it's helpful!

Thanks,
Lauren Zingarelli

**Comment by sebastianebarb** [comment]
@carolinestj , I just spoke with @jfalvey.  She is going to reach out to Environment and BCYF to see what we have done in the past.  Please hold on movement fo this project till she gets back to us.

**Comment by carolinestj** [comment]
https://www.canva.com/design/DACy1m6i_m8/share?role=EDITOR&token=5cc-CgbRDPFLIXnhVLxBBg&utm_content=DACy1m6i_m8&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton
