### ISSUE TITLE
Fix header on Open House web pages

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#686]
Create a new template for headers for open house events put on boston.gov

Example: https://www.boston.gov/calendar/roxbury-open-house

Note: Most of the words are being cut off in current set up.

May be worth creating a template and sharing with ONS to use for future open houses as well.

**Comment by sebastianebarb** [comment]
![686_01Header Open House pages-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46becccc1cd2d2818ae8bb46b61ddf842c48675b2611b02e3095e22fba5136515e4d52be011a001ea9aacd39aca43977d95c0ce8846a5a7cc46811f9ba831fbd50ef248d1c8ca4a0980e91b6697abad2c51a7c0c0f0a8bff5734a59d4dc051f04de44a57a213242e.png)
