### ISSUE TITLE
Receipt redesign

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#687]
Your credentials are the following:
PRODUCTION / LIVE:
https://www.invoicecloud.com/portal/(S(yx1dvomnutej5qrcbmmqivxx))/BillerLogin.aspx

User: 136579
Password: Indianajones@13

TEST:
https://www.invoicecloud.com/portal/(S(czwuip0dupp4ae2qvsygwlet))/billerlogin.aspx?exit=1

User: Test136579
Password:  Indianajones@13

**Comment by duffy-james** [comment]
@sebastianebarb can we chat about this when you get a minute? Just need to know where I'm going.
