### ISSUE TITLE
Latinx Heritage Month design

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#700]
Contact: Natalia Urtubey
other contacts: Tania Del Rio, Alex Valdez

We will be hosting the Latinx Heritage Month Sept 15-October 15. We will need support with developing a flyer, spotlight, calendar & page on the website, and more!

https://drive.google.com/open?id=0B0RwQU94BhGeY2NHWktJM3kyS0k

parent of  #709

**Comment by sebastianebarb** [comment]
social media on canva
