### ISSUE TITLE
List of other governments brand guidelines

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#708]
https://docs.google.com/spreadsheets/d/1TToXD6QIPRtjgyhHrNmG-Tot4xAWlC1dP3fVjqiRwY8/edit?usp=sharing

Archive - https://docs.google.com/document/d/1fZni8MPASEGDK6zhJG6sQXfzvi2UWJ6YoZctO7L7O2U/edit?usp=sharing
@jiaoruijiang the above doc is what we knew of off hand.  feel free to move to a sheets doc and update as needed.

**Comment by jiaoruijiang** [comment]
https://docs.google.com/spreadsheets/d/1TToXD6QIPRtjgyhHrNmG-Tot4xAWlC1dP3fVjqiRwY8/edit?usp=sharing
