### ISSUE TITLE
Sample of City Council minutes

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#715]
Hi,
Kevin asked me to send you a sample of the City Council meeting minutes. In the past they were edited, reformatted and bound. 

Please let me know if you have any questions

Thanks

Nicole

**Comment by carolinestj** [comment]
[April 5.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46c984882a8ec3fccda5fd53b652fa912a5265296b51f42820d2b62de81723530a5f1bae40585d15a9fd8f78afa42062c80d55b98e30063e937f03a6aa8317b500bf228e4d85b5bb8b45c5ea3e37aa.pdf)

**Comment by sebastianebarb** [comment]
@jfalvey - you and Kevin Coyne were talking about this during the interviews.  I don't know what we should do with it.
