### ISSUE TITLE
Digital team awards

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#717]
The digital team to set up an end-of year award to honor departments who have done good Digital work.
Categories:
- [ ] Most improved on social media
- [ ] Best campaign
- [ ] Best use of Canva 
- [ ] Most new groupies
- [ ] Best blog post
- [ ] Closest to 8th grade reading level
- [ ] Most engaging deaprtment
- [ ] Acronym remover of the year

**Comment by jfalvey** [comment]
😁
