### ISSUE TITLE
We are Boston Gala

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#719]
Hi Sebastian, Caroline,
I am looking for time with you to show you samples of our WAB printed materials.
Will be great to get your suggestions.
My calendar is pretty open next week Thursday 5-10 or Friday 5/11.
Please let me know if we can meet.
Thanks Mayra Canetti

**Comment by carolinestj** [comment]
[WAB17_Paddle.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46dfb5b872d5bc998eedbb4fa11fbcd6395428792c07b7692ac7b67fbc122c540a584ba4430d5f11fef88929f7e33876d95519f1c32f0e2a92624cf5f2d75dad0ba8218d4584b3be8f4bc0ef3421e48e894d2c53.pdf)
[GALA INVITE.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cfb5b602c2aa87b9c08b66e611b2843b492d762a10e17132d0b42bef152e04585a46ae14580a46fdf98b7af3b23a23834e17ff933c0120996048e6edc00db513bb26814e80b4b98d4cc7e1352dee89885d73.pdf)
[pWAB_4x6Board.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46f8a3bb01bdd7b1d9cbb042b659b2d86b56357c2301a03f32dfa17de8412b565a0a49a9495a0a44a9fb882ba4e769748c0f02ffcd7f1d2598694ef1e1c84afd13b0328a498fb7b98849c7e83a2cef83864e380c48.pdf)
[WAB_podium.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46dfb5b81c928cad86fcb201e81fe086264c22703d46f96925d2e078e8177e565a574cf9410d5d45fcfbd87ea2b06f79984019af80330b2b9b645bf9fa9015ad00bd2a8a4a87b3bb8a4bc9e0352ce58c9d02.pdf)

**Comment by carolinestj** [comment]
https://drive.google.com/drive/folders/1NEsLUCFoweVkLdsaDMmMw7LbQqVwNA0T

**Comment by carolinestj** [comment]
![Save the Date.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46db958c26c297a18aa99b42b058b2d86b56357c2301a03f32dfa17de8412b565a0a49a9495a0a44a9fb882ba4e769748c0f02ffcd7f1d2598694ef1e1c84afd13b0328a478fb7b98849c8e13822ef8d8f483c0c48.png)

**Comment by carolinestj** [comment]
Notes from meeting May 11 

Make the collateral on brand 
(Also take out the Caribbean part)

- invitations (tri fold) 
- booklet (might just have to do the cover and maybe layout mockup) 
- Podium sign 
- save the date (digital) 
- silent auction sign

Deadline for save the date June 1

**Comment by sebastianebarb** [comment]
We have a date and a venue confirmed for the We Are Boston Gala 2018:

Tuesday, November 27, 2018
The Westin Boston Waterfront
425 Summer Street, Boston, MA 02210

For more information contact:
AE Events at 617.879.9779
www.aeevents.com
