### ISSUE TITLE
Report on Issues with physical freedom trail (Internal use only)

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#723]
As you walk the trail we would like you to take notes where the physical line of the trail breaks, is damaged or disappears. This is critical to launching as there will be a lot of attention to the trail when we start promoting it.

**Comment by jiaoruijiang** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/1S8r3zKE9elkn7bn7BPIS3IBOfu9TlfQ3HEzFiP-Oyng/edit?usp=sharing

Report:
https://docs.google.com/document/d/1Q1kOZGLU77wzyOet9m20UymrOObtsuOGqi5HIgI9HMQ/edit?usp=sharing
