### ISSUE TITLE
Freedom Trail Way-finding testing

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#727]

**Comment by jiaoruijiang** [comment]
Testing Feedback:
-  "Freedom Trail" text is helpful for visitors who are not aware of which sites are on the trail (i.e. they are not looking for the sites, just doing the trail)
- Site icons are helpful for people 1) to know what buildings to look for and 2) who don't speak English. They stand out against other signs around that are mostly words. But the icons don't need to be too big.
- People generally want text (site name) and arrows to be big on wayfinding signs
- More people think the horizontal displays of previous and next location is easier to understand
