### ISSUE TITLE
Report on freedom trail site interaction

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#729]
There are 16 sites along the trail. They have a hard time converting people from moving along to trail to entering their spaces. We need you to come up with a plan that will help each site bring in more people from the trail.

**Comment by jiaoruijiang** [comment]
https://docs.google.com/document/d/1mBKnthYLJiIj8oYkqTx56eS3Oj-P1PPcS_PO67c7Xjs/edit
