### ISSUE TITLE
plastic bag illustration / graphic

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#739]

**Comment by sebastianebarb** [comment]
Illustrations should be for the website.  We will create a separate ticket for any campaign

**Comment by carolinestj** [comment]
Boston recycling plastic bag postcard  

![postcard front.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46f89b89378182bb8ba9b951ab53e4d665043761260ea62864c7b96aea157851585a1bab44505d11fcac8b2aa6b46d258e5a58e4c3714d36976345f3e5db55ea43a82a994e82bcbd8f4fc0e0352de0838b493b1c1755.png)

![postcard back.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46f89b89378182bb8ba9bd42a756b2d86b56357c2301a03f32dfa17de8412b565a0a49a9495a0a44a9fb882ba4e769748c0f02ffcd7f1d2598694ef1e1c84afd13b032894e8fb7b9894cc8e03522ee898a493c0c48.png)
