### ISSUE TITLE
Citizenship day 2018

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#747]
Contact Carol Leon

- Update the files from last year with new dates
- bilboard 
- program 
- mbta sign 
- flyer 

more details to come

**Comment by carolinestj** [comment]
Hi Caroline, 

Thanks for meeting with me today!

I've attached the following documents to this email:
Brand Guidelines
Citizenship Day 2017 Flyer * 
Citizenship Day Car Card *
Citizenship Day Billboard (English and Spanish) *
Photos for Immigration Clinic Flyer 
*Update the date for Saturday, September 30 

Let me know if there's anything that I'm missing!

**Comment by carolinestj** [comment]
[MOIA_StyleGuide_F.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46c5bbb302bdb0bd96e5ba64b154f4911660653f6b14b1247a80e03cfd183954580c4eab440d5841f4fbdc2bf3b43d70880d5ee9d73e5666da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3f2de08f8d483b1c061e8eed10.pdf)
[Citi Day Billboard 07272017-Spanish.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cb9d8e2ac2a7a896a99d4aa851f29b285423337953f17c22d5b27ff2716b0001060df453444d04bea6d37ef5f22e7a98590cbed16a5a21c13819aeed824abd00ba22da1a81b0ef835edcfa7f74b9dfd0126754505a9bf54f34a7934acd5afe4ce54f52a11b3f61ef647b.pdf)
[Citi Day Billboard 07272017-English.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cb9d8e2ac2a7a896a99d4aa851f29b285423337953f17c22d5b27ff267750603060df453444d04bea6d37ef5f22e7a98590cbed16a5a21c13819aeed824abd00ba22da1a81b0ef835edcfa7f74b9dfd0126754505a9bf54f34a9934acd5afe4ce54f52a2173662e3647b.pdf)
[1816 CarCard CitiDay Final Proof 2.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46b9cccb75c2a0a89dcabe51a01dd39d3d4f0372304485227e84ef688f50740e094f4cbe5d4a1f06a3a3dc78e2a436628f5b58edd6680a73c33513f9b8d71dbe01b871de4b83e5b59850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca50f14fe34a53a216346af43b.pdf)

**Comment by carolinestj** [comment]
Car Cards: Size is 28” wide x 11” high. The live image area is 9-7/8” x 27”. Produce on 18 points coated one side (C1S) and varnish. 
Billboard: Refer to file attached
[Bulletin 14x48 - art specs (1).pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ca81962f8797a081a9ee17bc09a8d4640626613d44b03b7586f068f7133243434d0eee1e020a17b8eb8339a3b16f708d595eead4655d21c66813adb8804eea05bc73825d99a4fedb1294b7607caddecd5d340c041183fe5837a99943cd58f14fe64c57b65e.pdf)

**Comment by carolinestj** [comment]
community partners doing design and branding

**Comment by sebastianebarb** [comment]
Since I know that Caroline is away, I am reaching out to you because I need a minor edit to be done on the document attached to be made. I just need the Goodwin logo to be removed. Could you give me a hand with that?

**Comment by sebastianebarb** [comment]
![MBTA AD-01 (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c5b6ae02c2a28dc2b9ee03ec0cb9d665043761260ea62864c7b96aea157851585a1bab44505d11fcac8b2aa6b46d258e5a58e4c3714d36976345f3e5db55ea43a82a994e82bcbd8f4fc1e13f20ee898849381e1755.png)
