### ISSUE TITLE
Redesigning paper forms testing

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#756]
We need to user text the updated paper forms ideas. 

All design files: https://drive.google.com/drive/folders/0B0RwQU94BhGebGluZDNTSzN0aFE?usp=sharing

**Comment by jiaoruijiang** [comment]
https://docs.google.com/document/d/1k3POHl3nsG0LgyefoTU0gJeLYtOzITI6ur48kVBJIco/edit
