### ISSUE TITLE
Recycling Do's and Don't

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#759]
Contact: Chris Coakley 
Create a social graphic that shows what to recycle

**Comment by carolinestj** [comment]
[Recycables for Twitter.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46da91993a8182ab83ecac03a252e2d41d512e673d01b1693cc7f33ab0487e021b4d44be445f0c44fbfcdc2ca3be3e258a0909ecd16f0e21c23b42a5aa9e0dfd50e474d412dcfce9c85ecafa3c2ded8a8a4d371e0d1a8efd5a35a49d5985.docx)

**Comment by sebastianebarb** [comment]
[Uploading 1.png...]
[Uploading 2.png...]
[Uploading 3.png...]
[Uploading 4.png...]
[Uploading 5.png...]
[Uploading 6.png...]
[Uploading 7.png...]
[Uploading 8.png...]
[Uploading 9.png...]
[Uploading 10.png...]
[Uploading 11.png...]

**Comment by sebastianebarb** [comment]
![11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b9c5d86fc093bb80e3ba40b01faad67c1124237e51a67c25ddb12def4729505f5d1ff9455e0c4deee59b69f7e8682fd70541b8937f5566c73a1badbd811eb704bc248e4a82b3b99801.png)

**Comment by sebastianebarb** [comment]
[Uploading 1.png...]
[Uploading 2.png...]
[Uploading 3.png...]
[Uploading 4.png...]
[Uploading 5.png...]

**Comment by sebastianebarb** [comment]
![1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b9d6d6619291a685ecbc57e607b2c17e4577247c01f47e28d7e678ba102a515d0e1ba8470b5656e0ebcb7af8e2632dd3165eafc3674d75c13710a9bb8317ba07bc238c4783b4aec7.png)

**Comment by carolinestj** [comment]
Make changes to fit this document 

[20180802083522158.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46bac4cb7bd2dbf9ddb9e710f10fa2c57c1e653f6b14b1247a80e03cfd183954580c4eab440d5841f4fbdc2bf3b43d70880d5ee9d73e5666da2f53fde6d640e258f075c95d8fa4bd8246c1ed3e26e58a884d371f041e8fed10.pdf)
