### ISSUE TITLE
Education Cabinet postcard

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#770]
https://drive.google.com/drive/folders/1-vgC4TtZxVV64YVrjVS7S2wOD295a9RJ

Hello Sebastian,

My name is Roy'al and I am an intern in the Education Cabinet. Right now, I am designing a postcard flier for students to fill out where they can let the city know where they need support in terms of career development. With this I could start to develop prototypes that can meet those needs. My design is below showing the cover of the postcard and two different versions of the back. I was hoping to hear your thoughts on how to improve the design, and which of the two versions gets my message across better. If I'm being vague in any way, please feel free to let me know and I'd be happy to elaborate. Thank you!

**Comment by sebastianebarb** [comment]
I'm still hoping the Education Cabinet logo could be added to the back of the postcard instead the city logo. I don't think Caroline got to it before going on vacation, and was wondering if you could?
