### ISSUE TITLE
Prototype for My Neighborhood

### ISSUE THREAD

**Issue by caroline-trier** [CityOfBoston/design-team-workflow#771]
**Requirements for the first iteration include:** 
(mock for North End or Dorchester if you want)

An address input (it has a drop down that autofills the address as you type with the top option being "current location") with a back to search option or ability to change typed address.

Static Dash - Title "My Boston"
1. Neighborhood liaison
2. City councilor
3. next trash day
4. next street clean
(we can experiment with others, see if street/trash is repetitive with calendar)

Calendar - Title "Upcoming Events"
1. Trash&Rec Calendar (add hazardous waste drop days and recycling rules link)
3. street sweeping (schedule)
4. BCYF (events)

Map
1. BCYF (mapped locations) - pop up could be name and address, maybe an example of facility ammenities
2. Property Info - pop up with current assessed value and owner
3. Open spaces (parks)
4. Libraries
5. Food markets
6. Wicked wifi

Links - Title "Learn More"
1. Neighborhood Safety Information
2. Property Information
2. "can't find what you are looking for? report to 311" link - maybe as a more prominent button in center of page below the other links
3. New to City of Boston Guide - [moving](https://www.boston.gov/moving)

Add a "toggle" button

**Next steps after initial testing:** 
- Dashboard info is limited to five values shown, but calendar, map, and links could include a lot of information that will require a filtering technique (by category, distance, user type)
- Interaction and popups

**Other cities with tools that serve a somewhat similar function:**
Asheville’s [Simplicity](https://simplicity.ashevillenc.gov/address?search=285%20Montford%20Ave&id=202716&entities=undefined&entity=address)
Louisville’s [MyLouisville](https://louisvilleky.gov/)
Savannah - [OpenNeighborhoods](https://www.savannahga.gov/2365/Open-Neighborhoods)
Raleigh - [MyRaleigh](https://www.raleighnc.gov/home/content/ITechWebServices/Articles/FindMyService.html)
[PortlandMaps](https://www.portlandmaps.com/detail/property/1535-NE-128TH-AVE/R220144_did/)

**Visual inspiration:**
compiled [here](https://docs.google.com/document/d/1YoXgGbTFj3l-ZRnsZ5fxjOUBC3XJPKg04WvDDH-2kK0/edit?usp=sharing)

**Comment by sebastianebarb** [comment]
[My neighborhood test.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c58dda2d878aae87ebb051ac52ff90695222603d46ef696097ec22ba416f43554d4bab12585841a9fe8c23a4e33c25885d0bef80385b72953403b0aac04ee155e57dd205d0f4ae805ec1e03724e2888e4b3718051d89f95f37b2d4.pdf)

**Comment by sebastianebarb** [comment]
[My neighborhood test.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c58dda2d878aae87ebb051ac52ff90695222603d46ef696097ec22ba416f43554d4bab12585841a9fe8c23a4e33c25885d0bef80385b72953403b0aac04ee155e57dd205d0f4ae805ec1e13724e2888e4a3f1a041981f75436b2d4.pdf)

**Comment by caroline-trier** [comment]
latest version: [https://drive.google.com/file/d/11yRDkTDUjBRwd58_FQ3FLiye8HvWXKWA/view?usp=sharing](url)

**Comment by caroline-trier** [comment]
Follow up on Cards conversation - 

Here are the cards and the possible links. Please share your Sketch files and I can mock what’s in my brain so we can compare and discuss in more detail than today’s more overarching thoughts.

Highest priority cards:
1. TITLE: Trash and Recycling
           Personalization: this is your next trash day, next recycling day, nearest compost site, upcoming hazard drop day
          Additional links: learn more about rules, how to live more green 
2. TITLE: Upcoming Events
              Personalization: As we currently have
              Additional links: Add a “see more” link at bottom
3. TITLE: Safety [This one is hard]
             Additional links: cityscore, district public safety officer update
4. TITLE: Property Information
            Personalization: Owner, Value, Current permits
            Additional Links: Assessing tool, rentsmart tool
5. TITLE: Parking
           Personalization: next street sweep day, upcoming permitted disruptions
          Additional Links: how to get a parking permit, how to pay a ticket
6. TITLE: Get Involved
          Personalization: your councilor, your liaison, you polling location, you neighborhood association

Secondary importance later:

1. TITLE: Out and About
          Personalization: closest transit, closest food access points (markets, pantries, food trucks), closest parks, closest water fountains, closest bathrooms
3. TITLE: Community Resources
          Personalization: closest community garden, closest BCYF, closest schools
