### ISSUE TITLE
Chinese holiday Bs

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#778]
Contact:  Danchen Xu

Hi Sebastian,

It was nice talking to you during the digital team meeting. I am excited for the possible synergies moving forward. Below are the major Chinese holidays that Chinatown celebrates. It would be awesome if we could create some official postcards or images and distribute them during each holiday!

Chinese New Year (February)2019 will be the year of Pig, and 2020 will be the year of Rat

Qing Ming Festival (April)

Dragon Boat Festival (June)

Mid-Autumn Festival (The holiday is in September, but Chinatown usually celebrates it in August, too)
https://drive.google.com/drive/folders/13LHKsR6rvJYIVaYtT2sZdXnR4C4HO5Fr?usp=sharing

Double Ninth Festival (September)

**Comment by carolinestj** [comment]
Thank you for the support! I appreciate it very much. I haven't thought about the size as much. The original idea was to create some images that will be adapted to postcards, bigger screens, tweeter, flyers, etc. Though postcards will be used more often, I want to keep the flexibility. Do you have any suggestions? 

And I'm really happy that you brought the up the phrases. Can't believe I omitted that bit. I created this document to include English, Chinese, and Vietnamese languages and phrase for the images: https://docs.google.com/document/d/1YJqt8om4OKvGVVgJEBCng5SXKwXUdW7XuH-JrdtV-xA/edit?usp=sharing I hope it helps. Chinese and Vietnamese are the two that the City is actively working on. 

Thanks again for your help. Please let me know if there is anything else I can do to make this easier for you!

**Comment by sebastianebarb** [comment]
Just a few notes:
For the Korean mid-autumn one, the language should be "새해복 많이 받으세요!" My apologies that in the google doc I messed up the space between characters. My Korean friend' grandparents caught it.
It would be nice add "from the City of Boston" to all the images.

**Comment by sebastianebarb** [comment]
![lantern festival -01](https://user-images.githubusercontent.com/20642299/44602906-0a605180-a7af-11e8-95f2-a523f4924e50.png)
![lantern festival -02](https://user-images.githubusercontent.com/20642299/44602907-0a605180-a7af-11e8-82fe-392242180d72.png)
![dragon boat festival text-01](https://user-images.githubusercontent.com/20642299/44602908-0a605180-a7af-11e8-8af3-75a9eb77f303.png)
![ching ming festival-01](https://user-images.githubusercontent.com/20642299/44602909-0a605180-a7af-11e8-94db-a0172ee4c27a.png)
