### ISSUE TITLE
Emergency Response Graphics: blog post

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#805]
I wanted to start an outline so we had something down. Feel free to add.  

https://docs.google.com/document/d/1aYNzsWSomheRIN-8-1HVJOBzPSUgJyDXD4ufH2LumQo/edit?usp=sharing

**Comment by jfalvey** [comment]
Blog post drafted yesterday 8/20, needs (would be nicer with) animated gif of a few examples. Second page of outline Sebastian created: https://docs.google.com/document/d/1aYNzsWSomheRIN-8-1HVJOBzPSUgJyDXD4ufH2LumQo/edit?usp=sharing

**Comment by carolinestj** [comment]
![Emergency-tips.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cd999f318586a78cf0f257ad4de3d665043761260ea62864c7b96aea157851585a1bab44505d11fcac8b2aa6b46d258e5a58e4c3714d36976345f3e5db55ea43a82a994d87bcbd8f4fc4e13b25e48b8c4d391d1755.gif)
