### ISSUE TITLE
Update URL on 311 graphic on City Hall elevator screens

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/design-team-workflow#847]
On the City Hall screens by the elevators the 311 graphic displays this URL: cityofboston.gov/311

We should change this URL to be boston.gov/311 which redirects to cityofboston.gov/311

**Comment by sebastianebarb** [comment]
![311_CityHall Screens.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46bbc5cb1ca18abd96c1be4fa81dc3973b43227d3a46ef696097ec22ba416f43554d4bab12585841a9fe8c23a4e33c25885d0bef80385b72953403b0aac04ee155e57dd205d0f4ae805ec2e93724e2888846371e0d198cfa5c34b2d4.png)
