### ISSUE TITLE
#5onMain

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#853]
Contact: crystal.torman@boston.gov
Contact 2: taylor.connolly@boston.gov

Discription: For this year's shop local holiday campaign Mayor Walsh and the Boston Main Streets will be partnering with WCVB (Channel 5) to relaunch #5onMain. We loved the graphics you put together for last year's #LetsAllShopSmall and was hoping we could revisit them for this campaign. We'd obviously need to change the hashtag and add Channel 5's logo (I will request this from them), and we're hoping we could add a few designs that featured an eating/restaurant scene and a couple of designs that are more generic and just a frame. That way districts can customize their social media posts to match the make up of their districts.

**Comment by carolinestj** [comment]
- swap the hashtag to 5onMain
- add channel 5 logo 
- add a restaurant graphic  
- Make a generic graphic where districts can customize text themselves (canva probs)
