### ISSUE TITLE
Boston Info logo

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#856]

**Comment by sebastianebarb** [comment]
![fireshot_capture_77_-_alexa_skill__city_of_boston_informatio__-_https___mail.google.com_mail_u_0__.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46ee9d8826918ba69bd6bc42b449e5862c79702416499c2a7c80fb2980517008030321c312011b0d93a6df44f4e97f34d50264b48f3b00369b6c55f5e7ed70a26ee264cf0fc6d9d3e51191b1613bb0d4d018624b1b4bd6a23268f1c017a71d994b8e2247b8017621b92c632f03861467296c3426acf98a51828d62f1ba452d57c8e1b5af1214f275cadb1b33320b0ff5776bff57189b6a8a447957eab0c7f5134e0c1700ceebcadfafa2.png)

**Comment by sebastianebarb** [comment]
![Asset 3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c987892696c3facda5fd53b652fa912a5265296b51f42820d2b62de81723530a5f1bae40585d15a9fd8f78afa42062c80d55b98e30063e937f03a6aa8318b500bf23834b87b2b58b44c5ec3f37aa.png)
![Asset 1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c987892696c3f8cda5fd53b652fa912a5265296b51f42820d2b62de81723530a5f1bae40585d15a9fd8f78afa42062c80d55b98e30063e937f03a6aa8316b500bf23834b87b2b58b44c5eb3537aa.png)

**Comment by rachelbraun** [comment]
Decision made to go with Option 2.
