### ISSUE TITLE
Snow Brochure Edits 17-18

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#863]
Contact: Chris Coakley 
Due: 

Updated the snow brochure from previous years

https://docs.google.com/document/d/1KCpri_Ijzj0BbEW1TivkO4MfXn7M7Hlwm9WMiwjdK6A/edit?ts=5bb78955

**Comment by sebastianebarb** [comment]
[Snow__2018_2019V2.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46db9a9534bdbcfbdfb8e77cf60da1cd1f14653f6b14b1247a80e03cfd183954580c4eab440d5841f4fbdc2bf3b43d70880d5ee9d73e5666da2f53fde6d640e258f075c95d8fa4bd8246c1ed3e2ce48c8f4a3d1f041e8ced10.pdf)
