### ISSUE TITLE
Let's go red sox graphic

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#867]
Contact: Norah Doherty 
Due: by friday

remake the pats super bowl graphic to a red sox one 

add hotdogs and baseballs

4000 pixels by 2250 pixels

**Comment by sebastianebarb** [comment]
[Uploading red sox-01.png...]

**Comment by sebastianebarb** [comment]
![red sox-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46fa919e63918cb1c2b9ee01e81fe086264c22703d46f96925d2e078e8177e565a574cf9410d5d45fcfbd87ea2b06f79984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86bfb48d49c4e13527e08a9d02.png)
