### ISSUE TITLE
Language and Communications Access Brochure

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#873]
It was so great to meet you and your team last Friday. The DoIT team has great energy and I'm really looking forward to working with you all. 

We didn't get around to talking about this much, but I'm hoping to get an LCA brochure printed soon. The content copy is nearly finished. Am I right to assume that the next step is take this to DoIT for design? Please let me know if this is not correct. 

If it is, how can I make your job easier? What would you need from me? 

I apologize for my late response. LCA is the acronym for our office/program, Language and Communications Access, which I am helping launch this year. 

Manar Swaby and I will be approving the final design. 

We have funding for the brochure from our own program budget. We're thinking about doing a test run first on regular paper and then mass printing professionally later on. The test run would be seen by city staff throughout the internal training period this year. The professional brochures would be the staple collateral for public consumption. Let me know if you have any other thoughts on this. 

I don't think there are any other details from my end. There isn't a hard deadline for when we want to make this happen, but sooner is better than later. I'm hoping to finalize the brochure content today or tomorrow. 

How long would the design process take on your end?

**Comment by carolinestj** [comment]
Word doc:

[125516c66e82c728ace21e0d46cb9b9437878dbdcfcaad46a549f99b277967430b44b42a6480f168bd4b770d4f0610ef141a1b56e0ebc969f9ec6923ce4e01ffd46a0c74c13844abbd8a1dea01ef228a4f87e7e98e4a93e12f39f5c9de116a415841c3aa1f27aa8b4acf52f74ee54c50a6143e66e674367.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46b9c6cf76d3d5aad9bfba1bf65ea7c6714724767b55a67b74d1b52bbd1b79585b5c49a446500b16a8aadf78f7e768748c0d0ee9d83b567d943f16abb18418bb02ba728f4bd7b2bedb4ac4e03d73e68d871d6a1a571f8eff0931f6994dc958a31de04954f5126466e023362915c71773253d6e73f8fad65484d635a0ef102e009eb7e0fc4712f27bdc9408726b515ffb7860e10a0b8834cd17785cbee3c6ff1f1d0c4809cabec48eb4e78e35242c444f51c274ed5b4d038f9502967995629c043f7b4f7a068d1c94ad30d79a90ad3d26d5e6bb313e6ac646cd8ad6edccdd5a5cedeebaa2d695d3344e190dcd939ece79fd19d1888568759420062828958df0daef20b3f9df979ae494b06bda1acf950f3ee6d227d0b3e1aa51938696601f14f99e38ea63b33e08ff1724d7c0b888e2c152be943744c3d2.docx)

photos: https://drive.google.com/drive/folders/1Nq6iyaTBHfezOcaqmpgxe9xXJchQ4TlR

**Comment by sebastianebarb** [comment]
[873_01_Language and Communication Access brochure.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0c3c91cd2d296a3e8b144b15cf791694729776927ac267d90ed21bc436f0800015edd120b0a07bfe9db69f9e56435c80919f1c32d1d2b9c6842e8aa880dba06e9208c4ad0b1b9824e95e86827e68b8d1e6b1a034b80ed4127e2c8159c07ab12ab1817b6192462ef7c377943901c75286a6f27aaf8df44ca.pdf)

**Comment by sebastianebarb** [comment]
Feedback: Tue, Dec 11, 9:27 AM

- [ ] Change the introduction to "The City of Boston is collecting this information to support the needs of all residents. This survey focuses on language, disability, and childcare services. 
- [x] Please, check any and all that apply."
- [x] Change to a lower case p in the word "program" for 'Center-based Program' and 'Public school /Head Start Program' options.
- [x] Can we remove the blank second page from the file?
- [x] We can use this shortcut for the link: boston.gov/language-disability-childcare-survey  
- [ ] Translate the language names at the bottom of the page:
Chinese : 中文
Vietnamese :  Tiếng Việt
Haitian Creole :  Kreyòl ayisyen
Portuguese : Português
Cape Verdean Creole : kriolu
- [x] Need a comma between "Disability" and "and" in the title

**Comment by sebastianebarb** [comment]
https://drive.google.com/drive/folders/1j4GvIkf3yRGvBAUBEdyEkuXfgITk4V3F?usp=sharing

**Comment by sebastianebarb** [comment]
[Uploading 873_03_Language and Communication Access brochure.pdf...]

**Comment by sebastianebarb** [comment]
Brochure edits:

DESIGN
- LCA is becomings a department Summer 2019
- Add mayors name 
- remove ONS

TEXT
- Disability
There are more than 84,000 people in Boston with a disability related to mobility, independent-living, or communications. About 22% say they are Deaf or have a hearing difficulty and 21% report that they are blind or have a vision difficulty. The LCA program works closely with the Disabilities Commission to make sure everyone, regardless of disability, can access what they need from the City.  

- Establishing Language and Communications Access for City Services 
 Ordinance 2016 Chapter 13

**Comment by sebastianebarb** [comment]
Front Cover: 
Replace "Language and Communications Access Program" to "Office of Language and Communications Access"
Add Mayor's Seal to include "City of Boston" and "Mayor Martin J. Walsh" text
Update and add Office of LCA logo
Back Cover: 
Replace "Language and Communications Access Ordinance" with "Establishing Language and Communications Access for City Services ordinance"
Update logo to Office of LCA logo
Update office title
Inside Flap: 
Replace second paragraph with: "There are more than 84,000 people in Boston with a disability related to mobility, independent-living, or communications. About 22% say they are Deaf or have a hearing difficulty and 21% report that they are blind or have a vision difficulty."
Inside Panel A: 
Fix typo: "If so, we encourage you to reach out and request an accommodation with any City of Boston department.
Inside Panel C: 
Replace second paragraph with: "If you need access to any of these services or equipment, please contact the department directly at least two weeks in advance."

**Comment by sebastianebarb** [comment]
Hi Sebastian, 

I finally have an update for you on this. We are going to keep the "LCA Program" title and logo so we can get it printed asap. We are going to print in-house for the first batch. Could you send me a PDF as well as the Adobe file so our translators can input translations directly into the design? 

Thanks so much. 

Best, 
Jenni

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=1Z2M8tL1KSxP9ckMUEseor74k-MKZqhRp&authuser=sebastian.ebarb@boston.gov&usp=drive_fs

**Comment by sebastianebarb** [comment]
Hi Sebastian, 

Could you update the following in the brochure? 

Front Cover:
We want to replace the seal with a city logo that has both "City of Boston" and "Mayor Martin J. Walsh" text in it. If it can only be one, Mayor's name should take precedence. 
Back Cover: 
Replace "Language and Communications Access Ordinance" with "Establishing Language and Communications Access for City Services ordinance"
Update office title to capital case "Language and Communications Access program"
Inside Panel A: 
Fix typo: "If so, we encourage you to reach out and request an accommodation with any City of Boston department.
Inside Panel C: 
Replace second paragraph with: "If you need access to any of these services or equipment, please contact the department directly at least two weeks in advance." 
Also, the PDF you have sent has the position markings all over it and would not be printable. Could you attach an unmarked copy? 

Thanks so much!

**Comment by sebastianebarb** [comment]
[873_04_Language and Communication Access brochure.pdf](https://github.com/CityOfBoston/creative-team-workflow/files/3114066/873_04_Language.and.Communication.Access.brochure.pdf)

**Comment by sebastianebarb** [comment]
Two quick things with the brochures:
Under "we can help you with" in all language versions, there are places where the colons are missing from the mini headlines
Also under "we can help you with" remove any periods you find in at the end of the little blurbs so they are all consistent
