### ISSUE TITLE
enchanted trolley tour downtown/chinatown flyer

### ISSUE THREAD

**Issue by DACole** [CityOfBoston/design-team-workflow#877]
Contact: Danchen Xu

Location based flyer for downtown/chiantown. 
try adding some cultural elements 

The date will be Sunday, December 2nd, at 1:45 PM. But I will start crowd building from 1 PM and end after mayor left -- probably around 3 PM.

**Comment by carolinestj** [comment]
20 ft by 30 inch bilingual banner

**Comment by carolinestj** [comment]
https://docs.google.com/document/d/1MHiNfMuCRo4Df0BwHLxqjvBfBmtZxfK-M2EN9vUpocM/edit?ts=5bd0dc99
