### ISSUE TITLE
Banner images for food access

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#881]
The food Acess page looks kinda dead.  can we add in some of their branding?

**Comment by carolinestj** [comment]
![hero-image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46e091882ccf8aa48eeeba01e81fe086264c22703d46f96925d2e078e8177e565a574cf9410d5d45fcfbd87ea2b06f79984019af80330b2b9b645bf9fa9015ad00b22a8a4a81b6b8834bc2e8352ce18d9d02.png)
