### ISSUE TITLE
Translation / MOWA City Census Insert

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#883]
Contact: Manar-ul Islam Swaby
Translation City Census Insert 8.5x11
- https://docs.google.com/document/d/1s2ajVFlOKHMA_36mrqLWCwIukojUWEUjGLOlNjGP9hs/edit?usp=sharing

One additional insert as we have 3 of our own pieces being inserted as is.  The actual census form with address, the instructions and the return envelope. (300,000 homes)
The outgoing envelope is a #10 standard window envelope (4 1/2 in x 9 1/2 in)

**Comment by sebastianebarb** [comment]
Hi Sebastian!

Hope you are well. The Language Access team and us have gotten on the same page about what our insert will look like and we were hoping to sit down with you and get you up to speed on our conversations. 

In summary:
We want to do a single page, printed on both sides. 
We want one side to be Spanish and another to be English. 
I am attaching the English and Spanish versions of the MOWA survey (two tabs). 
I am also attaching the English version of the LCA survey. Spanish to be sent shortly by Manar/Peilun.

Our question to you: Is it possible to fit it all?
Please let us know a good time to meet with you. We think it may be useful for us to talk through our thinking with you.

ttps://docs.google.com/spreadsheets/d/1Rv5G5djBtvtxT_oi2bsey1Phr8mP7MObLi_2B5Vvnpc/edit?usp=sharing

**Comment by sebastianebarb** [comment]
A single page, printed on both sides. 
One side to be Spanish and another to be English. 
MOWA: https://docs.google.com/spreadsheets/d/1Rv5G5djBtvtxT_oi2bsey1Phr8mP7MObLi_2B5Vvnpc/edit
LCA: https://docs.google.com/spreadsheets/d/173ztsXgy3CuMZNR6BW-V2vN3JcEcYHWkJg1ztF8KmPk/edit?usp=sharing

**Comment by carolinestj** [comment]
Photos: https://drive.google.com/drive/folders/1eB8jMxCDAqv73Ml16hI9t-_3FWxUGGx-

**Comment by sebastianebarb** [comment]
[883_01_Census Form .pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0ccc91cd2d296acecb150b14eb0b226542a336b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e3898e4b3a1c031d80fe5827ed.pdf)

**Comment by sebastianebarb** [comment]
[883_02_Census Form .pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0ccc91cd2d196acecb150b14eb0b226542a336b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e3898e4b3a1d0d1d81f95e27ed.pdf)

**Comment by sebastianebarb** [comment]
Tiny typo: "We are collecting this information to learn families' needs" v to learn about families' needs
Can we change the word "citizens" to "residents or persons above five", especially given that we are not wanting to limit ourselves based on a person's status or anything of the like
Can we move the row "Write the language spoken by each person" up to be second and to say "Languages spoken other than English"

**Comment by sebastianebarb** [comment]
[ceensus notes.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46eb919f2d9196bacfe7b057a14eb2d86b56357c2301a03f32dfa17de8412b565a0a49a9495a0a44a9fb882ba4e769748c0f02ffcd7f1d2598694ef1e1c84afd13b032894f8fb7b98e4ec7eb3c26ef898a493b0c48.pdf)

**Comment by sebastianebarb** [comment]
Hi Sebastian -- here's what we came up with for the last question: From the above options, what is your preferred childcare option? Explain if different for each child.

Would it make sense to make the write in box a lighter color with a border around it so folks know to write in there since we're eliminating the "please write in below" instructions? 

[883_04_Census Form .pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0ccc91cd2d796acecb150b14eb0b226542a336b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e389884b361e031c8cff5527ed.pdf)

**Comment by sebastianebarb** [comment]
- [x] On the 'Home-based provider’s home program' We need it to say "Home-based provider program".
- [x] "Languages spoken other than English" to "Languages used other than English"
- [x] "Has independent living" should be "Has independent living difficulty"
- [x] The last line describing access to translations, and alternative formatting will likely read - "Chinese, Vietnamese, Haitian Creole, Portuguese, Cape Verdean Creole, Alternative Formatting : www.boston.gov/_____" Each language will be translated in that language. Let me know what you all think about this.
- [ ] We were told to remove the word Census from our language (title and url), so MOWA and LCA agreed to rename it Language and Communications Access & Childcare Survey
- [x] Removing words "it was" in the option for too difficult to find, so it reads "Too difficult to find".
- [x] Removing "it is" from the affordable option so it reads "Not affordable".
- [x] Removing the words "It is" from the far from work and high quality options on Q3. So they would read "Too far from home or work" and "Not as high quality as I would prefer...."
- [x] Removing "it" from family schedule so it reads "Does not fit family schedule".
IF POSSIBLE (if it does not fit we understand): Insert under child date of birth, the question: "Receives childcare government subsidy Y/N"

- There will likely be additions to neighborhoods, but we are waiting back from Sabino to get final edits: most likely Bay Village.

- Regarding digital: Elections would rather we link our survey after the census itself was submitted online. It sounded like they are okay to have it linked directly from the main cover page of the Elections census, but taking a look at it, I'm not sure how or where.

**Comment by sebastianebarb** [comment]
![IMG_1494.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c1b9bd1cd3d7f0dbabf301b44fff9e2c4533317346f67c73d5b47dba152e595d0a4ef943595f46adac8d2df5bf2e6c981e5ab38532022d8c6853beb2901eb60bbb258f4c8db2b48a4fc4eb3b20f5c6.JPG)

**Comment by sebastianebarb** [comment]
- Fri, Nov 30, 12:26 PM
- [x] Change wording in Q2 from "Languages used other than English" back to "Primary language(s) used other than English"
- [x]  Change wording after question 3 to "Check any or all that apply."
- [x] Add date format in parentheses (MM/DD/YYYY) for question 3 after "child date of birth".
- [x] . Add question directly under "child date of birth": Do you currently receive a government subsidy/voucher for childcare? This question will also need check boxes.
- [x] Rearrange order of questions. Move "What is your current childcare arrangement for each child?" and the respective responses ahead of "What difficulties do you experience with childcare?". Also, please add the word "current" before childcare arrangement in the wording of the question.
- [x]  Take out "none", "I would prefer a different setting" and "other (please specify):" as options under "what difficulties to you experience with childcare?" and take out "other (please specify):" under "what is your current childcare arrangement?"
- [x]  Change wording from "Too far from home or work" to "Too far/hard to access from home or work". And change "Does not fit family schedule" to "Does not fit family/work schedule"
- [x]  Change "Parent/guardian stays home to care for child but prefers to work" to "Parent/guardian stays home to care for child but needs/wants to work". Would it be possible to have three smaller checkboxes to specify gender of parent: (Male, female, non-binary). We'd love your opinion on this one.
- [x] Change wording from "Home-based provider program" to "Home-based provider program/ Family child care"
- [x]  Separate "Center-based program" and "Head Start/public school" into separate lines.
- [x]  Reword last question: What other difficulties do you experience with childcare?

**Comment by sebastianebarb** [comment]
final (hopefully) batch of feedback:
- [x] We will change the title to Language, Disability and Childcare Survey
- [x] We will add the neighborhood, Bay Village.
- [x] We agree, let's keep the grid, forget the checkboxes. We thought the checkboxes could replace the grid, having both looks too busy.
- [x]  Include two slashes on the date of birth "  /   /   '" so people can fill in the blank.
- [x] Include Y / N in the answer space for the second childcare question (subsidyvoucher question) so people can check or circle Y or N.
- [x] The center based options are as follows:
              - [x] Center-based Program
              - [x] Public school /Head Start Program 
              - [x] Under date of birth in Language Access section, there are only three Y's instead of four.
- [ ]  We will remove the word Ability, where it currently says "Ability/Disability"
- [ ] We will change the phrase "Has difficulty dressing or bathing" to "Has Mobility Disability"
- [ ] Sebastian, the missing Y in date of birth is in the childcare section, not language access.

**Comment by sebastianebarb** [comment]
[883_07_Census Form .pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0ccc91cd2d496acecb150b14eb0b226542a336b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e38f8d4f3818021a8ef85e27ed.pdf)

**Comment by sebastianebarb** [comment]
Change the introduction to "The City of Boston is collecting this information to support the needs of all residents. This survey focuses on language, disability, and childcare services. Please, check any and all that apply."
Change to a lower case p in the word "program" for 'Center-based Program' and 'Public school /Head Start Program' options.
Can we remove the blank second page from the file?
We can use this shortcut for the link: boston.gov/language-disability-childcare-survey  
Translate the language names at the bottom of the page:
Chinese : 
中文
Vietnamese : 
Tiếng Việt
Haitian Creole : 
Kreyòl ayisyen
Portuguese :
Português
Cape Verdean Creole : 
kriolu

Also, need a comma between "Disability" and "and" in the title. An oxford comma, so to speak! 

[883_08_Census Form .pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0ccc91cd2db96acecb150b14eb0b226542a336b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e38f894b361e07118bfe5827ed.pdf)

**Comment by sebastianebarb** [comment]
- [x] Remove the MM/DD/YYYY from the Year of Birth question in Question 2.
- [x] Remove spaces between dashes in Public School/Head Start program option in Question 3.
- [x] Remove spaces between dashes in Too far/Hard to access from home or work option in Question 3.
- [x]  Remove "Please, check any and all that apply." from the instructions in Question 3.

**Comment by sebastianebarb** [comment]
[883_08_Census Form .pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0ccc91cd2db96acecb150b14eb0b226542a336b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984ec1e23c20e38f874e3717041f8cf75427ed.pdf)

**Comment by sebastianebarb** [comment]
[Uploading 883_09_Census Form .pdf...]

**Comment by sebastianebarb** [comment]
[883_09_Census Form .pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0ccc91cd2da96acecb150b14eb0b226542a336b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e38f874d3e1f071e8cff5c27ed.pdf)

**Comment by sebastianebarb** [comment]
[883_11_Census Form .pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46b0ccc91cd3d296acecb150b14eb0b226542a336b48e13b628ae92dbc56395b4d5a49ff415f5a11fbfc8129f3b669728b5c09bc84695927cf2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e38e8c4c3f1b021d8afd5c27ed.pdf)
