### ISSUE TITLE
Costume firearms graphic

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/design-team-workflow#884]
Replica firearms as part of your halloween costume will not be tolerated. We wish for everyone a safe, respectful, delightful parade and Halloween celebration.

Let's also get the "Have a safe, fun Halloween" B one ready for Sarah and a Red Sox celebratory one. Sebastian mentioned these were all ready. Thank you

**Comment by carolinestj** [comment]
Halloween safety tips https://www.canva.com/design/DAClVujUTEs/share?role=EDITOR&token=847xOur_mMtD5rHBXtRFuw&utm_content=DAClVujUTEs&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by carolinestj** [comment]
Parade safety tips 
https://www.canva.com/design/DADHeo5r1Oo/share?role=EDITOR&token=fpxNHC527nAUYNuZyNlC2Q&utm_content=DADHeo5r1Oo&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton
