### ISSUE TITLE
Build Mockup of Birth Certs Onboarding User Flow

### ISSUE THREAD

**Issue by rachelbraun** [CityOfBoston/design-team-workflow#931]
### Ask is to create mockups of the onboarding flow for the birth certs web app.

**1. Ordering for Page**

First part, language reads: Who are you ordering a birth certificate for?
Buttons include:
    - Myself
    - Someone Else

Wireframe:
![img_7109](https://user-images.githubusercontent.com/35377030/48855881-febb0180-ed82-11e8-831f-c00ee07527c1.jpg)

Second part, language reads: Is this your...?
Buttons include:
    - Spouse
    - Child
    - Parent
    - Family Member
    - Friend
    - Client

Wireframe:
![img_7112](https://user-images.githubusercontent.com/35377030/48856138-a3d5da00-ed83-11e8-85a1-034d731e4b7c.jpg)

**2. Born in Boston Page**

First part, language reads: Were you born in Boston? / Were they born in Boston? 
Buttons include:
    - Yes
    - No
    - Don't know

Wireframe:
![img_7109 2](https://user-images.githubusercontent.com/35377030/48856213-d41d7880-ed83-11e8-8ce5-efa09df5dcb0.jpg)

Second part, language reads: Were your parents living in Boston at the time of your birth?
Buttons include:
    - Yes
    - No (If no, info blurb saying: We only have records for people born in the City of Boston. Please contact the city or state where they were born to find the record.)
    - Don't know

Wireframe:
![img_7112 2](https://user-images.githubusercontent.com/35377030/48856397-45f5c200-ed84-11e8-96d4-fe41c0f30527.jpg)

**3. Name at Birth Page**

First part, language reads: What was your name at birth? / What was their name at birth?
Text boxes include:
    - [First name] text box
    - [Last name] text box
* Info blurb: Please use the name they were given at birth. If they were adopted, use their post-adoption name.

Wireframe:
![img_7109 3](https://user-images.githubusercontent.com/35377030/48856495-86edd680-ed84-11e8-8e99-58ab92fc8f57.jpg)

**4. Date of Birth Page**

First part, language reads: What day were you born? / What day were they born?
Text boxes include:
    - [Month/Day/Year] text box

Wireframe:
![img_7113](https://user-images.githubusercontent.com/35377030/48856585-ca484500-ed84-11e8-88fd-f8d656b9ee53.jpg)

**5. Parents Married at Time of Birth Page**

First part, language reads: Were your parents married at the time of your birth? / Were their parents married at the time of their birth?

Buttons include:
    - Yes
    - No
    - Don’t know

Wireframe:
![img_7113 2](https://user-images.githubusercontent.com/35377030/48856794-61ad9800-ed85-11e8-8187-df8e90db6ae1.jpg)

**6. Parents Names**

First part, language reads: What are your parents' names? / What are their parents' names?
Text boxes include:
    - Parent 1 (Parent that gave birth): [First name] [Last name] text box
    - Parent 2: [First name] [Last name] text box
        * Info blurb: Please use the name each parent was given at birth.

Wireframe:
![img_7113 3](https://user-images.githubusercontent.com/35377030/48856780-58bcc680-ed85-11e8-8f46-2208d9cfdbd2.jpg)

**Comment by carolinestj** [comment]
Inspo images:
![Screen Shot 2018-11-28 at 9.26.37 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456fb6b7191a371f1102d4f5c585edd3c4a4356bcbbd671f3e57862804e0eea826d5871933a14a4bad71fea03bb20891ed0b2bad945d2f42f67b6d5db1063474f4dcbed5727a19e41c95df248e54c50a6103463e7702431.png)


![8e858b4fe66839f10431f7504435c0cf.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46b091c276da81fd89ece915fc0ea992781673207802f47e20d1b77bea412b02094d52be011a001ea9aacd39aca43977d95c0ce8846a5a7cc46811f9ba831fbd50ef248d1c8ca4a0980e91b6697abad2c51a7c0c0f0a88f75734a59d48cc59f349e44852a313242e.png)


![1_fW2bS_5CJLCZd1ZpATHokA.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46b9ab9c14d0819ab0bc9c69887eca90787c37521d2cac2051c7af6aaf50740b0a0c0abe4b4a5a43aff98e2ef3b1397888090bb8d36c5f76976815aaeb8b0da313f871d51bdaebe5c01982fa3737e683854e3b1a061c88fa5430a99a43c14abb.jpeg)
![TurboTaxTeardown5.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46dc8188218db7a897ddba42b659ff832713653f6b14b1247a80e03cfd183954580c4eab440d5841f4fbdc2bf3b43d70880d5ee9d73e5666da2f53fde6d640e258f075c95d8fa4bd8346c1ed3926e38a894d3d1f001a8ced10.png)


![best_Screen_Shot_2016-04-26_at_22.59.20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ea918937bdb0aa9decba4d9b6ef89b3d7975237852ee7b24c8b17e80436f3e5d5d50a948465d44eee59b6be4e96625d91819e7c3685827c63a14f9bf8717bd54ba75894e85b4eddf48c6bb3437fb99cd1e604a5a45d0b50877b29359c951fc4ae44956a0123061e5753f79448653.png)


![1_eBEpHbUKkMBa-9_n05H2Hg.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46b9ab9f01a793818ddc9448897ff1d9707929237c2cf10377c7af6aaf50740b0a0c0abe4b4a5a43aff98e2ef3b1397888090bb8d36c5f76976815aaeb8b0da313f871d51bdaebe5c01982fa3737e589854e3b1a061c88f95f30a09c4cc14abb.png)


![829468edf2f9360e7f99f6ab777b650a.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46b0c6c377d4dbac8befed45fd0ea6c42c11212a7002f52a72d2b47fbd142e510e4d52be011a001ea9aacd39aca43977d95c0ce8846a5a7cc46811f9ba831fbd50ef248d1c8ca4a0980e91b6697abad2c51a7c0c0f0a8bfd5734a59d48cc59f04fe84454a21b242e.png)

**Comment by carolinestj** [comment]
Screenshots from Jessica:
![Screen Shot 2018-11-28 at 5.25.37 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456fb6b7191a37df1102e4f5c585ecc3c4a4356bcbbd671f3e57862804e0eea826d5871933a14a4bad71fea03bb20891ed0b2bad945d2f42f67b6d5db1063474f4dcbed5727a19041c95df248e44d54a3143f63e0742431.png)
![Screen Shot 2018-11-28 at 5.24.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456fb6b7191a37df1102f4f5a595ecc3c4a4356bcbbd671f3e57862804e0eea826d5871933a14a4bad71fea03bb20891ed0b2bad945d2f42f67b6d5db1063474f4dcbed5727a19141c95df248e44d54a31b3660e4772431.png)
![Screen Shot 2018-11-28 at 5.24.43 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456fb6b7191a37df1102f4f5b5c5ecc3c4a4356bcbbd671f3e57862804e0eea826d5871933a14a4bad71fea03bb20891ed0b2bad945d2f42f67b6d5db1063474f4dcbed5727a19041c95df248e44d54a31b376be6712431.png)

**Comment by sebastianebarb** [comment]
[Uploading Sebastian notes on birth cirts.pdf...]
