### ISSUE TITLE
Plastic bag ordinance billboards

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#933]
make billboard ads 

https://docs.google.com/document/d/1tobhrG7ImcIf6E8ovlyMT6UsidMSZMzvE2EJ2sWxNXg/edit?ts=5bf476de

**Comment by carolinestj** [comment]
[Production-MA-Boston-Outdoor-Digital Bulletin-14x48.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46d88695279780bd86e6b10e897cbdb62655337c27498c3e6481ec27ad0f5f0808060afd1d482d01a0a5dc6fffe821718e140fe5c3714d3484624bf9ebc60db513bf27d84f82b3e98d49c8ea6825b2898e4f3c4f501c8fac5427bc8b099906a214bc141ff1512469f477317646911a762e6d6620a8f8d8538f972d.pdf)

**Comment by carolinestj** [comment]
[Digital Bulletin Specs - 14x48 and 10'6x36.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cc9d9d2a9682a5cfcbaa4fa858e49d270614632c07b06b3dc5b27ca71623410e011abc40584842b4fa8f39baa47c32d5065ebe957f5566c33a42acbf874ab804b222de4fd0b4bd8a4e91bd3923b4829d532c5c5446dda0006ceacc09da52e44ae64754a1173561e0773e7e40931c703e26.pdf)

**Comment by carolinestj** [comment]
[BOS-DG-ROTDOM Spec.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cabba96ea6a4e4bdc68b678b70b0a7394324316546b3397f8fe62bab0021435a581dac465d0a43f9f18b7ea6e33e718a5e5ab8d56b0c7dd42103eee9dc4be05ce36ade0d97bcae8b4bcae93821e4888b483e1a051d8cfc4f78.pdf)
[BOS-DG-506_Spec_cc.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cabba96ea6a4e4dab9e97c974df597164524316546b3397f8fe62bab0021435a581dac465d0a43f9f18b7ea6e33e718a5e5ab8d56b0c7dd42103eee9dc4be05ce36ade0d97bcae8b4bcae93821e4888b483e1a061b89fc4f78.pdf)
[BOS-DG-504_Spec.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cabba96ea6a4e4dab9eb7c974df5976b0a65633b0ba92e7391a172fd172c025f584bf9465d5746a9f9dc29a7b63e21df580dbed87f4366846c4ff8e7df46f554f832815d84b1b68b49c4eb3e21e08b8b4a3f17010ac4.pdf)

**Comment by jfalvey** [comment]
please also include a design spec'd out for the JCDecaux signage. We have 4 content slots we can use with them and will be sending those separately and directly (not through Environment). The four will be: what you can do on Boston.gov (they have this from sebastian already), 3-1-1, plastic bag ban, Code Red sign-up for snow season (and/ or could use in context with the zombie graphic) :) Run language by Sarah, James, and I'd like to see them too. Thank you! 
resolution has to be @3840x2160

**Comment by jfalvey** [comment]
@sebastianebarb @carolinestj see above :D
