### ISSUE TITLE
Pilot program PDF report

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#995]
Contact: Casey Brock-Wilson

Hi Sebastian and Caroline, 

Just wanted to give you a heads up on something that is coming down the line -- we are creating a short PDF report about the FY18 PILOT program that we are hoping to publish quickly. I am waiting to get the final go-ahead on the report link, but wanted to give you guys some time to get started. 

I apologize for the short notice on this - if you don't have time, just let me know! And of course, happy to answer any questions!
Report Cover Page - "City of Boston Payment in Lieu of Taxes (PILOT) Program Fiscal Year 2018"
Report [FINALIZING RIGHT NOW]
Appendix A Cover Page - "Appendix A: FY2018 PILOT Recap"
FY18 PILOT Recap
Appendix B Cover Page - "Appendix B: FY2018 PILOT Community Benefit Program Examples" 
PILOT Community Benefit Program Examples

**Comment by carolinestj** [comment]
[fy18_pilot_contributions_revised_on_november_30_2018_final_print.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46ee8dcb7bbd93a083e6ab7ca752fe803b4f25663d0dac2563baf12da94b68040b3011f22e060002a9a4db7ee4d93f70e55e0becd902092d986c4dc3f8c046e145a83c990fc7e9e6df1f84fa3737e28cdc4f391b501f8cf75f60a0cc49c958f41ab44953f71a247ff434672213cb432c663e2534a1eede5f8d8465a0bf192d52cdebe2ff1512b331.pdf)

[PILOT Community Benefit Program Examples.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46d8bdb60cb6c38a80e4b256aa54e48d6964227d2c02aa3f30b5f127b8507a0c4f2a06fd1c180311bfeb9539e6f4632adf0f4fffdb7f5a73953d16a9ed851ab703ef20de4d84b6bedb19c4ee6e2cf5979d0d6f405147d4a61760e28b41da59f141e04851a11a3467e37f367c46950c38.pdf)

https://docs.google.com/document/d/1Ju154ruEteb30cv198QwkKOxfAEFk0_diN-2jmuteIo/edit

**Comment by sebastianebarb** [comment]
@carolinestj  is this still open?
